### ISSUE TITLE
constexpr for const variables and some if statements

### ISSUE THREAD

**Issue by rsjaffe** [cameron314/concurrentqueue#104]
I'm using concurrentqueue.h, and it appears that most if not all of the const variables can be constexpr and some if the if statements can be. Using constexpr has the potential to make the code faster (the compiler may be smart enough to figure this out without our help) and makes it easier to add static_asserts. 

The variables all look to be C++11 compatible, so should be supported by most compilers.

For the if statements, the ones with the following format can be constexpr--it'd just simplify code generation and perhaps make things a touch faster.

            if (INITIAL_IMPLICIT_PRODUCER_HASH_SIZE == 0) return false;
             return /*some return value here*/;

can become

            if constexpr (INITIAL_IMPLICIT_PRODUCER_HASH_SIZE == 0)
                return false;
            else
                return /*some return value here*/;

Other if statements that can be constexpr include:

            if (canAlloc == CanAlloc)
            if (context == explicit_context && BLOCK_SIZE <= EXPLICIT_BLOCK_EMPTY_COUNTER_THRESHOLD)

MSVC supports it beginning in 15.3. I'm not sure about other compilers.

**Comment by cameron314** [comment]
`if constexpr` is new in C++17. There's already a pull request that adds this to various expressions, with the verdict that I'll accept it eventually after C++17 support has become mainstream.

For the samples that you've highlighted, the compiler absolutely does eliminate the branches depending on the values known at compile time (with optimizations enabled, of course).
