### ISSUE TITLE
perf profiling

### ISSUE THREAD

**Issue by risingsun007** [cameron314/concurrentqueue#106]
I did profiling with perf on linux on my program using concurrentqueue and the results indicated that concurrentqueue size_approx() is slow.

**Comment by ouliuquan** [comment]
I agree with that cause we have talk about this, post the mail here:

> Hi, I am Michael, First to all, thanks to you high-performance lookfree queue.
I am using your readerwriterqueue in my little project now. And I found that the size_approx() function
running too slow. I know it has to be frozen all the inner queue when we wanna to get the right size.
But think about this, when we just want some fuzzy size frequently (not precise one), that will be a lot time
to wait, 100-times size_approx() about 5s.
So here I am thinking that maybe add a size_fuzzy() function will be a good idea. I would like to do that,
but my program ability limited ^_^. And if you want a test, I am glad to help. 
Sincerly.

> Hi Michael :-)
`size_approx()` is actually wait-free in the sense that it doesn't freeze the queue -- the other thread is able to continue modifying the queue at the same time.
However, it walks all the inner blocks of the queue to sum their sizes, which is O(n). For queues with many elements (especially with smaller block sizes) this can get quite expensive. Still, 50ms per call seems surprisingly high -- how many elements are in your queue? What max block size are you using? Are you compiling with optimizations enabled?
A workaround is to use the blocking version of the queue (`BlockingReaderWriterQueue`) which adds a slight overhead to each enqueue/dequeue operation but provides a very fast O(1) `size_approx()` implementation.
Cameron

The way to fixed this issuse I still had not find yet.
Hope some cool guys to make it fast.

**Comment by cameron314** [comment]
Note that that email was with regards to my `ReaderWriterQueue`, not this `ConcurrentQueue`, though the end effect is the same for similar reasons.

@risingsun007: Why are you using `size_approx()`?

**Comment by cameron314** [comment]
Ah, I see. There's two `size_approx()` functions in the `ConcurrentQueue` -- the first, public one is the one that iterates every subqueue and can be slow. The second, internal one is supposed to be very fast -- just two atomic loads and a subtraction.

Are you compiling with optimizations enabled?

**Comment by cameron314** [comment]
Note also that using the consumer-token version of `try_dequeue` should speed up dequeuing appreciably (it is several times faster under contention, and does not call the internal `size_approx()`).

**Comment by risingsun007** [comment]
what is the consumer-token version of try_dequeue?   And I noticed that enqueue has a move constructor which I'm not currently using.

**Comment by cameron314** [comment]
See the [README](https://github.com/cameron314/concurrentqueue#tokens).
