### ISSUE TITLE
Compile error with std::unique_ptr<>

### ISSUE THREAD

**Issue by PhilipVinc** [cameron314/concurrentqueue#107]
Hi and thanks for your very useful library. 

Until now I used it to store pointers to objects, and now I would like to upgrade to std::unique_ptr<myType>, but I see that I get several compile errors.

Is your queue not supposed to use unique_ptrs?

for example:
```
#include <iostream>
#include <memory>
#include "concurrentqueue.h"

using namespace std;
using namespace moodycamel;

struct pinco {
  int a;
};

int main()
{
  moodycamel::ConcurrentQueue<std::unique_ptr<pinco>> q;
  for (int jj=0; jj<4; jj++) {
    std::unique_ptr<pinco> p (new pinco); 
    p->a = jj;
    q.enqueue(p);
  }
  pinco *p;
  while (bool found = q.try_dequeue(p)) {
    cout << "Got element" << endl;
    if (found) {
      cout << p->a << endl;
    }
  }
} 
```

**Comment by cameron314** [comment]
`std::unique_ptr` is supported, but your sample code contains a few errors.

1) When enqueueing, you can't copy a `unique_ptr`, so it has to be explicitly moved:

    q.enqueue(std::move(p));  // #include <utility> for std::move

2) When dequeueing, you need to pass an object of the same type as your elements:

    std::unique_ptr<pinco> p;  // instead of pinco *p;
    while (bool found = q.try_dequeue(p)) {

**Comment by PhilipVinc** [comment]
Thanks, I did not realise we had to move it explicitly.
And is it possible to use the enqueue_bulk method from a std::array<std::unique_ptr<**>> ?

**Comment by cameron314** [comment]
Explicit moving is not particular to my queue, but C++11 and above in general.
Yes, you can do a bulk enqueue, but you still have to move the objects; so, you'll need to wrap the `begin()` and `end()` of the array with `std::make_move_iterator()`.
