### ISSUE TITLE
Rename `likely` and `unlikely`

### ISSUE THREAD

**Issue by Leandros** [cameron314/concurrentqueue#108]
Both `likely` and `unlikely` are commonly defined macros in many projects, and will interfere with the equally named functions defined in `moodycamel::details`.
My suggestion is to replace them with equally named macros, and only define the macros if they haven't been defined before (in which you also need to undefine them again, to not pollute them into the clients project).

**Comment by cameron314** [comment]
Should be fixed!

**Comment by Leandros** [comment]
Awesome, that was a quick fix. Thanks!
