### ISSUE TITLE
Failed to compile in Visual Studio 2017

### ISSUE THREAD

**Issue by SE-June** [cameron314/concurrentqueue#113]
To be more precisely speaking,
With the Compiler Option, "/permissive-"( C/C++ => Conformance mode)
It failed to compile.

**Comment by SE-June** [comment]
My Suggestion:
 I added the following two forward-declaration 
above "struct ProducerBase : public details::ConcurrentQueueProducerTypelessBase"

    class ExplicitProducer;
    class ImplicitProducer;

**Comment by SE-June** [comment]
Yes, It works
I have fixed it with your remedy.

**Comment by SE-June** [comment]
Sorry for my mis-information
With your remedy, It is just ok for including the header file ,"concurrentqueue.h"
When I try to instantiate "ConcurrentQueue",  the same error popped up.

I am not sure but friend expression does not seem to be related to forward-declaration.
The point is that forward-declarations are required for the both ExplicitProducer and ImplicitProducer

My fix is follows

    friend struct ProducerToken;
    friend struct ConsumerToken;               =>  struct ExplicitProducer;
    friend struct ExplicitProducer;                       struct ImplicitProducer;
    friend struct ImplicitProducer;
    friend class ConcurrentQueueTests;


As of C++11, Inner Class can access every members of outter class, as long as I know.

**Comment by cameron314** [comment]
Yeah, I'm not sure why I needed those friend declarations in the first place. I'll leave them there just in case.

**Comment by cameron314** [comment]
Should be fixed now. Thanks for taking the time to investigate and report this!
