### ISSUE TITLE
how to traversal your concurrentqueue?

### ISSUE THREAD

**Issue by githublet** [cameron314/concurrentqueue#117]
Some time I don't want to dequeue,just want traversal the q,
May be initial two concurrentqueue q1 q2 also can traversal,
tmp =q1.dequeue ;
q2.enqueue(tmp);
but I don't want to do like this.

**Comment by cameron314** [comment]
This is not currently possible, sorry. Traversal is fundamentally racy if other threads are accessing the queue at the same time, which makes it very difficult to implement in an efficient, thread-safe way.
