### ISSUE TITLE
concurrentqueue vs lmax disruptor: please add to performance benchmark

### ISSUE THREAD

**Issue by clear-m** [cameron314/concurrentqueue#118]
Hi there!
I was very excited to read this performance related discussion - https://www.reddit.com/r/cpp/comments/63rt56/the_performance_benchmark_of_boostlockfreequeue/

I hope there will be lmax disruptor comparison once in your benchmark section - http://moodycamel.com/blog/2014/a-fast-general-purpose-lock-free-queue-for-c++#benchmarks

Thank you for your project! You did a great job!

**Comment by cameron314** [comment]
Sorry, I don't have the time.
