### ISSUE TITLE
This assertion, what exactly does it mean?

### ISSUE THREAD

**Issue by pronvit** [cameron314/concurrentqueue#119]
https://github.com/cameron314/concurrentqueue/blob/8f7e861dd9411a0bf77a6b9de83a47b3424fafba/concurrentqueue.h#L1916

I see the comment but can you explain what it means in terms of what I may be doing wrong if that assert fails for me from time to time, i.e. what [incorrect] usage of the queue should be causing it to fail?

**Comment by cameron314** [comment]
It's an internal invariant which should never fail. Do you have code that can reproduce this?

**Comment by pronvit** [comment]
I'll try to provide something, although it's not easy to reproduce, it fails after hours of running (but always on the same line). Btw, I'm running on ARM, I can't say for sure right now if it failed the same way on x86, I'll do more testing.

**Comment by pronvit** [comment]
`dequeueOptimisticCount` and `dequeueOvercommit` are only incremented, shouldn't one of them overflow at some point and trigger this assertion?

**Comment by cameron314** [comment]
You're right of course. That should be a `circular_less_than` in the assertion.

**Comment by pronvit** [comment]
How is it not failing for everyone? It takes only about 4 hours in my scenario to crash. Also, the easiest for me is just to remove the assertion then?

**Comment by cameron314** [comment]
Probably because the default is to use 64-bit indexes when possible.
But I think there's actually a real bug on wrap-around -- I have to think more about this. I don't think it's just the assertion that's buggy at this point.

**Comment by pronvit** [comment]
Seems to work so far for a day now that I disabled assertions.

Also, my queue is filled and emptied all the time. It would help if there were a (cheap, not creating a new queue) way to reset the queue, including these counters, when I know it's empty before enqueuing the next batch of items.

**Comment by cameron314** [comment]
All should be well now.
