### ISSUE TITLE
Crashes when used outside main?

### ISSUE THREAD

**Issue by SephVelut** [cameron314/concurrentqueue#121]
```
void fails() {
    BlockingConcurrentQueue<char>* q = new BlockingConcurrentQueue<char>();
    ProducerToken* ptok = new ProducerToken(*a);

    thread([&q, &ptok]{
        while(true) {
            q->try_enqueue(*ptok, '1'); // crashes here exit code 11
            std::this_thread::sleep_for(std::chrono::milliseconds(200));
        }
    }).detach();
}

int main() {
    fails();
    std::this_thread::sleep_for(std::chrono::milliseconds(10000));
}
```

Why does this crash? Keep in mind that if I take the code in the fails procedure and place it in my `main()`, then just like that it works miraculously. I'm on OSX if that matters.

**Comment by cameron314** [comment]
It crashes because in the lambda you're referencing two local variables after they've been destroyed when the function returns...

**Comment by SephVelut** [comment]
I thought when since I'm using `new` I'm allocating to the heap and they wouldn't be destroyed?

**Comment by cameron314** [comment]
The objects are indeed on the heap, but the pointer variables themselves are being passed by reference to the lambda. Pass them by value instead to fix the undefined behaviour.

**Comment by SephVelut** [comment]
Ah. I have a use much wider than the simplified example I gave. Basically I'm using the Gstreamer C library and registering a callback to one of its threads `gst_app_sink_set_callbacks(...&args)`. I'm packing the queue into an initialized struct and passing it into the `gst_app_sink_set_callbacks` as the future argument to my callback function. I'm assuming the example I gave is the same, but I'll close the issue since it appears I'm just doing something wrong.

**Comment by cameron314** [comment]
No worries. Feel free to reopen if necessary.

**Comment by SephVelut** [comment]
I'm almost 100% certain its some weird interaction between Gstreamer and ConcurrentQueue. I don't actually get the same problems when using a pointer to one of my own objects and the addresses printed are the same. Furthermore, here is the code that makes it """""""""""work"""""""""""


```
cout << app.queue << endl;
cout << &app.queue << endl;
```

I'm not kidding. Delete any one of those std::cout lines and the crashes from concurrentqueue come back. I.. I dont know. Here's a full gist https://gist.github.com/SephVelut/6bddcfb5056e5819ab7128026677d59f

**Comment by cameron314** [comment]
Looks like memory corruption, judging from the impact of the couts.

Actually, looking at the gist, it seems like you have the same bug as the original exmple code -- a pointer to `app` is passed to gstreamer (and later the callback), but app is declared on the stack and is destroyed when the function returns. Try making app either global, static, or instantiated on the heap instead.

**Comment by cameron314** [comment]
You're welcome :-)
The extra couts probably changed the way the stack was laid out, allowing the memory where app was to remain unchanged even though the variable technically no longer existed.
