### ISSUE TITLE
Adding a minimum count to wait_dequeue_bulk_timed

### ISSUE THREAD

**Issue by ryanolson** [cameron314/concurrentqueue#122]
Currently, `wait_dequeue_bulk_timed` will complete on timeout or if it finds a single element in which it can dequeue.  

ASK: Add a `min` value to the interface to allow the `wait_dequeue_bulk_timed` method such that the method only returns if at least `min` items are dequeued or if `max` items are dequeued or if the timeout is reached. 

WHY: Under some circumstances, batching for example, we want our consumer to have as large of batch as possible in a given time window.

Setting `min = max` or `min = max/2` would be a very effect batching strategy.

**Comment by cameron314** [comment]
This can be done in the application code, although I understand that it's annoying to do so. The internal OS semaphore will unblock as soon as a single item is available (which is not something that can be changed), so the only way to implement this is to loop-wait.

**Comment by cameron314** [comment]
A few things: 
- Why is `totalCount == 0` an exit condition of the inner loop?
- `token` can't be used by multiple threads, but it doesn't have to be declared `thread_local` in this example
- Never use `std::chrono::system_clock` for timing anything -- this will break on daylight savings time, leap seconds, manual clock changes, etc. Use `std::chrono::steady_clock` instead.

**Comment by ryanolson** [comment]
Thanks for suggests and the pointer on the `steady_clock`.

Regarding `total_count`, each time you fail to get a result and timeout, you need reset your `start` time.  Once you get an item from the queue, then you stay in the `do/while` loop until one of the other two conditions are met.

**Comment by cameron314** [comment]
Ah, I see. In that case, looks good!
