### ISSUE TITLE
Strange behaviour: search the item with try_dequeue and enqueue never ends here

### ISSUE THREAD

**Issue by clear-m** [cameron314/concurrentqueue#123]
Hi there!

Please have a look at the sample below - it is never ends in busy loop.
It is looks like that we enqueue at the beginning of the queue here.

```
int main()
{
	moodycamel::ConcurrentQueue<int> event_queue;
	
	std::thread([&]() {
		int elm{1};
		event_queue.enqueue(elm);
		if (event_queue.try_dequeue(elm))
		{
			event_queue.enqueue(elm);
		}
	}).detach();

	std::thread([&]() {
		int elm{2};
		event_queue.enqueue(elm);
		if (event_queue.try_dequeue(elm))
		{
			event_queue.enqueue(elm);
		}
	}).detach();

	std::thread([&]() {
		int elm{3};
		event_queue.enqueue(elm);
		if (event_queue.try_dequeue(elm))
		{
			event_queue.enqueue(elm);
		}
	}).detach();

	int target{3};
	int item{};

	while (event_queue.try_dequeue(item))
	{
		std::cout << item << " " << event_queue.size_approx() << std::endl;

		if (item == target)
		{
			break;
		}

		event_queue.enqueue(item);
	}

    return 0;
}
```

If we change the sample a little, everything will work as expected:

```
int main()
{
	moodycamel::ConcurrentQueue<int> event_queue;
	
	std::thread([&]() {
		int elm{1};
		event_queue.enqueue(elm);
		if (event_queue.try_dequeue(elm))
		{
			event_queue.enqueue(elm);
		}
	}).detach();

	std::thread([&]() {
		int elm{2};
		event_queue.enqueue(elm);
		if (event_queue.try_dequeue(elm))
		{
			event_queue.enqueue(elm);
		}
	}).detach();

	std::thread([&]() {
		int elm{3};
		event_queue.enqueue(elm);
		if (event_queue.try_dequeue(elm))
		{
			event_queue.enqueue(elm);
		}
	}).detach();

	int target{3};
	int item{};

	while (event_queue.try_dequeue(item))
	{
		std::cout << item << " " << event_queue.size_approx() << std::endl;

		if (item == target)
		{
			break;
		}
	}

    return 0;
}
```
Please explain and advise us with the info of how can we avoid that trap.

**Comment by cameron314** [comment]
The queue assumes producers are independent (see the README). It is internally built of sub-queues, one for each producer. In your first example, you keep putting back the element that you take off; there's no guarantee that the next dequeue won't take from that producer queue (and indeed, it does so forever).

If you need a concurrent queue that is truly linearizable, I'm afraid you'll have to find a different implementation.

**Comment by clear-m** [comment]
Thank you for your implementation and response! I learned a lot from your project, but I need to ask this question to make sure that I understand everything.

Well, I think I need to read README next time)

And I wish this project to evolve, perhaps in truly linear, concurrent queue as well as concurrent and blocking.
