### ISSUE TITLE
Feature Request: Providing queue fd for monitoring via epoll() or poll() or select() APIs (avoid busy loop)

### ISSUE THREAD

**Issue by enthusiasticgeek** [cameron314/concurrentqueue#125]
It would be nice to monitor fd for available data on queue (if possible) in the future releases. This will be similar to msg_queue where we can get queue fd for monitoring via epoll() or poll() or select() APIs.

Basically want to avoid busy loop https://josephmate.wordpress.com/2016/02/04/how-to-avoid-busy-waiting/

CPU load is too high when there is no data in the queue, I can probably use conditional variable to reduce CPU load and wake up the thread when signal received, but that defeats the purpose of lock-free mechanism.

for now I am using     

`std::this_thread::yield(); // other threads can push work to the queue now`

Some people recommend futex

https://stackoverflow.com/questions/6089917/how-to-achieve-lock-free-but-blocking-behavior

But not sure if there is another elegant solution.

**Comment by cameron314** [comment]
Have you tried the `BlockingConcurrentQueue`?

**Comment by cameron314** [comment]
Fair enough. I can safely say that I won't implement this, though, for multiple reasons -- the first being that it's impossible to do in a cross-platform way, the second being that I'm not sure it can be done at all even on Linux (is there a way to get a descriptor from a semaphore?), and the third being that I have no time and energy to invest in new feature development for the foreseeable future. Sorry.
