### ISSUE TITLE
Implicit Producer(s) not Serialized in Single Thread

### ISSUE THREAD

**Issue by stefan-baranoff** [cameron314/concurrentqueue#126]
Under gcc 6.3.1 as part of devtoolset-7 on a CentOS 7.4 system we have code that uses the basic ConcurrentQueue enqueue/try_dequeue with implicit producers/consumers. We actually have MPSC semantics in production with no ordering requirements. However, our unit tests run single threaded so are SPSC but do have ordering requirements.

Under debug all of our tests pass flawlessly. Under release, however, we are seeing ordering violations. Digging into this some more it seems that the (very creative) thread identification mechanism is not actually identifying threads. It is identifying compilation units within threads. We have two separate .cpp files that enqueue (from the same thread) into the same queue and the ordering for each location was serialized but between the two was not, even from the same thread.

It turns out that moodycamel::details::thread_id() is static inline and contains a static thread local variable, x. It appears that the variable, x, is (sometimes) copied per-compilation-unit; possibly having to do with inline and not just static on the function but removing inline does not seem to help.

Obviously switching to per-thread producer tokens will resolve this but wanted to point it out in case anyone else was assuming the implicit producers were truly per-thread. I don't have a great answer for thread identification since std::this_thread::thread_id is so finicky; although it is std::hash-able and compare-able so it might be usable in your hash table with a bit of wrapping.

**Comment by samwise** [comment]
We are seeing ordering violations as well, in MPMC scenario, using gcc 7.3.0. We expected per thread ordering to be honored but that is not what we see in release mode.

**Comment by cameron314** [comment]
Thanks for this report! That's quite unfortunate; `static` variables within a method are supposed to only have one definition, but it seems this can be violated in some circumstances; the templated instantiations of course generate many definitions across compile units, but they're supposed to be folded together at link time. Sigh.

I need an integer ID for my hash table to work; I suppose I could cast the `std::thread::id` and hope for the best (that's essentially what I do on iOS where there's no thread local storage and all known implementations are just a wrapper around an int).

I think `std::this_thread::get_id()` is also relatively slow on most Linux libc implementations, I'll need to re-check this too.

Sorry for the lost time spent debugging this.

**Comment by cameron314** [comment]
Side note: This is generally easy to work around by using an explicit producer token that is `thread_local` (oh, the irony).

**Comment by waqqasjabbar** [comment]
Just wondering if this bug effects the Single producer, Single consumer version, in any way ?(https://github.com/cameron314/readerwriterqueue)

**Comment by cameron314** [comment]
No.

**Comment by cameron314** [comment]
This should hopefully be fixed: I've changed the `thread_id` function to no longer be `static`.
According to https://stackoverflow.com/q/185624/21475, the thread-local static variable within it should now be folded together across compilation units, instead of unique for each one.
