### ISSUE TITLE
队列是怎么出队入队的

### ISSUE THREAD

**Issue by Tgsgf** [cameron314/concurrentqueue#127]
你好，在使用您的concurrentqueue我有一个疑问:
1: 使用单一线程操作入队出队结果是理想的,一下代码
```
#include "stdafx.h"
#include "concurrentqueue.h"
#include <iostream>
using namespace std;

moodycamel::ConcurrentQueue<int> y;

void jiayi()
{
	int item;
	bool found = y.try_dequeue(item);
	if (found)
	{
		++item;
		y.enqueue(item);
	}
}

int main()
{
	for (size_t i = 0; i < 10; i++)
	{
		y.enqueue(i);
	}

	for (size_t i = 0; i < 10; i++)
	{
		jiayi();
	}
	
	for (size_t i = 0; i < 10; i++)
	{
		int item;
		bool found = y.try_dequeue(item);
		if (found)
		{
			cout << item << endl;
		}
	}
	return 0;
}
```
输出: 1,2,3,4,5,6,7,8,9,10

但是使用线程池的时候输入不一样的结果:
```
#include "stdafx.h"
#include "concurrentqueue.h"
#include "ThreadPool.h"
#include <iostream>
using namespace std;

moodycamel::ConcurrentQueue<int> y;

void jiayi()
{
	int item;
	bool found = y.try_dequeue(item);
	if (found)
	{
		++item;
		y.enqueue(item);
	}
}

int main()
{
        /* https://github.com/progschj/ThreadPool */
	ThreadPools pools(1); //ThreadPool
	for (size_t i = 0; i < 10; i++)
	{
		y.enqueue(i + 100 * i);
	}

	for (size_t i = 0; i < 10; i++)
	{
		pools.enqueue([]()
		{
			jiayi();
		});
	}
	pools.wait_until_nothing_in_flight();
	for (size_t i = 0; i < 10; i++)
	{
		int item;
		bool found = y.try_dequeue(item);
		if (found)
		{
			cout << item << endl;
		}
	}
	return 0;
}
```
则输出结果不是: 1,2,3,4,5,6,7,8,9
是不是ConcurrentQueue  出队入队都是随机的啊？

**Comment by Tgsgf** [comment]
我发现使用多线程以后,所有的ConcurrentQueue元素自动相应的分配给指定线程访问

**Comment by cameron314** [comment]
This is normal -- the queue is formed of a collection of sub-queues, one for each producer. The order between elements is only guaranteed on each sub-queue, but not globally. See the README for more details; if you need a global total order, I'm afraid you'll have to find another queue implementation.

**Comment by Tgsgf** [comment]
@cameron314  非常感谢您的解答

**Comment by Tgsgf** [comment]
@cameron314 这个队列目前正是我所需要的,只不过在测试中出现不一样的结果,这个ConcurrentQueue只有C++版本吗

**Comment by cameron314** [comment]
Yes it is for C++ only.

**Comment by cameron314** [comment]
Let me know if I misunderstood/didn't answer any of your questions, Google-translate is not always super clear :-)

**Comment by Tgsgf** [comment]
@cameron314  Well, I'm not good at English, and I think of that too, so I'll solve it directly in Chinese. Thank you very much for your answer.

**Comment by yxwsbobo** [comment]
....

**Comment by HaoLiuHust** [comment]
@cameron314 Could you recommend a queue than can guarantee the order?

**Comment by cameron314** [comment]
I don't know the others very well. Maybe have a look at the various Boost or Folly queues?
