### ISSUE TITLE
Concurrent Queue As MultipleProducer and Single Consumer

### ISSUE THREAD

**Issue by abhit011** [cameron314/concurrentqueue#128]
@cameron314 

I am using this Concurrent Queue and there are some anomalies I want to understand.

I have created a single Concurrent Queue and its handle has been shared among Multiple Producer Threads, which means that there are Multiple Producers producing the data to a Single Thread
I am doing like `queueHandle->try_enqueue(myTempPbject)`

And there is **single Consumer Thread ** which is consuming the data from the queue,
What I have observed that RAM keep on growing, it started with 144 MB Ram and with in 20 minutes shoot to 170 MB RAM.  
The Structure is of size 156 bytes . Please tell me how to overcome this.

**Comment by cameron314** [comment]
How many different threads do you have? Are there new threads being created? How many elements are being put into the queue? How many elements are left in the queue after 20m?

**Comment by abhit011** [comment]
@cameron314 

I create thread Pool at the beginning of my program and there are total **48 Producer threads.** Those 48 Producer Threads keep on enqueuing the data at every second <the rate varies from 100 objects to 500 objects per second>. 
There is single Consumer thread ,I did not check how many elements are left in queue after some time, **BTW does there exist any API to check that ?**

But other than that, I also ran a sample program where in Main thread I kept on enqueuing and dequeuing too in the same loop,  that also has the similar repercussion..

**Comment by cameron314** [comment]
48 threads * 300 objects/s * 20 minutes * 60s/m * 156 bytes is an average of ~2.5GB. So, anything from a few bytes up to a few GB of usage is normal depending on the peak number of items in the queue (once memory is allocated to the queue, it doesn't like to let it go).

You can determine a close estimate of the number of items in the queue using the `size_approx()` method.

A loop that enqueues and dequeues at the same rate, from the same thread, should never see memory grow without bounds -- I'd be interested in seeing your test case for this.

**Comment by abhit011** [comment]
300 objects are not per thread, it's in total . Cummulative of 48 threads ...

**Comment by abhit011** [comment]
As it was my mistake, I have written a custom data structure where I was flushing everything but not the root node.. Hence root node was not getting deal-located that leads to the increase of RAM , my bad.

Is it possible to pre allocate 10K nodes worth data in concurrent queue , which means 10k * 156 bytes. So that at least the RAM does not grow or shrink ... and if at any time there was 10K entries inserted into the queue, i am also okie that further

**Comment by cameron314** [comment]
There's an overload of the constructor that allows a specified number of element slots to be preallocated. You can ensure no additional memory is allocated by using `try_enqueue`, however: Keep in mind that the queue is organized as a set of independent sub-queues, one for each producer. This means that a little more than 10K slots may actually be reserved since producers claim entire blocks at a time. There are also certain other internal structures (like the hashtable mapping thread IDs to sub-queues), that may at some point need resizing and will cause try_enqueue to fail; in this case it may be useful to look at the default sizes in the traits and adjust them to suit your needs.

**Comment by abhit011** [comment]
Yeah I will add little more than 10K . Does this BLOCK SIZE refers to one's object Node size or something else e.g in my case the MyObj is of size 156 bytes ? 

Do you have any blog or picture which depicts the memory layout of this Queue..  I am still little perplexed over this BLOCK SIZE and IMPLICT and EXPLICT calculations

**Comment by abhit011** [comment]
You mean 
```
MPSCQueueHandle *pHandleAx = NULL; 
pHandleAx = new MPSCQueueHandle(10000); 
```

**Comment by cameron314** [comment]
I meant

    new MPSCQueueHandle(10000, 0, 48)

**Comment by abhit011** [comment]
Trieds this `new MPSCQueueHandle(10000, 0, 48)`
In Consumer Thread its `retrivedNoOfBatches = this->MPSC_queueHandle_consumer->try_dequeue_bulk(temp,200);`

Lets say due to some reason the Consume thread is responding a little late, the Produce `try_enqueue `starts throwing Fail when ever the size_approx() is above 1000

**Comment by cameron314** [comment]
That would be due to the other internal structures needing to expand (even though enough free blocks are available). In your custom traits,try setting the `INITIAL_IMPLICIT_PRODUCER_HASH_SIZE` to 128, the `BLOCK_SIZE` to 128, 
and the `IMPLICIT_INITIAL_INDEX_SIZE` to 64 or even 128.

**Comment by abhit011** [comment]
**Assertion failed: prevVal + count <= BLOCK_SIZE,**

**Comment by abhit011** [comment]
struct MyTraits : public  moodycamel::ConcurrentQueueDefaultTraits
{
	static const size_t BLOCK_SIZE = 128;
	static const size_t INITIAL_IMPLICIT_PRODUCER_HASH_SIZE = 128;
	static const size_t IMPLICIT_INITIAL_INDEX_SIZE = 128;	
};

**Comment by cameron314** [comment]
Hmm. I'll look into this today.

**Comment by cameron314** [comment]
Should not be happening, obviously. The code looks correct. Can I see how you are dequeueing elements?

**Comment by abhit011** [comment]
```
while (!CThread::currentThread().isInterrupted()) {	
			if (m_BaseLayer != NULL){
				m_BaseLayer->postTheData(); 
			}
}

void postTheData(){
int retrivedNoOfBatches = 0;
static MsgObject queueDumpBatch[BATCH_DEQUEUE_NUMBER] = { 0x00 };
memset(queueDumpBatch, 0x00, sizeof(MsgObject) * BATCH_DEQUEUE_NUMBER); 
retrivedNoOfBatches=this->queueHandle_consumer->try_dequeue_bulk(queueDumpBatch,BATCH_DEQUEUE_NUMBER);
		if (!retrivedNoOfBatches)
			::Sleep(1);
     doSomething(queueDumpBatch);
}
```

**Comment by cameron314** [comment]
I've tried running some tests locally but I can't reproduce. Can you construct a self-contained example that produces this assertion?

**Comment by cameron314** [comment]
(Sorry for the delay, by the way.)
