### ISSUE TITLE
Speed benchmark

### ISSUE THREAD

**Issue by albertino80** [cameron314/concurrentqueue#130]
I did some tests to evaluate the efficiency of this lock-free queue.

I use vs2017 15.8.6 on Windows.

I compared `moodycamel :: ConcurrentQueue` against `std :: queue` + `std :: mutex`

Maybe I did something wrong, but I can not see benefits in terms of speed.

I attach the code I used.
[main.zip](https://github.com/cameron314/concurrentqueue/files/2476302/main.zip)

If possible, I would like to understand what I'm wrong.

Sample output:
```
thread 0 4033881 elems
thread 1 4055774 elems
thread 2 4011301 elems
thread 3 3899044 elems
total elems processed: 16000000
time: 2557
thread 0 3630750 elems
thread 1 4276339 elems
thread 2 4446451 elems
thread 3 3646460 elems
total elems processed: 16000000
time: 2442
```

Time is in Millisec, the first time is related to `moodycamel::ConcurrentQueue` the second is `std :: queue` + `std :: mutex`

**Comment by cameron314** [comment]
I think most of the time is spent in string manipulation, which makes the speed of the queue operations negligible.

Try using a different element type than `std::string`.

Also, the many-producers-to-few-consumers pattern is the worst case for the moodycamel::ConcurrentQueue; use a consumer token to accelerate dequeueing:

    moodycamel::ConsumerToken tok(q1);
    while(!stop){
        bool found = q1.try_dequeue(tok, item);

**Comment by albertino80** [comment]
it is true that the time is spent to manipulate `std :: string`, but it is also true that this happens with `moodycamel :: ConcurrentQueue` but also with `std :: queue + std :: mutex` so the comparison should remain valid.

If I add a `moodycamel :: ConsumerToken` and a `moodycamel :: ProducerToken` I actually reach:
time: 1339 (`moodycamel :: ConcurrentQueue`)
time: 2464 (`std :: queue + std :: mutex`)

80% performance gain!
