### ISSUE TITLE
Integrate with a package manager

### ISSUE THREAD

**Issue by HQarroum** [cameron314/concurrentqueue#131]
Hi,

First, I would like to say thanks for the awesome job you've been doing with `concurrentqueue`. I have created a [lock-free thread-pool implementation](https://github.com/HQarroum/thread-pool) using C++11 semantics, which is based on the moodycamel queue (the blocking queue implementation actually). Feedback would be tremendously appreciated !

I've read the license associated with your project, and decided to embed your two header files as part of the thread pool (confirm if that's not ok). However, this is not really ideal and wanted to have your input on whether it could be a good idea to publish the concurrent queue [releases](https://github.com/cameron314/concurrentqueue/releases) as part of a package manager such as Conan, Buckaroo, Hunter, etc.

The advantages I see would be :

 - Ability to seamlessly integrate your queue into any project using on the package managers above.
 - Ability to target a specific version.
 - No need to use sub-modules, or worse, hard copy the project.
 - Ability to track breaking changes made down the road to `concurrentqueue` using [semantic versioning](https://semver.org/).

Let me know what do you think.

Thanks!

**Comment by cameron314** [comment]
I tried to create a Conan package for another project at one point (based partly on the existing pull request), but it was extremely complex to produce a simple single-header package.

I've decided not to package the queue for now. If anyone wants to create third-party "unofficial" packages that's perfectly fine with me, as long as the license is respected and included.
