### ISSUE TITLE
Blocking-concurrentqueue:  Manually lock queue

### ISSUE THREAD

**Issue by liron-tiledmedia** [cameron314/concurrentqueue#134]
Is there a way to manually block the queue?

I'm asking this as I would like to empty the queue. However, I would like to prevent other threads to dequeue in the same time. Obviously I could do it externally, but I thought if the queue already blocks maybe I can use this to my advantage.

**Comment by cameron314** [comment]
No, there is not, sorry.

**Comment by liron-tiledmedia** [comment]
Wow, thanks for the blazing fast answer (you see what I did there) ;) and no need to be sorry, I should be the one to thank you for all the hard work you put in here :)

**Comment by cameron314** [comment]
Thanks for the nice words :-)
