### ISSUE TITLE
Help with try_dequeue

### ISSUE THREAD

**Issue by amno1** [cameron314/concurrentqueue#135]
I have a classical producer/consumer problem; I take pictures from camera in one thread and put them into a queue for analysis by another thread. The camera stream is coming from a Basler cam, and runs in it's own internal thread provided by API. 

I am enqueuing images into a BlockingReaderWriterQueue with try_enqueue method which seems to work fine. It is about max 14 fps from the camera model I use. On the other end my analysis thread is dequeuing images for analysis (most of them will be thrown away). For now it is just an empty method to dequeue images from the queue.

For the first, despite me setting max number of items in the queue the actual number of items is always bigger. I am using an atomic int as counter as well as checking size_approx () from the queue itself. They both show same. When I used max queue size of 25, the queue will grow up until it reaches size 31 and than it will stay there for the rest of the run. When I used max size of 10, the queue grew up to 15 and stayed there. When I used 5 as max depth, the queue grows up to 7 and than stays constantly there.

For my application it is important to process all images from the queue. The expected size is supposed to be at 0 most of the time. The application itself is running much faster than camera is taking images by design. The queue is just an extra buffer to provide security layer in case of analysis gets too slow because of OS doing something funky but mostly as help to divide processing and sorting trash images from real ones (I do some preprocessing and sort out some images before the main analysis functions runs). 

Here is some code:

```
atomic<int> fbdepth = 0;
const int maxfbdepth = 5;

BlockingReaderWriterQueue< cv::Mat > framebuffer ( maxfbdepth );     // input from camera

class OnGrabbedEvent : public CImageEventHandler { // baslers callback
public:
        virtual void OnImageGrabbed ( CInstantCamera& camera, const CGrabResultPtr& ptrGrabResult ) {

                    ( ... some stuff here ... )

                if ( framebuffer.try_enqueue ( img ) ) {
                        fbdepth++;
                }
        }
};
```

Meanwhile in some other thread .... :-)

```
void analyze () {

        while ( true ) {
                if ( fbdepth > 0 && framebuffer.try_dequeue ( img ) ) {
                        fbdepth--;

                        ( ... some stuff here ... )

                } else {
                        //if ( fbdepth < 1 )
                        this_thread::yield ();
                }
        }
}
```
I have scaled away all the unnecessary code, I can put it in if somebody is curious, it is nothing special nor secret, I just wanted to keep the queue logic clean for the purpose of this question.

What I see is that queue is always at max depth + some. I also guess that it never blocks since two cores on my cpu (an i7) are running at 100% all the time. It is expected since there are always items in the queue which means the queue will never block since it will never enter else part of if-else in the analyze() while loop.

By the way, I have also tested with depth queue 1. The max depth actually stayed at 1, but the queue was never empty so the analysis thread never yielded. The queue should go to sleep some time since I am just dequeuing images out of the queue without doing anything to them. It should be much faster than copying images from camera into ram from Baslers thread.

I guess I have missed something about how the blocking queue works, but I can't find what. I hope someone can direct me in the right direction, any help is appreciated.

**Comment by cameron314** [comment]
Before I answer, are you using the `BlockingReaderWriterQueue` or `BlockingConcurrentQueue`? Your code says the former but you're opened an issue in the project for the latter ;-)
The two queues are implemented very differently!

**Comment by cameron314** [comment]
I think this is relating to the `BlockingReaderWriterQueue`, so here you go:

1) The initial max number of elements is actually a lower bound (you're guaranteed space for *at least* that many elements). Internally, the queue is formed of a number of blocks. The number of elements in each block must be a power of two (for performance). Additionally, one of these elements is sacrificed in order to more easily distinguish between an empty and full block. Since your test sizes are all less than the maximum block size, a single block is allocated; this explains the sizes you are seeing (25 rounds up to 32-1, 10 rounds up to 16-1, 5 rounds up to 8-1, 1 rounds up to 2-1).

2) You're declaring a blocking queue, but not using it as a blocking queue (i.e. `wait_dequeue` is never called). This explains why it never blocks, but not why it never empties out.

3) If it's expected that there's always items in the queue, then when would it block? I'm not sure I understand. Why would there always be items in the queue if the production thread is slower than the consumption thread?

4) By far the most perplexing for me is why the queue is always full and never empty. Are you sure that `OnImageGrabbed` is being called less often than your other thread is calling `try_dequeue`? This can be checked by adding a counter for both and comparing after some time.

**Comment by amno1** [comment]
I am begging of pardon, my mistake. BlockingReaderWriterQueue :-). I wasn't looking carefully where I was posting.



Skickat från min Samsung Galaxy-smartphone.


-------- Originalmeddelande --------
Från: Cameron <notifications@github.com>
Datum: 2018-11-15 19:10 (GMT+01:00)
Till: cameron314/concurrentqueue <concurrentqueue@noreply.github.com>
Kopia: amno1 <arthur.miller@live.com>, Author <author@noreply.github.com>
Rubrik: Re: [cameron314/concurrentqueue] Help with try_dequeue (#135)


Before I answer, are you using the BlockingReaderWriterQueue or BlockingConcurrentQueue? Your code says the former but you're opened an issue in the project for the latter ;-)
The two queues are implemented very differently!

**Comment by amno1** [comment]
Ok. That explains at least some of the observed behaviour.

I am not at home and will not be until tomorrow so I can't post code or test things. I will test with two counters tomorrow.

For the point 4. I am quite sure. The camera is speced at 14 fps and there si memcpy from driver space to cv::Mat at enque, but on sequel side is no work done at all. I just deque and return.

I will play with the code more tomorrow, in front of all I will test with wait_deque.

For the point 3: no the expected number of items in the block is 0 most of the time. Producer is supposed to be much slower in this case, and I want consumer to block until an image is available. I am sorry if I have expressed myself wrong in the original post.


Skickat från min Samsung Galaxy-smartphone.


-------- Originalmeddelande --------
Från: Cameron <notifications@github.com>
Datum: 2018-11-15 19:19 (GMT+01:00)
Till: cameron314/concurrentqueue <concurrentqueue@noreply.github.com>
Kopia: amno1 <arthur.miller@live.com>, Author <author@noreply.github.com>
Rubrik: Re: [cameron314/concurrentqueue] Help with try_dequeue (#135)


I think this is relating to the BlockingReaderWriterQueue, so here you go:

  1.  The initial max number of elements is actually a lower bound (you're guaranteed space for at least that many elements). Internally, the queue is formed of a number of blocks. The number of elements in each block must be a power of two (for performance). Additionally, one of these elements is sacrificed in order to more easily distinguish between an empty and full block. Since your test sizes are all less than the maximum block size, a single block is allocated; this explains the sizes you are seeing (25 rounds up to 32-1, 10 rounds up to 16-1, 5 rounds up to 8-1, 1 rounds up to 2-1).

  2.  You're declaring a blocking queue, but not using it as a blocking queue (i.e. wait_dequeue is never called). This explains why it never blocks, but not why it never empties out.

  3.  If it's expected that there's always items in the queue, then when would it block? I'm not sure I understand. Why would there always be items in the queue if the production thread is slower than the consumption thread?

  4.  By far the most perplexing for me is why the queue is always full and never empty. Are you sure that OnImageGrabbed is being called less often than your other thread is calling try_dequeue? This can be checked by adding a counter for both and comparing after some time.

**Comment by amno1** [comment]
Hello again:

For the point 3. I was reflecting over the code snippet I posted and the fact that queue always contains elements, so I ment it can't yield. But the assumption for the correct application is that queue will most of the time contain no images (0 depth).

Anyway, I tested more, I switched to wait_dequeue() and results are better. Now I get expected results: 
```
void analyze () {
        int dequeueevent = 0;
        while ( true ) {
                framebuffer.wait_dequeue ( img );
                //if ( framebuffer.try_dequeue ( img ) ) 
                {
                        fbdepth--;
                        dequeueevent++;                        
                        DPT ( "Dequeueevent: %d\n", dequeueevent );
                }
        }
}
```
Super! As expected, queue depth stays at 0 most of the time.

> QEUE DEPTH: 0
> ATOM DEPTH: 0
> ONGRABEVENT: 1
> Dequeueevent: 1
> QEUE DEPTH: 0
> Dequeueevent: 2
> ATOM DEPTH: 0
> ONGRABEVENT: 2
> QEUE DEPTH: 0
> Dequeueevent: 3
> ATOM DEPTH: 0
> ONGRABEVENT: 3
> QEUE DEPTH: 0
> Dequeueevent: 4
> ATOM DEPTH: 0
> ONGRABEVENT: 4
> QEUE DEPTH: 0
> Dequeueevent: 5
> ATOM DEPTH: 0
> ONGRABEVENT: 5
> QEUE DEPTH: 0
> ATOM DEPTH: 0
> ONGRABEVENT: 6
> Dequeueevent: 6
> QEUE DEPTH: 0
> Dequeueevent: 7
> ATOM DEPTH: 0
> ONGRABEVENT: 7
> QEUE DEPTH: 0
> Dequeueevent: 8
> ATOM DEPTH: 0
> ONGRABEVENT: 8
> QEUE DEPTH: 0
> Dequeueevent: 9
> ATOM DEPTH: 0
> ONGRABEVENT: 9
> QEUE DEPTH: 0
> ATOM DEPTH: 0
> ONGRABEVENT: 10
> Dequeueevent: 10
> QEUE DEPTH: 0
> Dequeueevent: 11
> ATOM DEPTH: 0
> ONGRABEVENT: 11
> QEUE DEPTH: 0
> ATOM DEPTH: 0
> ONGRABEVENT: 12
> Dequeueevent: 12
> QEUE DEPTH: 0
> Dequeueevent: 13
> ATOM DEPTH: 0
> ONGRABEVENT: 13
> QEUE DEPTH: 0
> Dequeueevent: 14
> ATOM DEPTH: 0
> ONGRABEVENT: 14
> QEUE DEPTH: 0
> ATOM DEPTH: 0
> ONGRABEVENT: 15
> Dequeueevent: 15
> QEUE DEPTH: 0
> Dequeueevent: 16
> ATOM DEPTH: 0
> ONGRABEVENT: 16
> QEUE DEPTH: 0
> ATOM DEPTH: 0
> ONGRABEVENT: 17
> Dequeueevent: 17
> QEUE DEPTH: 0
> Dequeueevent: 18
> ATOM DEPTH: 0
> ONGRABEVENT: 18
> QEUE DEPTH: 0
> Dequeueevent: 19
> ATOM DEPTH: 0
> ONGRABEVENT: 19
> QEUE DEPTH: 0
> Dequeueevent: 20
> ATOM DEPTH: 0
> ONGRABEVENT: 20
> QEUE DEPTH: 0
> Dequeueevent: 21
> ATOM DEPTH: 0
> ONGRABEVENT: 21
> QEUE DEPTH: 0
> ATOM DEPTH: 0
> ONGRABEVENT: 22
> Dequeueevent: 22
> QEUE DEPTH: 0
> Dequeueevent: 23
> ATOM DEPTH: 0
> ONGRABEVENT: 23
> QEUE DEPTH: 0
> ATOM DEPTH: 0
> ONGRABEVENT: 24
> Dequeueevent: 24
> QEUE DEPTH: 0
> Dequeueevent: 25
> ATOM DEPTH: 0
> ONGRABEVENT: 25
> QEUE DEPTH: 0
> Dequeueevent: 26
> ATOM DEPTH: 0
> ONGRABEVENT: 26
> QEUE DEPTH: 0
> Dequeueevent: 27
> ATOM DEPTH: 0
> ONGRABEVENT: 27
> QEUE DEPTH: 0
> Dequeueevent: 28
> ATOM DEPTH: 0
> ONGRABEVENT: 28
> QEUE DEPTH: 0
> ATOM DEPTH: 0
> ONGRABEVENT: 29
> Dequeueevent: 29
> QEUE DEPTH: 0
> ATOM DEPTH: 0
> ONGRABEVENT: 30
> Dequeueevent: 30
> QEUE DEPTH: 0
> ATOM DEPTH: 0
> ONGRABEVENT: 31
> Dequeueevent: 31
> QEUE DEPTH: 0
> Dequeueevent: 32
> ATOM DEPTH: 0
> ONGRABEVENT: 32
> QEUE DEPTH: 0
> Dequeueevent: 33
> ATOM DEPTH: 0
> ONGRABEVENT: 33
> QEUE DEPTH: 0
> ATOM DEPTH: 0
> ONGRABEVENT: 34
> Dequeueevent: 34
> QEUE DEPTH: 0
> ATOM DEPTH: 0
> ONGRABEVENT: 35
> Dequeueevent: 35
> QEUE DEPTH: 0
> Dequeueevent: 36
> ATOM DEPTH: 0
> ONGRABEVENT: 36
> QEUE DEPTH: 0
> Dequeueevent: 37
> ATOM DEPTH: 0
> ONGRABEVENT: 37
> QEUE DEPTH: 0
> Dequeueevent: 38
> ATOM DEPTH: 0
> ONGRABEVENT: 38
> QEUE DEPTH: 0
> Dequeueevent: 39

Interesting to see is event 12/13. For some reason there is no grabevent 13 but I still got a dequeue event.

Anyway the only problem left for me to solve is that cpu  jumps to 100% on two cores and stays there all the time. I guess one is camera thread and another one is my analysis thread. I even tried manually to put analysis thread to sleep if queue depth is 0, but it does not seem to do anything. It should run approximately 12 ~ 15 times per second at max. Since it does no work at all (approximately just a "free()" on a buffer pointer somewhere in cv::Mat ), it should not hog entire core 100% of time, but I might be wrong. I would prefer to see some more spikes on one core (analysis thread). Camera thread is not much to do about, it is controlled internally by provided API, unless I wish to switch and do it all manually. But I would prefer to see bit less CPU usage by a thread that just empties a queue.

I have been looking into wait_dequeue() and LightweightSemaphore, and I wonder if waitWithPartialSpinning() has something to do with it called from sema->wait(), class LightweightSemaphore? Or is it just me doing fishy stuff :-).

**Comment by cameron314** [comment]
Good! :-)

In your output it seems the ONGRABEVENT output can be printed after the corresponding Dequeueevent is output, indicating there's either some kind of race in the output stream, or that the ONGRABEVENT message is being printed after the event is already enqueued.

The internal lightweight semaphore does an initial spin-wait to lower the latency in high-throughput situations where another element is just around the corner, and it would not be worth blocking the thread at the OS level. In your case, this adds a little CPU overhead without any benefit, since your throughput is so low / spaced out. But, it should not contribute significantly to your thread's CPU usage.

It sounds like you can't find why your threads are at 100% CPU. Have you tried repeatedly breaking in the debugger to see what the threads are usually doing? What platform are you on?

**Comment by amno1** [comment]
Thank you for kind and fast answer. I will play with it a bit more and post result later on. I am working on another part of application atm, so I just want to finnish that before I go back to my threads.
