### ISSUE TITLE
Does this queue support void * ?

### ISSUE THREAD

**Issue by new-commer** [cameron314/concurrentqueue#138]
I want to use it like this 
```
moodycamel::BlockingConcurrentQueue<void *> mq;
char * buffer = new char[128];
mq.try_enqueue(buffer);

char * out = nullptr;
mq.try_dequeue(out);
```
And i ran into compile error like below 
```
concurrentqueue.h:1952:54: error: invalid conversion from ‘std::remove_reference<void*&>::type {aka void*}’ to ‘char*’ [-fpermissive]
      if (!MOODYCAMEL_NOEXCEPT_ASSIGN(T, T&&, element = std::move(el))) {
                                              ~~~~~~~~^~~~~~~~~~~~~~~
concurrentqueue.h:189:68: note: in definition of macro ‘MOODYCAMEL_NOEXCEPT_ASSIGN’
```

Is this queue do not support `void *` ?

**Comment by cameron314** [comment]
The queue supports `void*`, but C++ doesn't allow implicit conversion from `void*` to `char*`, which is what you're effectively trying to do with `try_dequeue(out)`.

This is the same error you'll get from the following code:

    void* p = ...;
    char* x = p;  // invalid conversion from 'void*' to 'char*'

To fix this, either change the queue to use `char*` elements, or dequeue into a `void*` variable then cast explicitly to `char*`.

**Comment by new-commer** [comment]
Got it . Thank you very much
