### ISSUE TITLE
Possible Race Condition between ~ProducerToken() and ~ConcurrentQueue?

### ISSUE THREAD

**Issue by graphicsMan** [cameron314/concurrentqueue#140]
I might be missing something, but it seems that there could be a race between ~ProducerToken() and ~ConcurrentQueue?  I'm thinking of using ProducerToken as a thread-local,  but I'm worried about lifetimes.  I haven't fully verified a bad race, but it looks like the checks on `token` for nullptr could both pass, and then one could destroy the memory while the other modifies `invalid`?

**Comment by cameron314** [comment]
It's the programmer's responsibility to ensure that the `ProducerToken` object is destroyed before the `ConcurrentQueue` object is destroyed.

**Comment by cameron314** [comment]
Actually, it seems that the `ConcurrentQueue` supports `ProducerToken`s that outlive it. In this case, it is the programmer's responsibility to ensure that no tokens are being created or destroyed while the queue is being destroyed.

**Comment by graphicsMan** [comment]
When I saw that it was supported to destroy after the queue, it wasn't immediately obvious whether it should be safe to do so concurrently.  Thanks.
