### ISSUE TITLE
Dose this queue support max count limition

### ISSUE THREAD

**Issue by new-commer** [cameron314/concurrentqueue#147]
Can i pre-set the capacity of queue ? When the item count reach the max number, it block util dequeue  happened or return with error code ?

**Comment by cameron314** [comment]
Oops, sorry I didn't respond until now.

The queue design uses multiple independent sub-queues internally (one for each producer), so the total capacity cannot be limited in a precise way. If you need this functionality I would suggest using a concurrent ring buffer instead.

Having said that, there is a constructor overload that allows a number of elements to be pre-allocated up front; this combined with the initial hash sizes in the traits can be used with `try_enqueue` to prevent the queue from allocating on enqueue, but the total capacity is not fixed (it depends on how many and which threads are enqueueing elements). There's also no way to wait until room becomes available.

There is also the `MAX_SUBQUEUE_SIZE` trait that can be used to limit the number of elements per sub-queue, which may be sufficient if you have only a single producer.
