### ISSUE TITLE
How can the queue be cleared?

### ISSUE THREAD

**Issue by deiflou** [cameron314/concurrentqueue#150]
Hello.
At some point in the code I want to clear the queue for potential reuse. I'm using:
``` cpp
void clear_tasks_()
{
    std::vector<task_type> tasks(10);
    while(task_queue_.try_dequeue_bulk(consumer_token_, tasks.begin(), 10));
}
```
Is there any other (simpler, more correct) way to clear the queue or discard the elements currently enqueued?
Thanks.

**Comment by cameron314** [comment]
There is no simpler way, I'm afraid. Adding a `clear()` method would require coordination between all producers, which can't be done efficiently with the current design; so, it's up to the user to do such coordination.

Your loop is efficient, and correct assuming  that no more tasks are being added in parallel, and that the thread it's running on has been synchronized with all the producer threads after their last enqueue operation (e.g. via a memory barrier or mutex).

**Comment by deiflou** [comment]
Ok, thanks.
