### ISSUE TITLE
How can I declare a group of concurrentqueue?

### ISSUE THREAD

**Issue by sylvia531** [cameron314/concurrentqueue#155]
I would like to declare a group of Concurrent queue either use malloc or with some std library like vector. I use the following way: 

moodycamel::ConcurrentQueue<ioRequest*>* lf_client_finish_pool;
lf_client_finish_pool= new moodycamel::ConcurrentQueue<ioRequest*>[num_client];
for(int i =0; i<num_client; i++){
  moodycamel::ConcurrentQueue<ioRequest*> tmp_pool;
  lf_client_finish_pool[i] =  tmp_pool;
}

However, I meet the following error:
client.cpp:53:28: error: use of deleted function ‘moodycamel::ConcurrentQueue<T, Traits>& moodycamel::ConcurrentQueue<T, Traits>::operator=(const moodycamel::ConcurrentQueue<T, Traits>&) [with T = ioRequest*; Traits = moodycamel::ConcurrentQueueDefaultTraits]’
   lf_client_finish_pool[i] = tmp_pool;
                            ^
In file included from rdmaHeader.h:66:0,
                 from client.h:4,
                 from client.cpp:1:
concurrentqueue.h:819:19: note: declared here
  ConcurrentQueue& operator=(ConcurrentQueue const&) MOODYCAMEL_DELETE_FUNCTION;

I wonder whether there is a way to realize the function I want using this concurrentqueue?

Thanks

**Comment by cameron314** [comment]
Your loop is attempting to copy `tmp_pool` into each array element, but ConcurrentQueue objects cannot be copied, only moved.

The constructor of each ConcurrentQueue object is already implicitly called during the invocation of `new[]` -- your code is fine without the loop.
