### ISSUE TITLE
Incorporating Boost::pool_allocator

### ISSUE THREAD

**Issue by psgbhavani** [cameron314/concurrentqueue#156]
We are currently trying to use a concurrentQueue that holds the type vector<std::complex<short>, boost::pool_allocator<std::complex<short>>. We noticed when we traced back our build errors that the error is being caused by concurrentqueue.h. It says there is no operator found which takes a right-hand operand of type 'vector<std::complex<short>, boost::pool_allocator<std::complex<short>>'. How do you suggest working around this?

**Comment by cameron314** [comment]
Please copy the full error?

**Comment by psgbhavani** [comment]
This is the code that corresponds to what we are doing:
`moodycamel::ConcurrentQueue< std::vector< std::complex<short>, boost::pool_allocator<std::complex<short>>>> processing_queue;`

`std::vector< std::complex<short>, boost::pool_allocator<std::complex<short>>>buff(samps_per_buff);
moodycamel::ProducerToken ptok(processing_queue);`

`processing_queue.enqueue(ptok, std::move(buff));`

The error is the following: 

![image](https://user-images.githubusercontent.com/33610242/58135537-c2f0df80-7bdf-11e9-8cfa-e28baff3a584.png)

**Comment by cameron314** [comment]
That should work. What version of VS?

**Comment by psgbhavani** [comment]
Visual Studio 2017

**Comment by psgbhavani** [comment]
Is there any other details I can give you that might make figuring out/understanding the problem easier?

**Comment by aishwaryabh** [comment]
I have the same issue. I've been trying to incorporate boost::pool_allocator into a concurrent queue (also by defining a vector that takes in type boost::pool_allocator into the Allocator template parameter). Any suggestions on how to approach this problem? Thanks in advance!

**Comment by cameron314** [comment]
Sorry I haven't had time to investigate. It looks like `std::vector` with a `boost::pool_allocator` is not movable, which is weird (I see no reason why not).

**Comment by cameron314** [comment]
Cannot reproduce (with VS2015). Are you sure all your vectors are of the same type (i.e. `std::vector<std::complex<short>, boost::pool_allocator<std::complex<short>>>`)?

**Comment by cameron314** [comment]
Does the following code compile for you?

    std::vector<std::complex<short>, boost::pool_allocator<std::complex<short>>> v { { 1, 0 } }, u;
    u = std::move(v);

**Comment by aishwaryabh** [comment]
Thanks for the prompt reply! Yes those lines of code compile! I however believe that the issue has to do with the code in concurrent_queue.h in all of the lines that involve std::move on the vector element. For example this line of code does not compile:

`if (!MOODYCAMEL_NOEXCEPT_ASSIGN(T, T&&, element = std::move(el))) {`

I tried to modify concurrent_queue.h by changing the std::move() to boost::move as I thought that might have been the issue, but I still keep getting that same error. Any suggestions as to how to approach this problem?

**Comment by cameron314** [comment]
Sorry for the long response time.

I still can't reproduce. The following code compiles correctly with VS2019 and Boost 1.72:

	ConcurrentQueue<std::vector<std::complex<short>, boost::pool_allocator<std::complex<short>>>, MallocTrackingTraits> q;
	ProducerToken ptok(q);
	std::vector<std::complex<short>, boost::pool_allocator<std::complex<short>>> x;
	q.enqueue(ptok, std::move(x));
	q.try_dequeue(x);

Even if I force the definition of `MOODYCAMEL_NOEXCEPT_ASSIGN` to the VS2017 equivalent it still compiles correctly. I suggest upgrading to Visual Studio 2019 if possible.

**Comment by cameron314** [comment]
Feel free to reopen as necessary.
