### ISSUE TITLE
ConcurrentQueue loses sent messages.

### ISSUE THREAD

**Issue by max0x7ba** [cameron314/concurrentqueue#157]
There are benchmarks for 11 different queues in https://github.com/max0x7ba/atomic_queue

The throughput benchmark also checks that all sent messages are received exactly once (no missed messages, no duplicates). All queues pass the test, apart from  `moodycamel::ConcurrentQueue` which fails this test sporadically.

It appears that `moodycamel::ConcurrentQueue` loses sent messages, which strongly suggests there is a race condition in `moodycamel::ConcurrentQueue`.

Example output of the benchmark:

```
   boost::lockfree::spsc_queue,1:  61,982,530 msg/sec
        boost::lockfree::queue,1:   8,988,512 msg/sec
        boost::lockfree::queue,2:   7,889,834 msg/sec
        boost::lockfree::queue,3:   7,273,366 msg/sec
              pthread_spinlock,1:  23,359,727 msg/sec
              pthread_spinlock,2:  14,271,047 msg/sec
              pthread_spinlock,3:  11,131,887 msg/sec
   moodycamel::ConcurrentQueue,1:  16,280,639 msg/sec
moodycamel::ConcurrentQueue: wrong checksum error: producers: 2, expected_sum: 250,000,500,000, diff: -1.
   moodycamel::ConcurrentQueue,2:  11,665,341 msg/sec
moodycamel::ConcurrentQueue: wrong checksum error: producers: 3, expected_sum: 166,666,833,333, diff: -6.
moodycamel::ConcurrentQueue: wrong checksum error: producers: 3, expected_sum: 166,666,833,333, diff: -1.
   moodycamel::ConcurrentQueue,3:  14,562,560 msg/sec
               tbb::spin_mutex,1:  59,073,877 msg/sec
               tbb::spin_mutex,2:  36,448,238 msg/sec
               tbb::spin_mutex,3:  33,031,061 msg/sec
   tbb::speculative_spin_mutex,1:  49,906,590 msg/sec
   tbb::speculative_spin_mutex,2:  35,294,316 msg/sec
   tbb::speculative_spin_mutex,3:  30,825,597 msg/sec
 tbb::concurrent_bounded_queue,1:  14,528,864 msg/sec
 tbb::concurrent_bounded_queue,2:  15,607,995 msg/sec
 tbb::concurrent_bounded_queue,3:  12,662,292 msg/sec
                   AtomicQueue,1:  19,112,157 msg/sec
                   AtomicQueue,2:  12,854,121 msg/sec
                   AtomicQueue,3:  11,311,835 msg/sec
           BlockingAtomicQueue,1: 114,722,154 msg/sec
           BlockingAtomicQueue,2:  36,538,892 msg/sec
           BlockingAtomicQueue,3:  36,193,781 msg/sec
                  AtomicQueue2,1:  18,602,246 msg/sec
                  AtomicQueue2,2:  12,273,033 msg/sec
                  AtomicQueue2,3:  11,365,921 msg/sec
          BlockingAtomicQueue2,1:  44,435,338 msg/sec
          BlockingAtomicQueue2,2:  32,550,395 msg/sec
          BlockingAtomicQueue2,3:  35,700,057 msg/sec
```

I can provide more details if necessary.

**Comment by cameron314** [comment]
`moodycamel::ConcurrentQueue` does not provide a total ordering of all elements -- elements from a given producer thread are guaranteed to come out in the same order, but that doesn't mean elements from another producer won't be dequeued first.

Your benchmark assumes that as soon as the stop value is seen, all other values have been dequeued, but this is not necessarily true for my queue -- after the stop value (enqueued by the last producer) is seen, values from other producers may still be present in the queue.

You can fix this by adding the following loop after joining all threads in your `benchmark_throughput` function (using `long long` because I'm on MSVC):

    for (long long i = total_sum; i != (N + 1) / 2. * N * producer_count; ++i)
		total_sum += queue.pop();

**Comment by max0x7ba** [comment]
> Your benchmark assumes that as soon as the stop value is seen, all other values have been dequeued, but this is not necessarily true for my queue -- after the stop value (enqueued by the last producer) is seen, values from other producers may still be present in the queue.

All producers post element sequence `[N, ..., 1, N+1]`. Although messages from different producers may get reordered (which also applies to other queues in the test), the very last element in the queue is `N+1` and no elements can possibly follow. Because, as you mention, _elements from a given producer thread are guaranteed to come out in the same order_, and sequences from all producers end with `N+1` element.

Each consumer stops upon receiving its own `N+1` element, so that when that last `N+1` element gets dequeued by the last consumer there mustn't be any elements left in the queue unconsumed.

I do not to see how `moodycamel::ConcurrentQueue` can possibly dequeue the last `N+1` element and still contain more elements, that would violate the one producer FIFO guarantee. Your explanation doesn't actually explain the observed phenomena.

**Comment by max0x7ba** [comment]
> All producers post element sequence `[N, ..., 1, N+1]`. Although messages from different producers may get reordered (which also applies to other queues in the test), the very last element in the queue is `N+1` and no elements can possibly follow. Because, as you mention, elements from a given producer thread are guaranteed to come out in the same order, and sequences from all producers end with `N+1` element.

Actually this was not the case. It was the last producer posting all the `N + 1` elements.

I changed the benchmark to work as I described above and now `moodycamel::ConcurrentQueue` passes the test. Thanks for your explanation.

**Comment by cameron314** [comment]
Ah, that explains it :-)
