### ISSUE TITLE
Compilation on MSVS 2015 (CTP5) fails

### ISSUE THREAD

**Issue by mintyc** [cameron314/concurrentqueue#16]
Just a heads up as this is pre-release software ...

Building fails from converted MSVS 2012 solution - all configurations

unittests builds and passes OK

however rest of solution not so happy ...

Warning at start of benchmarks build (assumed benign):
>'Unknown compiler version - please run the configure tests and report the results'

Errors:
1) benchmarks - boost:lockfree problem
>u:\dev\concurrentqueue\benchmarks\boost/lockfree/queue.hpp(109): error C2280: 'std::atomic<boost::lockfree::detail::tagged_ptr<T>>::atomic(void) noexcept': attempting to reference a deleted function

(also tried with latest boost develop branch implementation of queue.hpp with same error)

2) fuzztests
>..\..\tests\fuzztests\fuzztests.cpp(676): error C3066: there are multiple ways that an object of this type can be called with these arguments

Microsoft's `<xxatomic>` has 2 overloads of 
template<class _Ty>
	struct atomic<_Ty *>
{
	operator _Ty *() const volatile _NOEXCEPT
	operator _Ty *() const _NOEXCEPT

and it can't choose between them (I didn't even realise I could differentiate const functions on volatile)

3) Also several 'shadowed variable' warnings to ignore

**Comment by cameron314** [comment]
Thanks for opening this issue! Hrumph, that's annoying. Not much I can do about boost not compiling, though I suppose I could patch my local version. I'll fix all these when I have a moment.

**Comment by cameron314** [comment]
So I finally got around to creating a VS 2015 (Update 2) solution. It now compiles fine without any changes. The boost version used in the benchmarks had been updated to the latest (1.60) since this issue was opened, though, which probably has something to do with it :-)
