### ISSUE TITLE
Comment out MOODYCAMEL_EXCEPTIONS_ENABLED

### ISSUE THREAD

**Issue by portsip** [cameron314/concurrentqueue#162]
I'm failed to compile the blockingqueue with my project in VS2017, after I comment out the #define MOODYCAMEL_EXCEPTIONS_ENABLED then successfully compiled, my question is: does there has any potential problems if comment out that line(#define MOODYCAMEL_EXCEPTIONS_ENABLED  ) ?

<I commented out the **MOODYCAMEL_EXCEPTIONS_ENABLED**  in below code block> 

```
// Exceptions
#ifndef MOODYCAMEL_EXCEPTIONS_ENABLED
#if (defined(_MSC_VER) && defined(_CPPUNWIND)) || (defined(__GNUC__) && defined(__EXCEPTIONS)) || (!defined(_MSC_VER) && !defined(__GNUC__))
//#define MOODYCAMEL_EXCEPTIONS_ENABLED  
#endif
```

**Comment by cameron314** [comment]
You can safely undefine it if you're sure that none of the types you pass into the queue can throw exceptions.

However, it should compile as-is without issue. What error are you getting?

**Comment by portsip** [comment]
@cameron314 
Please find attached the screenshot.

<img width="966" alt="error1" src="https://user-images.githubusercontent.com/11405486/62179759-2fc2eb80-b380-11e9-81ce-9461bd94dca2.png">
<img width="981" alt="error2" src="https://user-images.githubusercontent.com/11405486/62179760-2fc2eb80-b380-11e9-84db-45878b1ac771.png">
<img width="964" alt="error3" src="https://user-images.githubusercontent.com/11405486/62179761-305b8200-b380-11e9-9327-2238eb3dded0.png">

**Comment by cameron314** [comment]
Can you copy the details from the Output Window following a build? I'd like to know what the ambiguity is, in case it's something I can fix on my end.

**Comment by portsip** [comment]
There is is below, the 3rd library PoolBase.hxx you can find at: https://github.com/resiprocate/resiprocate/blob/master/rutil/PoolBase.hxx

1>d:\stacks\portpbx\src\common\include\concurrentqueue.h(2772): error C2668: 'operator new': ambiguous call to overloaded function
1>D:\Stacks\portpbx\resip\include\rutil/PoolBase.hxx(19): note: could be 'void *operator new(size_t,resip::PoolBase *)'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.16.27023\include\vcruntime_new.h(184): note: or       'void *operator new(size_t,void *) noexcept'
1>d:\stacks\portpbx\src\common\include\concurrentqueue.h(2772): note: while trying to match the argument list '(unsigned __int64, nullptr)'
1>d:\stacks\portpbx\src\common\include\concurrentqueue.h(1481): note: see reference to function template instantiation 'bool moodycamel::ConcurrentQueue<T,Traits>::ImplicitProducer::enqueue<moodycamel::ConcurrentQueue<T,Traits>::CanAlloc,const T&>(U)' being compiled
1>        with
1>        [
1>            T=PortPBX::CDRManager::WriteDBObject,
1>            Traits=PortPBX::CDRManager::Traits,
1>            U=const PortPBX::CDRManager::WriteDBObject &
1>        ]
1>d:\stacks\portpbx\src\common\include\concurrentqueue.h(1481): note: see reference to function template instantiation 'bool moodycamel::ConcurrentQueue<T,Traits>::ImplicitProducer::enqueue<moodycamel::ConcurrentQueue<T,Traits>::CanAlloc,const T&>(U)' being compiled
1>        with
1>        [
1>            T=PortPBX::CDRManager::WriteDBObject,
1>            Traits=PortPBX::CDRManager::Traits,
1>            U=const PortPBX::CDRManager::WriteDBObject &
1>        ]
1>d:\stacks\portpbx\src\common\include\concurrentqueue.h(1074): note: see reference to function template instantiation 'bool moodycamel::ConcurrentQueue<T,Traits>::inner_enqueue<moodycamel::ConcurrentQueue<T,Traits>::CanAlloc,const T&>(U)' being compiled
1>        with
1>        [
1>            T=PortPBX::CDRManager::WriteDBObject,
1>            Traits=PortPBX::CDRManager::Traits,
1>            U=const PortPBX::CDRManager::WriteDBObject &
1>        ]
1>d:\stacks\portpbx\src\common\include\concurrentqueue.h(1074): note: see reference to function template instantiation 'bool moodycamel::ConcurrentQueue<T,Traits>::inner_enqueue<moodycamel::ConcurrentQueue<T,Traits>::CanAlloc,const T&>(U)' being compiled
1>        with
1>        [
1>            T=PortPBX::CDRManager::WriteDBObject,
1>            Traits=PortPBX::CDRManager::Traits,
1>            U=const PortPBX::CDRManager::WriteDBObject &
1>        ]
1>d:\stacks\portpbx\src\common\include\concurrentqueue.h(1071): note: while compiling class template member function 'bool moodycamel::ConcurrentQueue<T,Traits>::enqueue(const T &)'
1>        with
1>        [
1>            T=PortPBX::CDRManager::WriteDBObject,
1>            Traits=PortPBX::CDRManager::Traits
1>        ]
1>d:\stacks\portpbx\src\common\include\blockingconcurrentqueue.h(532): note: see reference to function template instantiation 'bool moodycamel::ConcurrentQueue<T,Traits>::enqueue(const T &)' being compiled
1>        with
1>        [
1>            T=PortPBX::CDRManager::WriteDBObject,
1>            Traits=PortPBX::CDRManager::Traits
1>        ]
1>d:\stacks\portpbx\src\common\include\blockingconcurrentqueue.h(433): note: see reference to class template instantiation 'moodycamel::ConcurrentQueue<T,Traits>' being compiled
1>        with
1>        [
1>            T=PortPBX::CDRManager::WriteDBObject,
1>            Traits=PortPBX::CDRManager::Traits
1>        ]
1>d:\stacks\portpbx\src\common\include\concurrentqueue.h(2772): error C2056: illegal expression
1>d:\stacks\portpbx\src\common\include\concurrentqueue.h(2793): error C2668: 'operator new': ambiguous call to overloaded function
1>D:\Stacks\portpbx\resip\include\rutil/PoolBase.hxx(19): note: could be 'void *operator new(size_t,resip::PoolBase *)'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.16.27023\include\vcruntime_new.h(184): note: or       'void *operator new(size_t,void *) noexcept'
1>d:\stacks\portpbx\src\common\include\concurrentqueue.h(2793): note: while trying to match the argument list '(unsigned __int64, nullptr)'
1>d:\stacks\portpbx\src\common\include\concurrentqueue.h(2793): error C2056: illegal expression

**Comment by cameron314** [comment]
Well, I can easily reproduce this with VS2019. It looks like a compiler bug with `noexcept`.

**Comment by cameron314** [comment]
Fixed :-)
