### ISSUE TITLE
do you have front() and back() methods , just like std::queue?

### ISSUE THREAD

**Issue by qian0702** [cameron314/concurrentqueue#164]
do you have front() and back() methods , just like std::queue?

**Comment by cameron314** [comment]
No. There's no way to make such methods thread-safe.

**Comment by qian0702** [comment]
Ok , thanks!

**Comment by qian0702** [comment]
I want to establish a total ordering with your queue by creating producer token and consumer token, the a total ordering is good, but my program still produce coredump after program runs for a while. 

The coredump log is: test: ../src/concurrentqueue.h:1517: bool moodycamel::ConcurrentQueue<T, Traits>::Block::set_empty(moodycamel::ConcurrentQueue<T, Traits>::index_t) [with moodycamel::ConcurrentQueue<T, Traits>::InnerQueueContext context = (moodycamel::ConcurrentQueue<int, moodycamel::ConcurrentQueueDefaultTraits>::InnerQueueContext)1; T = int; Traits = moodycamel::ConcurrentQueueDefaultTraits; moodycamel::ConcurrentQueue<T, Traits>::index_t = long unsigned int]: Assertion `!emptyFlags[BLOCK_SIZE - 1 - static_cast<size_t>(i & static_cast<index_t>(BLOCK_SIZE - 1))].load(std::memory_order_relaxed)' failed.
Aborted (core dumped)

My program is:
#include <iostream>
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <thread>
#include <chrono>
#include "concurrentqueue.h"
#include <queue>
using namespace std;
using namespace moodycamel;


moodycamel::ConcurrentQueue<int> Q;
moodycamel::ProducerToken ptok(Q);
moodycamel::ConsumerToken tok(Q);
void func000() {

    chrono::microseconds dura(1000);
    while(1) {
        for(int i = 0; i < 50; i++) {
            if(!Q.enqueue(ptok, i)) {
                cout << "func000 i = " <<i << "enqueue failed...!"<<endl;
            }else
                cout <<i<<endl;
        }
        this_thread::sleep_for(dura);
    }
}
//
void func00() {
    chrono::microseconds dura(1000);
    while(1) {
        for(int i = 50; i < 100; i++) {
            if(!Q.enqueue(ptok, i)) {
                cout << "func00 i = " <<i << "enqueue failed...!"<<endl;
            } else
            cout <<i<<endl;
        }
        this_thread::sleep_for(dura);
    }
}

void func0() {
    chrono::microseconds dura(1000);
    while(1) {
        for(int i = 100; i < 150; i++) {
            if(!Q.enqueue(ptok,i)) {
                cout << "func0 i = " <<i << "enqueue failed...!"<<endl;
            }
            else
            	cout <<i<<endl;
        }
        this_thread::sleep_for(dura);
    }
}

Do you known the reason?!
void func1() {
    chrono::microseconds dura(1000);
    while(1) {
        int num;
        if(!Q.try_dequeue(tok, num)) {
            this_thread::sleep_for(dura);
            continue;
        }

        else
        {
            cout<< "func1 num = " << num<< endl;
        }
    }
}

int main ()
{
    thread th00(func000);
    thread th0(func00);
    thread th1(func0);
    thread th2(func1);
    th00.join();
    th0.join();
    th1.join();
    th2.join();
    cout << "size_approx = " <<Q.size_approx() <<endl;
    return 0;
}

**Comment by qian0702** [comment]
I want to establish a total ordering with your queue by creating producer token and consumer token, the a total ordering is good, but my program still produce coredump after program runs for a while.

The coredump log is: 
test: ../src/concurrentqueue.h:1517: bool moodycamel::ConcurrentQueue<T, Traits>::Block::set_empty(moodycamel::ConcurrentQueue<T, Traits>::index_t) [with moodycamel::ConcurrentQueue<T, Traits>::InnerQueueContext context = (moodycamel::ConcurrentQueue<int, moodycamel::ConcurrentQueueDefaultTraits>::InnerQueueContext)1; T = int; Traits = moodycamel::ConcurrentQueueDefaultTraits; moodycamel::ConcurrentQueue<T, Traits>::index_t = long unsigned int]: Assertion `!emptyFlags[BLOCK_SIZE - 1 - static_cast<size_t>(i & static_cast<index_t>(BLOCK_SIZE - 1))].load(std::memory_order_relaxed)' failed.
Aborted (core dumped)

My program is:

#include <iostream>
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <thread>
#include <chrono>
#include "concurrentqueue.h"
#include <queue>
using namespace std;
using namespace moodycamel;


moodycamel::ConcurrentQueue<int> Q;
moodycamel::ProducerToken ptok(Q);
moodycamel::ConsumerToken tok(Q);
void func000() {

    chrono::microseconds dura(1000);
    while(1) {
        for(int i = 0; i < 50; i++) {
            if(!Q.enqueue(ptok, i)) {
                cout << "func000 i = " <<i << "enqueue failed...!"<<endl;
            }else
                cout <<i<<endl;
        }
        this_thread::sleep_for(dura);
    }
}
//
void func00() {
    chrono::microseconds dura(1000);
    while(1) {
        for(int i = 50; i < 100; i++) {
            if(!Q.enqueue(ptok, i)) {
                cout << "func00 i = " <<i << "enqueue failed...!"<<endl;
            } else
            cout <<i<<endl;
        }
        this_thread::sleep_for(dura);
    }
}

void func0() {
    chrono::microseconds dura(1000);
    while(1) {
        for(int i = 100; i < 150; i++) {
            if(!Q.enqueue(ptok,i)) {
                cout << "func0 i = " <<i << "enqueue failed...!"<<endl;
            }
            else
            	cout <<i<<endl;
        }
        this_thread::sleep_for(dura);
    }
}

void func1() {
    chrono::microseconds dura(1000);
    while(1) {
        int num;
        if(!Q.try_dequeue(tok, num)) {
            this_thread::sleep_for(dura);
            continue;
        }

        else
        {
            cout<< "func1 num = " << num<< endl;
        }
    }
}

int main ()
{
    thread th00(func000);
    thread th0(func00);
    thread th1(func0);
    thread th2(func1);
    th00.join();
    th0.join();
    th1.join();
    th2.join();
    cout << "size_approx = " <<Q.size_approx() <<endl;
    return 0;
}

**Comment by qian0702** [comment]
#include 
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include 
#include 
#include "concurrentqueue.h"
#include 
using namespace std;
using namespace moodycamel;
moodycamel::ConcurrentQueue Q;
moodycamel::ProducerToken ptok(Q);
moodycamel::ConsumerToken tok(Q);
void func000() {
chrono::microseconds dura(1000);
while(1) {
    for(int i = 0; i < 50; i++) {
        if(!Q.enqueue(ptok, i)) {
            cout << "func000 i = " <<i << "enqueue failed...!"<<endl;
        }else
            cout <<i<<endl;
    }
    this_thread::sleep_for(dura);
}
}
//
void func00() {
chrono::microseconds dura(1000);
while(1) {
for(int i = 50; i < 100; i++) {
if(!Q.enqueue(ptok, i)) {
cout << "func00 i = " <<i << "enqueue failed...!"<<endl;
} else
cout <<i<<endl;
}
this_thread::sleep_for(dura);
}
}
void func0() {
chrono::microseconds dura(1000);
while(1) {
for(int i = 100; i < 150; i++) {
if(!Q.enqueue(ptok,i)) {
cout << "func0 i = " <<i << "enqueue failed...!"<<endl;
}
else
cout <<i<<endl;
}
this_thread::sleep_for(dura);
}
}
Do you known the reason?!
void func1() {
chrono::microseconds dura(1000);
while(1) {
int num;
if(!Q.try_dequeue(tok, num)) {
this_thread::sleep_for(dura);
continue;
}
    else
    {
        cout<< "func1 num = " << num<< endl;
    }
}
}
int main ()
{
thread th00(func000);
thread th0(func00);
thread th1(func0);
thread th2(func1);
th00.join();
th0.join();
th1.join();
th2.join();
cout << "size_approx = " <<Q.size_approx() <<endl;
return 0;
}

**Comment by cameron314** [comment]
Producer and consumer tokens must only be used by a single thread at a time. I'm afraid there's no easy way to establish a total order.

**Comment by qian0702** [comment]
I'm sorry to hear that, but thank you!
