### ISSUE TITLE
Drop elements from the queue

### ISSUE THREAD

**Issue by Sitiritis** [cameron314/concurrentqueue#165]
Is it possible to just get rid of some elements from the queue without saving them anywhere?

**Comment by cameron314** [comment]
Not exactly. You can provide a dummy value to dequeue into, however.

**Comment by Sitiritis** [comment]
Colud you, please, share a code snippet of how it can be done? Say I want to drop n elements from the queue.

**Comment by cameron314** [comment]
T x;
    for (int i = 0; i != n;)
        i += q.try_dequeue(x) ? 1 : 0;

**Comment by Sitiritis** [comment]
Thank you! Though it would be good to have a function that clears/drops elements from the queue in the API.

I have a situation, where I have several producer threads, which write into the queue and 1 thread that makes a decision based on the values written into the queue in a certain amount of time. When I already made a decision I no longer need data from the queue, because very soon a fresh data will arrive there, so I wolud like to discard the old data.

**Comment by cameron314** [comment]
At this point, I'm not actively developing the queue and will not add new functionality, sorry.
