### ISSUE TITLE
try_enqueue fails at less than the requested limit

### ISSUE THREAD

**Issue by hagaisela** [cameron314/concurrentqueue#169]
Hi,
I am trying this simple test:
 ```c++
#include "concurrentqueue.h"
#include <iostream>

using namespace std;

int main() 
{
    int len = 4096;
    moodycamel::ConcurrentQueue<int> q(len);

    for (int i=0; i<len; i++)
    {
        bool ret = q.try_enqueue(i);
        if (!ret)
        {
            cout << "error" << endl;
        }
    }
}
```
it starts failing at index 1024, but should succeed up to 4096. What am I doing wrong?

**Comment by cameron314** [comment]
It's normal for `try_enqueue` to fail if it would otherwise require allocating memory to succeed.

The queue stores elements in blocks internally. The default block size (controllable through the traits) is 32. Each implicit producer (such as the one you're using) has an internal index to its allocated blocks. This index is large enough to address 32 blocks by default (so, 1024 elements total). After that, the index needs resizing, which requires allocating memory, which causes` try_enqueue` to fail.

I suggest providing traits that better match your use case. A `BLOCK_SIZE` of 256 and `IMPLICIT_INITIAL_INDEX_SIZE` of 16 should do the trick.

**Comment by hagaisela** [comment]
thanks.
do the traits need to be resolved in compile time? I want to be able to use different block and index sizes for different queues and configure this at run time.

**Comment by cameron314** [comment]
The trait values must be known at compile time, but you could instantiate multiple versions with different template parameters.

**Comment by hagaisela** [comment]
another question - is it possible to set a hard limit on the queue size at runtime?
I am using the queue from a c program which needs to configure different queue sizes at runtime, so for now I used a unified traits structure for all my queues (didn't have the time to deal with macro magic for different queue sizes). I used 256 blocks of 256 items each, but I am passing different minCapacity values to the constructor. I noticed that one of the queues that has a minCapacity of 1024 reaches ~1600 items. I want it to stop at 1024.
I guess I can do this inaccurately with an atomic counter, but I was wondering if there is something more elegant.

**Comment by cameron314** [comment]
Well, you can configure the `MAX_SUBQUEUE_SIZE`, but I'm afraid it's also statically defined in the traits :-)

**Comment by hagaisela** [comment]
Hi,
Sorry for bugging you, but I am still having problems with the queue size. I switched to a static allocation, I am setting the queue size to 2048 but it still succeeds when I push the 2049th element.
 ```c++
#include "concurrentqueue.h"
#include <iostream>

using namespace std;

struct MyTraits : public moodycamel::ConcurrentQueueDefaultTraits
{
	static const size_t BLOCK_SIZE = 32;
    static const size_t EXPLICIT_INITIAL_INDEX_SIZE = 64;
};

int main() 
{
    int len = 2048;
    moodycamel::ConcurrentQueue<int, MyTraits> q(len, 1, 0);

    for (int i=0; i<len; i++)
    {
        bool ret = q.try_enqueue(i);
        if (!ret)
        {
            cout << "error" << endl;
        }
    }

    cout << "ret=" << q.try_enqueue(2049);   
}
```

**Comment by hagaisela** [comment]
Hi, sorry for bugging you but I am still having problems with the queue size. I want the queue to be limited to 2048 items but try_enqueue still succeeds when I push the 2049th element.

```c++
#include "concurrentqueue.h"
#include <iostream>

using namespace std;

struct MyTraits : public moodycamel::ConcurrentQueueDefaultTraits
{
	static const size_t BLOCK_SIZE = 32;
    static const size_t EXPLICIT_INITIAL_INDEX_SIZE = 64;
};

int main() 
{
    int len = 2048;
    moodycamel::ConcurrentQueue<int, MyTraits> q(len, 1, 0);
    moodycamel::ProducerToken prod_token(q);
    for (int i=0; i<len; i++)
    {
        bool ret = q.try_enqueue(prod_token, i);
        if (!ret)
        {
            cout << "error" << endl;
        }
    }

    cout << "ret=" << q.try_enqueue(2049);   
}```

**Comment by cameron314** [comment]
It sounds like you might want a circular buffer-based queue instead. This one is formed of a series of sub-queues, one per producer (which has certain advantages and disadvantages, one of them being that the sizing is much more difficult to control exactly).

In this particular example, there are two producers: the explicit one created by enqueueing with the token, and the implicit one created by enqueueing without one at the end. The initial size of the queue is used to compute a minimum number of blocks for the worst case, which is generally more than the number passed ([see the formulas](https://github.com/cameron314/concurrentqueue/blob/master/README.md#preallocation-correctly-using-try_enqueue)). Currently, when using only explicit producers it seems that too many blocks are allocated; I'll try to adjust the constructor code soon.

**Comment by hagaisela** [comment]
I used producer tokens on both try_enqueue calls (I forgot it in the second call and fixed it afterwards).

**Comment by cameron314** [comment]
I looked again at the initialization logic and I think it's correct in the end; it's simply that the worse case with explicit producers is that they all have the maximum number of blocks, which means it's `O(N explicit producers * M maximum elements)` for memory allocation.
