### ISSUE TITLE
Add `folly::MPMCQueue` to benchmarks

### ISSUE THREAD

**Issue by cameron314** [cameron314/concurrentqueue#17]
As suggested by 'ThoraxImpailor' in the comments on my blog post.
Implementation can be found [here](https://github.com/facebook/folly/blob/master/folly/MPMCQueue.h) (Apache license).

**Comment by 0x1997** [comment]
Any update on this?

**Comment by cameron314** [comment]
Don't have the inclination right now, sorry. If someone wants to submit a pull request I'll take the time to integrate it, though.
