### ISSUE TITLE
Can you judge this kind of simple version?

### ISSUE THREAD

**Issue by nickhuangxinyu** [cameron314/concurrentqueue#174]
Hi, cameron.

great work! you must be a c++ expert.
but for me, a beginner, can understand everything you use, So, could you give me some suggestions for the following code?
I think the data[]= operation (which mark with !!!!!!!!!!!) is not good,
bc if code crash there, the other thread's queue will be blocked forever,
Am i right? but I found many tutorials show this kind of code

```
#ifndef __ARRAY_LOCK_FREE_QUEUE_H__
#define __ARRAY_LOCK_FREE_QUEUE_H__

#include <atomic>
#include <thread>

// MAX_SIZE must be (power of 2) -1, then we can count new index by bit operation.
template <typename T, size_t MAX_SIZE = 31>
class ArrayLockFreeQueue {
public:
  ArrayLockFreeQueue() : writeIndex(0), readIndex(0), maximumReadIndex(0) {}
  ~ArrayLockFreeQueue() {}

  bool push(const T &item) {
    size_t currentReadIndex = 0;
    size_t currentWriteIndex = 0;
    size_t nextWriteInex = 0;

    // reserve space to commit
    do {
      currentWriteIndex = writeIndex.load();
      currentReadIndex = readIndex.load();
      nextWriteInex = (currentWriteIndex + 1) & sizeMask;
      if (nextWriteInex == currentReadIndex) {
        // queue full
        return false;
      }
      // cas fail means other producer take this place, this thread need retry
    } while (!std::atomic_compare_exchange_weak(&writeIndex, &currentWriteIndex,
                                                nextWriteInex));

    // commit data to the reserve place // !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    data[currentWriteIndex] = item;

    while (!std::atomic_compare_exchange_weak(
        &maximumReadIndex, &currentWriteIndex, nextWriteInex)) {
      // the commit step should be order between producers, producer 1 ->
      // producer 2 -> producer 3. so when producers more than the cores, yield
      // is needed to avoid spinlock.
       std::this_thread::yield();
    }

    return true;
  }

    bool pop(T &item) {

    size_t currentMaximumReadIndex = 0;
    size_t currentReadIndex = 0;
    size_t nextReadIndex = 0;

    do {
      currentReadIndex = readIndex.load();
      currentMaximumReadIndex = maximumReadIndex.load();

      if (currentReadIndex == currentMaximumReadIndex) {
        // queue empty
        return false;
      }

      // this read will not drop the item in data, so other consumer can still read this item.
      item = data[currentReadIndex];

      nextReadIndex = (currentReadIndex + 1) & sizeMask;
      // cas fail means this item is consumed by other consumer.
    } while (!std::atomic_compare_exchange_weak(&readIndex, &currentReadIndex,
                                                nextReadIndex));

    return true;
  }

  T data[MAX_SIZE + 1];
  const size_t sizeMask = MAX_SIZE;
  std::atomic<size_t> writeIndex;
  std::atomic<size_t> readIndex;
  std::atomic<size_t> maximumReadIndex;
};

#endif // __ARRAY_LOCK_FREE_QUEUE_H__
```

**Comment by cameron314** [comment]
If one thread crashes, the entire process dies, so it doesn't matter if the other threads would be blocked -- none of them should crash :-) But yes, it can be nice to have a guarantee that if a thread is suspended, the other threads can continue to accomplish work ("wait-freedom").

What's more important is making sure that the state of the data structure remains coherent under all possible interleavings of execution from multiple threads.

Your logic in general seems sound at first glance, though I do see a couple problems.

The line with the exclamation marks seems fine: the write index is unique as claimed by the loop above, so it should be safe to write into.

The loop that publishes the maximum read index is buggy. Consider the following situation: thread A acquires index 2, and thread B acquires index 3. Thread B writes to index 3. Then thread B publishes the max read index as 3. But thread A still hasn't written to index 2 yet.

Apart from that, your CAS-loops might be prone to the ABA problem, which may or may not matter depending on how large the queue is.

Finally, some of the memory ordering constraints could be tightened for better performance.

**Comment by nickhuangxinyu** [comment]
Thanks Cameron. great to have your advice.

but i am confused on another issue, that is:
Is this kind of while(CAS) method performance effective?
I do some experiment between this and simple version with just mutex+queue.
I found mutex will be faster, that confused me. Even boost::lockfree::queue is slower than mutex queue.
The experiment is 100 thread write queue, 100 thread read queue, the race is happened a lot.
Then the while(CAS) is quite slower(100s), boost(0.5s) mutex(0.4s), can you give me some guide?
It is really confused me.
I know your code must be a masterpiece in this problem, but a little hard for a beginner.
Can you let me know if you are using while(CAS)?

**Comment by cameron314** [comment]
CAS loops force a all threads to a single point of contention. If the CAS fails, all but one thread will have to try again. So the higher the contention, the slower a CAS loop gets.

A system with 200 active threads is pretty extreme (unless you have a 200-core CPU?). In this case the mutex is much faster, because while only a single thread can complete an operation at a time, all the other threads are efficiently waiting their time without interrupting the active thread. Imagine a crowd of 200 all trying to grab a drink from a machine at once vs the same 200 lining up in an orderly fashion.

I do have some CAS loops in the surrounding infrastructure, but the main queueing algorithm uses atomically incrementing integers instead. This is still a single point of contention, but there's no retrying needed because the increment is always done as a single operation in hardware (it can't fail).

**Comment by cameron314** [comment]
Closing this for now, fell free to reopen if you need more clarification.
