### ISSUE TITLE
Compilation with VS2012 fails (because of =delete functions)

### ISSUE THREAD

**Issue by jlaumon** [cameron314/concurrentqueue#18]
The disabling of the copy constructors / operator= is the only thing preventing your queue from compiling in VS2012 (deleted functions are only supported since VS2013). 

Would you consider hiding the "= delete" behind a macro that resolves to nothing when _MSC_VER <= 1700 ? (I can make a pull request if you want)

In any case, thanks for this very nice code!

**Comment by cameron314** [comment]
Cool! Sure, if you don't mind making a pull request that'd be great (might be a good idea to update the README too where it mentions `VS2013+` as a supported platform).

Keep in mind the queue might be a little slower under [VS2012](http://cpprocks.com/44-c11-bugs-fixed-in-visual-studio-2013/#atomics-were-slow), though.

**Comment by jlaumon** [comment]
Ha good to know, thanks. 
The pull request is on its way.

**Comment by cameron314** [comment]
I got everything compiling and fixed the failing tests when run under VS2012.
