### ISSUE TITLE
A hidden issue in blocking version

### ISSUE THREAD

**Issue by mxydls** [cameron314/concurrentqueue#181]
Hi, first thanks for your comprehensive jobs in lockfree queue.
I'm not sure if there exists a hidden trouble in the blocking version. When calling `wait_dequeue`, if `tryWait` returns false which means there is no item for now, we will call into `waitWithPartialSpinning`. And then we have 10000 times spinning, after which we use `sem_wait` to sleep the thread and wait for a signal. But if the consumer thread exactly hang up and the producer enqueue an item exactly after the spinning and before `sem_wait`, and this thread will never be awaken.
Actually it has been troubling me for a long time about how to implement both lockfree and wait/signal semantic at the same time where we cannot use condition_variable. It is said C++20 is going to support wait on atomic but it has not come.

**Comment by cameron314** [comment]
Actually this scenario should work.

If the spinning consumer sees no element, the count is decremented *before* it waits on the semaphore. (If, after the decrement, it sees there was a value after all, it does not wait on the semaphore.)

Meanwhile, the producer increments the count. If it sees the count was negative, it signals the semaphore. The consumer will then wake up (or, if it hadn't yet waited on the semaphore, it will take it when it goes to wait).

**Comment by mxydls** [comment]
um.. I think there is still a problem here. Think about this, thread A find there is no element after spinning and then decrease the mcount(initialized 0) to -1.
![image](https://user-images.githubusercontent.com/19381432/72502378-194c1600-3874-11ea-90dc-669ab150d54b.png)
Then the condition `if (oldCount > 0)` will be skipped and just before the next statement thread B race to control CPU. Thread B now find mcount to be -1 and will signal once but there is no thread waiting for now. Then switch to thread A, A will wait forever because thread B will never awake it...

**Comment by mxydls** [comment]
I've checked some similar discussions on stackoverflow(e.g https://stackoverflow.com/questions/29943775/correct-way-to-wait-on-a-stdatomicint-in-windows/29944112) and there seems to be no perfect solution. https://en.cppreference.com/w/cpp/atomic/atomic/wait here is C++20 atomic::wait and I don't know if it works yet.

**Comment by mxydls** [comment]
Maybe there is no perfect solution to use atomic with the same semantic as mutex/condition. Your implement has been good for most cases.

**Comment by cameron314** [comment]
When thread B signals and thread A is not yet waiting on the semaphore, the semaphore's internal count is incremented. Then when thread A waits on it, the semaphore is decremented and thread A does not block.

**Comment by mxydls** [comment]
That's right... I forgot it was semaphore...Thanks!
