### ISSUE TITLE
crash when moving ntp time

### ISSUE THREAD

**Issue by hagaisela** [cameron314/concurrentqueue#190]
Hi,
I have an app which uses the blocking version of the queue. The problem is that if another process changes the ntp time it the thread that reads from the queue crashes with this stack trace:

`1970-01-18 19:22:18.489527 [ERROR     ] [wb_agent_main.c:386:signal_action] backtrace:
???(/build/glibc-OTsEL5/glibc-2.27/nptl/../sysdeps/unix/sysv/linux/x86_64/sigaction.c:???)
futex_abstimed_wait_cancelable(../sysdeps/unix/sysv/linux/futex-internal.h:205)
do_futex_wait(/build/glibc-OTsEL5/glibc-2.27/nptl/sem_waitcommon.c:111)
__new_sem_wait_slow(/build/glibc-OTsEL5/glibc-2.27/nptl/sem_waitcommon.c:181)
_ZN10moodycamel7details9mpmc_sema9Semaphore10timed_waitEm(/cheetah/src/libdatapath/data_structures/blockingconcurrentqueue.h:254)
_ZN10moodycamel7details9mpmc_sema20LightweightSemaphore27waitManyWithPartialSpinningEll(/cheetah/src/libdatapath/data_structures/blockingconcurrentqueue.h:365)
_ZN10moodycamel7details9mpmc_sema20LightweightSemaphore8waitManyEll(/cheetah/src/libdatapath/data_structures/blockingconcurrentqueue.h:445)
_ZN10moodycamel23BlockingConcurrentQueueIP12bcm_wrap_pkt19IpfixPktQueueTraitsE23wait_dequeue_bulk_timedIPS2_EEmRNS_13ConsumerTokenET_ml(/cheetah/src/libdatapath/data_structures/blockingconcurrentqueue.h:1060)`

**Comment by cameron314** [comment]
Well that's unfortunate.

Not much I can do about that, it seems like the Linux futex implementation used by glibc's semaphore is "throwing" a signal. Based on your stack trace it's not clear if this is a recoverable signal or not (like a SIGSEGV).
