### ISSUE TITLE
using the queue as a memory pool

### ISSUE THREAD

**Issue by hagaisela** [cameron314/concurrentqueue#192]
Hi,
I am trying to use the queue as a memory pool - I have fixed size buffers and I use try_dequeue_bulk to get the buffers and try_enqueue_bulk to return them.
I sometimes get failures on the try_enqueue calls, even though I think I never return more than I requested. could this be because of block fragmentation?

**Comment by cameron314** [comment]
Yes, there are additional internal data structures that may need to resize automatically depending on usage (e.g. number of producer threads) as well as the blocks themselves. Try playing with the constants in the traits template argument to suit your needs.
