### ISSUE TITLE
Compilation fails

### ISSUE THREAD

**Issue by ppjxhyyy** [cameron314/concurrentqueue#194]
concurrentqueue.h

line 1611 , __declspec( align( __alignof(T) ) )  

error c2059,  "__builtin_alignof"

environment: vs2013 Ultimate update 5
debug x64

**Comment by cameron314** [comment]
Is `__alignof` a macro in your environment?

**Comment by ppjxhyyy** [comment]
`__alignof`

line 231 and 232 works.

**Comment by ppjxhyyy** [comment]
> Is `align` or `__alignof` a macro in your environment?

`__alignof`

line 231 and 232 works.

**Comment by cameron314** [comment]
I'm not sure I understand the error. Can you provide more details?

**Comment by damofeixue** [comment]
I ran into the same issue when trying to compile examples provided in the repo with VS Ultimate 2013 for x86. Both Debug and Release reported the same error.

**Comment by ppjxhyyy** [comment]
> I ran into the same issue when trying to compile examples provided in the repo with VS Ultimate 2013 for x86. Both Debug and Release reported the same error.

me too,  x64 too.



> I'm not sure I understand the error. Can you provide more details?

plz compilation by yourself. 

I'm sorry but I think my description is concise and accurate.

And I can't take pictures on the work machine.

Thanks again.

**Comment by cameron314** [comment]
I don't need screenshots of your work machine, but the full error message would have been nice. I didn't have VS2013 installed, and I didn't know that you were building the unittests (typically such errors only reproduce within the context of a larger project, or with specific types).

Anyway, it should be fixed now. Thanks for reporting.
