### ISSUE TITLE
preprocessor error due to thread sanitizer check

### ISSUE THREAD

**Issue by khuck** [cameron314/concurrentqueue#199]
the issue reported for the readerwriterqueue has appeared in concurrentqueue:
https://github.com/cameron314/readerwriterqueue/issues/69

This bug was just introduced by the PR from https://github.com/cameron314/concurrentqueue/pull/198

Thanks!

**Comment by cameron314** [comment]
Oops, sorry, forgot completely about that. Thanks for opening PR #200 to fix this.

**Comment by khuck** [comment]
no worries, concurrentqueue is fantastic, thanks for your project!
