### ISSUE TITLE
High CPU occupation ratio

### ISSUE THREAD

**Issue by youzhihua** [cameron314/concurrentqueue#204]
CPU occupation ratio is 1000%-1500%（24 core）,But only 2 ms less time（original 50ms  now 48ms）.
Is this normal？  （Production environment concurrency is 200）

**Comment by cameron314** [comment]
I have no idea. It depends what you're doing with the queue. 200 producers or consumers? 2ms less for what? Are you using the blocking version or polling?

**Comment by cameron314** [comment]
Anywhere from 0% to 100% usage of all cores is normal -- as with all data structures it depends on how it's used.

**Comment by youzhihua** [comment]
I store public resources in the queue, such as the Lua execution environment. Each time I process a request, I first take a resource out of the queue, and then put it back in the queue. Is there any problem in this way.

Here is my code
`
template <typename ResourceT, typename FactoryT>
class ResourcePool {
   public:
    // Acquires owner ship of factory.
    ResourcePool(unsigned int capacity, FactoryT *factory);

    ~ResourcePool();

    void set_max_capacity(unsigned int max_capacity) {
        if (max_capacity < _capacity) {
            throw std::invalid_argument("max capacity is lesser than capacity");
        }
        _max_capacity = max_capacity;
    }

    inline void set_need_clear(bool need_clear) {
        _need_clear = need_clear;
    }

    inline int get_size() {
        int size = _size;
        return size;
    }

    ResourcePool(const ResourcePool &) = delete;
    ResourcePool &operator=(const ResourcePool &) = delete;

    // thread safe
    template <typename ResultT>
    ResultT RunWithResource(std::function<ResultT(ResourceT *)> func);

   private:
    ResourceT *GetResource();
    void PutResource(ResourceT *);
    void PutErrorResource(ResourceT *);
    void ClearPool();

    unsigned int _capacity;
    unsigned int _max_capacity;
    bool _need_clear;
    std::unique_ptr<FactoryT> _factory;

    std::mutex _pool_lock;  // protects the following two
    int _size;
    moodycamel::ConcurrentQueue<ResourceT *> _idle;
};

template <typename ResourceT, typename FactoryT>
ResourcePool<ResourceT, FactoryT>::ResourcePool(unsigned int capacity,
                                                FactoryT *factory)
    : _capacity(capacity),
      _max_capacity(std::numeric_limits<unsigned int>::max()),
      _factory(factory),
      _need_clear(true) {
    // std::lock_guard<std::mutex> guard(_pool_lock);
    _size = 0;
    for (unsigned int i = 0; i < _capacity; ++i) {
        try {
            bool flag = _idle.enqueue(_factory->Create());
            if(!flag){
                WLOG("obj=arbiter\tmsg=failed to enqueue resource\terr={}",
                 "Create ResourcePool enqueue failed");
                 continue;
            }
            ++_size;
        } catch (std::exception &e) {
            WLOG("obj=arbiter\tmsg=failed to create resource\terr={}",
                 e.what());
            throw;
        }
    }
}

template <typename ResourceT, typename FactoryT>
ResourcePool<ResourceT, FactoryT>::~ResourcePool() {
    ClearPool();
}

template <typename ResourceT, typename FactoryT>
template <typename ResultT>
ResultT ResourcePool<ResourceT, FactoryT>::RunWithResource(
    std::function<ResultT(ResourceT *)> func) {
    ResourceT *resource = nullptr;
    try {
        resource = GetResource();
        ResultT result = func(resource);
        PutResource(resource);
        return result;
    } catch (std::exception &e) {
        if (resource) {
            PutErrorResource(resource);
            if (_need_clear) {
                ClearPool();
            }
        }
        throw;
    }
}

template <typename ResourceT, typename FactoryT>
ResourceT *ResourcePool<ResourceT, FactoryT>::GetResource() {
    // std::lock_guard<std::mutex> guard(_pool_lock);
    ResourceT *resource;
    if (_idle.try_dequeue(resource)) {
        // resource = _idle.front();
        // _idle.pop_front();
    } else {
        if (_size < _max_capacity) {
            ILOG("msg=idle pool empty, creating new resource");
            resource = _factory->Create();
            ++_size;
        } else {
            throw std::runtime_error("resource pool reach max capacity");
        }
    }
    return resource;
}

template <typename ResourceT, typename FactoryT>
void ResourcePool<ResourceT, FactoryT>::PutResource(ResourceT *resource) {
    if (resource == nullptr) return;

    // std::lock_guard<std::mutex> guard(_pool_lock);
    if (_size >= _capacity && _need_clear) {
        try {
            _factory->Destroy(resource);
        } catch (std::exception &e) {
            WLOG("obj=arbiter\tmsg=failed to destroy resource, ignore\terr={}",
                 e.what());
        }
        --_size;
    } else {
        bool flag = _idle.enqueue(resource);
        if(!flag){
            WLOG("obj=arbiter\tmsg=failed to enqueue resource\terr={}",
                "PutResource enqueue failed");
        }
    }
}

template <typename ResourceT, typename FactoryT>
void ResourcePool<ResourceT, FactoryT>::PutErrorResource(ResourceT *resource) {
    if (resource == nullptr) return;

    // std::lock_guard<std::mutex> guard(_pool_lock);
    try {
        _factory->Destroy(resource);
    } catch (std::exception &e) {
        WLOG("obj=arbiter\tmsg=failed to destroy resource, ignore\terr={}",
             e.what());
    }
    --_size;
}

template <typename ResourceT, typename FactoryT>
void ResourcePool<ResourceT, FactoryT>::ClearPool() {
    // std::lock_guard<std::mutex> guard(_pool_lock);
    ResourceT *resource;
    while (_idle.try_dequeue(resource)) {
        try {
            _factory->Destroy(resource);
            resource = nullptr;
        } catch (std::exception &e) {
            WLOG("obj=arbiter\tmsg=failed to destroy resource, ignore\terr={}",
                 e.what());
        }
        --_size;
    }
}
`

**Comment by cameron314** [comment]
Your code seems fine, so the CPU usage must be normal. Keep in mind that removing a mutex allows more work to be done in parallel, increasing max CPU usage all else being equal. 

Consider using explicit consumer/producer tokens to speed up repeated accesses to the queue from the same threads.

**Comment by youzhihua** [comment]
Thank you for your response. I'll try another way
