### ISSUE TITLE
Where is `configure test`?

### ISSUE THREAD

**Issue by JesseChisholm** [cameron314/concurrentqueue#206]
Fetched repo on 2020.06.19. Built it (using MSVC 19) saw the message:

`Unknown compiler version - please run the configure tests and report the results`

But there don't seem to be any `configure tests` to run.

**Comment by cameron314** [comment]
Looks like it's a message from the Boost headers used in the benchmarks.

**Comment by JesseChisholm** [comment]
Ah. Not an issue here, then. Thanks. Closing!.

**Comment by cameron314** [comment]
I suppose I should update the Boost headers to a more recent version but every time I need to do this it ends up taking a few hours because of various incompatibilities (last couple times I had to change my OS version to get `bcp` to compile and work).
