### ISSUE TITLE
LICENSE.md claims dual licensing, but library comments claim BSD only

### ISSUE THREAD

**Issue by camlorn** [cameron314/concurrentqueue#207]
I need a lockfree queue under Boost, and this looks like a really good one, but I don't want to drop this into my project if source files only claim BSD.  LICENSE.md makes it look like I'm covered, but it would be nice to avoid having conflicting comments in the code.  Is this possible to fix?

**Comment by cameron314** [comment]
Done!

**Comment by camlorn** [comment]
Cool.  Much appreciated.
