### ISSUE TITLE
question about Token

### ISSUE THREAD

**Issue by chengm349** [cameron314/concurrentqueue#209]
take README sample here
```
moodycamel::ConcurrentQueue<int> q;

moodycamel::ProducerToken ptok(q);
q.enqueue(ptok, 17);

moodycamel::ConsumerToken ctok(q);
int item;
q.try_dequeue(ctok, item);
assert(item == 17);
```
Assume I have 2 producer threads and 2 consumer threads and all are accessing the same q. So in my each thread code part, I have same code stmt moodycamel::ProducerToken ptok(q) or moodycamel::ConsumerToken ctok(q). From the 2 producer threads viewpoint, both tokens are the same in sense of value (?).  I'd like to guess that internally the queue makes use of tokens' ID which are different?

**Comment by cameron314** [comment]
Each token is a different object, since they're declared on different stacks. So their values are independent.

**Comment by chengm349** [comment]
understood, they are different objects but same value, right? How this can help the queue? I mean the queue should get something from these 2 objects but with same value. Just curious.

**Comment by cameron314** [comment]
They have different values.

Each producer token is initialized in its constructor with a pointer to a SPMC sub-queue of the parent queue for its exclusive use.

Each consumer token is initialized with what amounts to a random offset, which is then used to accelerate each dequeue operation by helping find a sub-queue with elements more quickly, and with reduced contention.

**Comment by chengm349** [comment]
thanks. now conceptually clear.
