### ISSUE TITLE
Support for timeout on blocking dequeue

### ISSUE THREAD

**Issue by mojoBrendan** [cameron314/concurrentqueue#21]
I needed this for my application and modified the unix semaphore implementation to support this.

Are you interested in adding more widespread support for this? I can create a pull request for you to look at if you want.

**Comment by cameron314** [comment]
I always like pull requests! :-)

The reason it's not already implemented is that I wanted it to be completely cross-platform, and I don't have any Mac OS X machine to try stuff on. One blog post suggests using `semaphore_timedwait`, but I can't find reference to that function anywhere else on the web...

I suppose I could add timed wait support for only those platforms that support it. I'll take a look when I have some time.

**Comment by cameron314** [comment]
This relates to [this issue](https://github.com/cameron314/readerwriterqueue/issues/19).

**Comment by xeoshow** [comment]
Strongly need this feature, when this feature could be available? Thanks!

**Comment by alanchb** [comment]
Is the timed wait support for blocking dequeue available by now? :)

**Comment by cameron314** [comment]
Not yet. Been too busy. ETA early 2016.

**Comment by cameron314** [comment]
This is now done. See issues #22 and #38.
