### ISSUE TITLE
the order of entering the queue

### ISSUE THREAD

**Issue by GREATwo** [cameron314/concurrentqueue#212]
Ask a question. If a producer thread and a consumer thread do not use tokens, is the order of leaving the queue the same as the order of entering the queue?

**Comment by cameron314** [comment]
Without a producer token, the order is preserved (FIFO) only for elements enqueued by the same thread.

**Comment by GREATwo** [comment]
To confirm, does the same thread mean to be queued in one thread and then out of the queue?
If there are two threads, one producer and one consumer, and the order in which the producer threads enter the queue and the consumer thread out of the queue are the same, is it possible to use tokens?

**Comment by cameron314** [comment]
The producer determines the ordering guarantee. If a producer uses a token to enqueue, the relative order of all elements enqueued with that token will be preserved when those elements are dequeued. If a producer does not use a token, the relative order of all elements enqueued on that thread (without a token) will be preserved.

Think of the queue as a collection of SPMC sub-queues (internally, this is how it's designed). Producers enqueue to a specific sub-queue (determined explicitly by token or implicitly by thread ID). Consumers dequeue from all sub-queues in a non-deterministic order.
