### ISSUE TITLE
Been stuck in BlockingConcurrentQueue::try_dequeue_bulk and cpu usage is 100%

### ISSUE THREAD

**Issue by DavidLiuXh** [cameron314/concurrentqueue#213]
Below is my codes(Multi Producer and Single consumer):
```
while (run) { 
LOG(ERROR) << "xxx | before swap | q size:" << q.size_approx();          
 BlockingConcurrentQueue<CQItem> swap_queue;                                
 moodycamel::swap(swap_queue, q);                                           
 LOG(ERROR) << "xxx | after swap | q size:" << q.size_approx();           
 LOG(ERROR) << "xxx | after swap | swap_queue size:" << swap_queue.size_approx();  

size_t size = swap_queue.try_dequeue_bulk(item, MAX_CQITEM);    
LOG(ERROR) << "xxx | after swap | dequeue size:" << size; 
}
```

After the program runs for a while，stuck in the swap_queue.try_dequeue_bulk and cpu usage is 100%.
log at this time:

```
xxx | before swap | q size: 1491
xxx | after swap | q size: 0
xxx | after swap | swap_queue size:1491
```

**Comment by cameron314** [comment]
Are you using the latest version of the queue? There were a few bugs with the blocking semaphore at one point.

**Comment by cameron314** [comment]
Just to make sure, you're not swapping it while another thread is using it?

**Comment by DavidLiuXh** [comment]
I have used the latest version.

Can't I swap it if other thread are writing to this queue?

The following log shows that I have successfully swap：
```
xxx | before swap | q size: 1491
xxx | after swap | q size: 0
xxx | after swap | swap_queue size:1491
```

**Comment by cameron314** [comment]
No, swapping/move-construction is not safe under contention. A swap is not an atomic operation since several different members need to be moved. Even if it was there would still be a race where elements could go to the wrong queue.

**Comment by DavidLiuXh** [comment]
@cameron314  Thanks~~
