### ISSUE TITLE
NUMA constraints

### ISSUE THREAD

**Issue by dvhwgumby** [cameron314/concurrentqueue#214]
Hi.  Love this package.  Have an architecture question:  In the README.md you write, 

> My queue is also not NUMA aware, and does a lot of memory re-use internally, meaning it probably doesn't scale particularly well on NUMA architectures...

Does this mean I can't use this for communication between threads on two different cores of the same CPU?  That's almost a defining use case, and I have no control over which core my thread might run on.

Thanks,
d

**Comment by cameron314** [comment]
You can definitely use it to communicate between cores on the same CPU, but if you use it to communicate between cores on different CPU sockets, where some sockets have faster access to some part of RAM than the others (NUMA), then the performance may not be as good as it theoretically could be.

**Comment by dvhwgumby** [comment]
Thanks.  Closing.
