### ISSUE TITLE
require feature of dequeue data but not pop out from queue

### ISSUE THREAD

**Issue by gzliudan** [cameron314/concurrentqueue#216]
such as: `bool try_dequeue(item&, bool pop_flag = true);`     
When pop_flag is false, the data is not poped out from queue. This is very helpful, especially in the single consumer scenario.

**Comment by cameron314** [comment]
Duplicate of #215. Sorry, not going to implement this. The internal design of the queue makes it impossible to implement either safely or efficiently.
