### ISSUE TITLE
C Api

### ISSUE THREAD

**Issue by rock59** [cameron314/concurrentqueue#217]
Is it possible to provide a C Api in order to make this awesome library usable in C programs and other languages with FFI or similar mechanisms? Queuing and dequeuing void pointers is sufficient.

**Comment by cameron314** [comment]
Wouldn't be too hard for a minimal interface subset. Create, destroy, enqueue, dequeue be enough?

**Comment by rock59** [comment]
Thanks for your quick response. Yes. It's enough for now

**Comment by cameron314** [comment]
OK. I'll add this when I have some free time, which fair warning, might not be for a little while.

**Comment by cameron314** [comment]
Unless you feel like making a pull request? :-)

**Comment by rock59** [comment]
Unfortunately I'm not a professional C++ programmer but I'll try my best  :-)

**Comment by alex-tee** [comment]
i noticed there's some glue code for a C API but this is not installed by cmake. can you please make cmake install this API?

**Comment by cameron314** [comment]
Sorry for the delay. I've been thinking about this, and since the whole point was to provide a header-only library, I've decided to leave the C API out of cmake.
