### ISSUE TITLE
Inconsistent Version Tags

### ISSUE THREAD

**Issue by McKillroy** [cameron314/concurrentqueue#222]
Sometimes the version tags have a "v" as first letter (tag = v1.01) , but 1.02 (tag = 1.0.2) has not.
https://github.com/cameron314/concurrentqueue/tags
Please keep version numbers consistent, because it can cause issues in CMakeFiles of dependent projects.
Thanks

**Comment by cameron314** [comment]
Whoops, fixed, thanks.
