### ISSUE TITLE
Benchmark BlockingConcurrentQueue against dlib::pipe

### ISSUE THREAD

**Issue by pfeatherstone** [cameron314/concurrentqueue#227]
Would it be possible to update the benchmarks to include ```dlib::pipe``` from http://dlib.net/other.html#pipe ?

**Comment by cameron314** [comment]
I'm open to pull requests :-)

**Comment by pfeatherstone** [comment]
How come the plots [here](https://moodycamel.com/blog/2014/a-fast-general-purpose-lock-free-queue-for-c++.htm#benchmarks) do not show ```moodycamel::BlockingConcurrentQueue``` graphs?

**Comment by pfeatherstone** [comment]
@cameron314 I've created a [PR](https://github.com/cameron314/concurrentqueue/pull/228). Hopefully the benchmarks can be updated by running on AWS. Hopefully the graphs can be updated too, and include ```moodycamel::BlockingConcurrentQueue``` as well as ```dlib::pipe```. Usually a user wants to use ```moodycamel::BlockingConcurrentQueue``` anyway to have some upper bound on memory consumption.

**Comment by cameron314** [comment]
Thanks for the pull request! I'll take a look.

The plots were made when the queue was initially released. At the time, `BlockingConcurrentQueue` didn't exist yet. And the AWS results were contributed by a friendly Redditor, so unfortunately I'm unable to reproduce them.

Note also that the `BlockingConcurrentQueue` is no better than the `ConcurrentQueue` in terms of memory consumption, and that a circular-buffer based queue (similar to `dlib::pipe`, if I understand correctly) may better suit your needs in such a case.

**Comment by topin89** [comment]
> similar to dlib::pipe

Yeah, simple fixed-size circular buffer, but it uses `std::swap` internally, no constructors or destructors. It requires some modification in the benchmark code to work. See https://github.com/cameron314/concurrentqueue/pull/229
