### ISSUE TITLE
cast bug

### ISSUE THREAD

**Issue by skaller** [cameron314/concurrentqueue#23]
~/felix>clang++ -std=c++11 -I. ccx.cpp
In file included from ccx.cpp:2:
./concurrentqueue.hpp:1508:78: error: reinterpret_cast from 'const char *' to 'int *'
      casts away qualifiers
  ...idx) const MOODYCAMEL_NOEXCEPT { return reinterpret_cast<T*>(elements) + static_c...
                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ccx.cpp:3:28: note: in instantiation of member function 'moodycamel::ConcurrentQueue<int,
      moodycamel::ConcurrentQueueDefaultTraits>::Block::operator[]' requested here
template class moodycamel::ConcurrentQueue<int>;

This is a stupidity in C++, you'll have to work around it. 
reinterpret cast isn't allowed to cast away const.

The fix is simple: use an ordinary C cast: (T*) instead.

**Comment by cameron314** [comment]
Actually, there's no reason for me to be casting away the const at all. Looks like a copy-paste error. Oops!

Good catch, thanks. Should [now be fixed](https://github.com/cameron314/concurrentqueue/commit/8dcedc1ad0026d4b7bac4edf2ea453e4bc30033b).
