### ISSUE TITLE
End of block

### ISSUE THREAD

**Issue by GREATwo** [cameron314/concurrentqueue#230]
If I use wait_dequeue_bulk_timed in a thread, how can I immediately end the block and exit the thread

**Comment by cameron314** [comment]
Unfortunately there's no way other than to enqueue a dummy value.

**Comment by GREATwo** [comment]
enqueue a dummy value what means? example?

**Comment by cameron314** [comment]
Meaning, enqueue a value just to unblock the consumer. The value itself doesn't matter in this case.

**Comment by GREATwo** [comment]
i see,thank you
