### ISSUE TITLE
Add CMake support

### ISSUE THREAD

**Issue by hsdk123** [cameron314/concurrentqueue#231]
Hi, this is a request to add cmake support for the library.

**Comment by cameron314** [comment]
There's a couple open pull requests already. I prefer using the native build systems directly but I can understand those already using it everywhere might want it here too. Though at the end of the day, this is a header-only library.

**Comment by hsdk123** [comment]
Any particular reason that none of them have gone through? Having them would also make it easier to add github actions for compiling + testing on PR.

**Comment by cameron314** [comment]
1. Lack of time/interest on my part (sorry!)
2. Lack of time/interest on the PR authors' parts
3. Lack of cross-platform compatibility (the whole point is for cmake to be able to build on multiple platforms)
4. PRs adding cmake support are often invasive (e.g. moving the main header files into a folder)

I'll try get around to this eventually though, you're definitely not the only one that's interested :-)

**Comment by cameron314** [comment]
[Light cmake support was added via PR to my readerwriterqueue](https://github.com/cameron314/readerwriterqueue/blob/master/CMakeLists.txt) sister project, though, so perhaps I could start with something similar here, and eventually expand support to the tests.

**Comment by hsdk123** [comment]
@cameron314 
That looks more than sufficient. Made the PR: https://github.com/cameron314/concurrentqueue/pull/232
Could you review?

**Comment by cameron314** [comment]
Thanks!
