### ISSUE TITLE
Signal the semaphore manually in BlockingConcurrentQueue?

### ISSUE THREAD

**Issue by 0x416c69** [cameron314/concurrentqueue#234]
Thank you for this cool lock free queue.

I have a question regarding to BlockingConcurrentQueue, I'm trying to implement a thread pool task scheduler using your BlockingConcurrentQueue.

The question is that can I signal the semaphore manually myself without facing an issue? I want to signal it because I have a function which cancels the tasks and tries to end the threads, now I know there are _timed functions but can I somehow avoid _timed functions and try signaling the semaphore myself whenever the kill function is called so that my worker threads get terminated normally?

**Comment by cameron314** [comment]
This would cause the queue to go into an infinite loop, so no :-) Once the internal semaphore is signaled the queue expects to be able to dequeue an element.

However, you can achieve the desired effect by enqueueing a special dummy "kill" task that tells the worker thread to exit.

**Comment by 0x416c69** [comment]
> Once the internal semaphore is signaled the queue expects to be able to dequeue an element.

Yeah, I also noticed that from here:
https://github.com/cameron314/concurrentqueue/blob/master/blockingconcurrentqueue.h#L364

That is why I asked this question, somehow I thought there is a race situation there which make the consumers get into spinlock but that's the case for unchecked condition variables not semaphores.

> you can achieve the desired effect by enqueueing a special dummy "kill" task that tells the worker thread to exit.

Is this achievable for multiple threads? (Multiple consumers)
Because I cannot know the exact number of threads which are in wait-state (Or could I?) hence it's not easy to know how many dummy tasks should I enqueue in order to make sure they're all signaled.

**Comment by cameron314** [comment]
Maybe I misunderstood -- you're not trying to stop all workers?

**Comment by 0x416c69** [comment]
> Maybe I misunderstood -- you're not trying to stop all workers?

I don't think you misunderstood, I am trying to stop all of them.

**Comment by cameron314** [comment]
Then you can send one dummy task per worker (tracking the number of workers should be pretty straightforward). Each worker will only remove one of these tasks before exiting.

**Comment by 0x416c69** [comment]
> Then you can send one dummy task per worker (tracking the number of workers should be pretty straightforward). Each worker will only remove one of these tasks before exiting.

Couldn't one thread consume two or more of those dummy works?
