### ISSUE TITLE
Enumerate contents

### ISSUE THREAD

**Issue by skaller** [cameron314/concurrentqueue#24]
This is a feature request (not a bug!)  

I need a routine to enumerate all the elements (more precisely, the addresses of
all the elements). I need this for my system garbage collector so it can find
contained pointers. The routine can assume all (other) threads are stopped.

FYI: I am implementing a thread pool whose threads grab jobs from the
queue. These are represented by a pointer. My first exercise is to use it
to do matrix multiplication quickly (to win a language micro-test competition : ) 
A naive implementation will just  dispatch N x N jobs, each of which calculates 
a single inner-product. If N is large enough that should run several times faster 
than a serial algorithm on a quad-core. A more advanced algorithm would use
submatrix partitions (which does a few more operations but uses the cache
better). My current queue uses traditional single mutex lock.

BTW: This kind of queue must be bound. When the queue is full
we want producers to hang waiting (i.e. block), when the queue is empty,
the consumers should also hang (i.e. block). So to actually use your queue,
I needs to wrap the enqueue/dequeue functions which do a timed yield loop. 
My standard queue uses a semaphore, which is another option. So interestingly
I will have to wrap all the locking around you queue anyhow (but only use it when
the queue is empty or full). Note: approximate fullness is good enough.

And so on to the next queue: a priority queue .. :)

**Comment by cameron314** [comment]
There is a blocking version of the queue (added not too long ago) that will make your job easier -- it handles all the blocking on dequeue using a lightweight semaphore (fast when the queue still has items, and doesn't spin-wait forever when it's empty). It doesn't have any blocking enqueue operations, though (that may be an interesting feature to add, though -- I'll have to think about it more).

As for enumerating the contents, I'm afraid that's far more tricky. Even under the assumption that all other threads are stopped, it's entirely possible that the memory effects of operations done on those threads are not yet propagated to the CPU core on which the GC thread is running, which means items might be "missed" even if they're actually logically in the queue. It depends on how the other threads are paused -- there would have to be a memory barrier just before pausing that release all changes to the GC thread, and the GC thread would need a corresponding memory barrier after that point to acquire all those changes.

**Comment by skaller** [comment]
The world stop operation I use has a flag which is checked under a mutex which acts as a full barrier. It's a cooperative stop. Which is rather unfortunate.

However I have to back off my original need for blocking enqueue and dequeue. I have a queue already that does that (and allows enumerating all elements). I also have monitors. I'm using blocking condition variables/semaphores. Unfortunately that leads to a deadlock so I'm right now having to change all blocking operations to used timed waits that loop around and also check the world stop flag.

When a thread stops, it does a setjump() to save all the registers on the stack and then it saves its stack to a control object so the GC can scan all the thread stacks as roots.

With heavy trickery on some OS better can be done but its hard to provide a portable GC whilst still using C/C++ and OS native operations (Posix/Linux, OSX, Windows at least). OTOH any language without a GC is screwed.

**Comment by cameron314** [comment]
I'm continuing to maintain the queue but will not be adding any new features.
