### ISSUE TITLE
Maximum elements in queue

### ISSUE THREAD

**Issue by max197616** [cameron314/concurrentqueue#241]
Hello,

I am observing a strange limitation on the number of items in the queue. This number cannot be more than 1024, although a larger number is specified in the constructor. What could be the problem?
Example:
```
#include "blockingconcurrentqueue.h"
#include <iostream>
#include <thread>

int main()
{
    moodycamel::ConcurrentQueue<int> q(2048);
    std::thread producer([&]()
    {
  for (int i = 0; i != 2048; ++i)
  {
    if(!q.try_enqueue(i))
   {
     std::cout << "unable to insert element " << i << std::endl;
     break;
    }
  }
    });

    producer.join();

    std::cout << "size_approx: " << q.size_approx() << std::endl;
    return 0;
}
```

P.S. If I use a token, then the queue size matches the declared one.

Thanks.

**Comment by cameron314** [comment]
Hello, this is normal; see [issue 169](https://github.com/cameron314/concurrentqueue/issues/169#issuecomment-546113196).

In short, either adjust the traits to fit your use case, or use the three-argument constructor and explicit producer tokens.

**Comment by max197616** [comment]
Thank you.
