### ISSUE TITLE
The order in case where multi producer thread and one consumer thread ?

### ISSUE THREAD

**Issue by triump2020** [cameron314/concurrentqueue#242]
Hi  !   it's really great job !   i have two questions :
  1.  Suppose i have multi producer threads , e.g. A, B,C.......  , and have one consumer thread , e.g.  F , 
      then if A  has successfully enqueued item-A , and then B has successfully enqueued item-B too,  would F probably see the 
      order which is item-B-item-A , namely F sees the item-B before seeing the item-A ? 

      i  guess it would be , since  there is no guarantee about the order in which item-A 's visibility happens before item-B's , 
       though  the visibility of  item-A and item-B  both happen before F 's dequeueing action .  But i ' m not sure of it , need to your confirms , thanks !  

2.  If  C  needs to see the correct order: itemA-itemB ,   a token can do it for this , even though in case where multi producer threads and multi consumer threads?

**Comment by triump2020** [comment]
@cameron314   i have knew more about your queue ,  seems that there is no way to guarantee the order in which other consumers  see item-A before seeing item-B .

BTW ,  to confirm : 1. each explict producer corresponds to one private thread-local sub-queue ,  even though multi producers lives in the same thread ?  and each implict producer conrresponds to one provate thread-local sub-queue too ?   
                              2.  implict producer and explicit producer can exist in the same thread ?

**Comment by cameron314** [comment]
Yes, there is no ordering (at dequeue time) between items enqueued by different producers (be they implicit or explicit).

Each explicit producer corresponds to a single `ProducerToken` (independent of the threads involved). Each implicit producer corresponds to a single thread (the first time a thread enqueues to a given ConcurrentQueue, an implicit producer is created for it). So yes, there can be up to one implicit producer and any number of explicit producers for a single thread.

Both implicit and explicit producers correspond to a single inner sub-queue within the main ConcurrentQueue object.

**Comment by triump2020** [comment]
Thanks for your clear reply !
