### ISSUE TITLE
unsigned int and overflow errors

### ISSUE THREAD

**Issue by wbyates777** [cameron314/concurrentqueue#245]
Under macos when the undefined behaviour sanitiser is enabled, xcode
detects a number of overflow errors in concurrentqueue.h when the queue
is initilaised. 

For example, at line 1771 , the call to new_block_index(0); produces a problem at line 2374
where the code  header->front.store(numberOfFilledSlotsToExpose - 1, std::memory_order_relaxed);
is executed. It results in overflow error as numberOfFilledSlotsToExpose is 0.

Line 2059 produces a similar error when startTailIndex = 0

Another possible issue occurs at lines 3707 and 3715 where
lastKnownGlobalOffset = static_cast<std::uint32_t>(-1);
Here lastKnownGlobalOffset is defined to be a std::size_t which is unsigned - assigning -1 causes an error

Once the queue has set itself up the errors stop occurring, and everything seems to work OK.

**Comment by cameron314** [comment]
Note that UBSan detects more than just undefined behaviour; overflow in unsigned integers is well defined.

I'll try to have a closer look at these lines though.

**Comment by wbyates777** [comment]
Ive been using the queue for a while now without any problems. It was only with UBSan switched on
that the issue became visible. I wasn’t sure if the overflows are deliberate or a possible error, so I thought Id raise an issue.

I’ll keep checking your github site for more info on this.

regards

Bill

**Comment by cameron314** [comment]
I've checked and they're all safe, expected overflows.

Try running without `-fsanitize=unsigned-integer-overflow` [or with `UBSAN_OPTIONS=silence_unsigned_overflow=1`](https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html#silencing-unsigned-integer-overflow).

**Comment by wbyates777** [comment]
Good news. Thank for you time.
