### ISSUE TITLE
A bug in the example code.

### ISSUE THREAD

**Issue by yorkyer** [cameron314/concurrentqueue#252]
Hi, there is a bug in your example code: https://github.com/cameron314/concurrentqueue/blob/master/samples.md#producerconsumer-model-simultaneous-blocking

```c++
while (promisedElementsRemaining.fetch_sub(1, std::memory_order_relaxed)) {
    q.wait_dequeue(item);
    consumeItem(item);
}
```

The condition in `while` should be `promisedElementsRemaining.fetch_sub(1, std::memory_order_relaxed) > 0`.

When the last item is consumed, the outcome of `promisedElementsRemaining.fetch_sub(1, std::memory_order_relaxed)` is 1, and `promisedElementsRemaining` becomes 0.
Now, the other threads will check this condition, and `promisedElementsRemaining` will be less than 0, such that in the original condition, those threads will never exit the loop.

**Comment by cameron314** [comment]
Yup, good catch, sorry about that!
