### ISSUE TITLE
How to compile ?

### ISSUE THREAD

**Issue by meatlover888** [cameron314/concurrentqueue#257]
Dear developer,

I am new to multi-thread (and maybe C++ too).

Now I already have a project, scenario is:
1. 5 threads put data into the queue, randomly, simultaneously。
2. 1 thread pop data from the queue (using a for loop)

BUT that locked free queue (I got it from somewhere else) does not work well, thus I want to use this queue.

My question about [compile] is:
1. What file do I need to put into my project? The whole "concurrentqueue-master" folder?
2. What should I change for my existing CMakeLists.txt? How about the CMakeLists.txt in "concurrentqueue-master" folder?

My question about [the queue] is:
1. In "sample.md" it has listed several ways to use this queue. Which one should I use? Can I just use "Hello concurrency" model?

I am desperate to get help. Should you give my a hand I would be very grateful.

**Comment by cameron314** [comment]
This is a header-only library, so you can simply copy `concurrentqueue.h` next to your source files then `#include` it.

The samples showcase particular aspects of the queue's API and how to use it in different ways. So, you can certainly base your code on the "hello concurrency" sample if that fits your needs.
