### ISSUE TITLE
when compiled with cpprestsdk, errors happened.

### ISSUE THREAD

**Issue by yangqun** [cameron314/concurrentqueue#259]
Hello, i am developing program using cpprestsdk(https://github.com/microsoft/cpprestsdk) and concurrentqueue. 
just include concurrentqueue.h errors will occur. without cpprestsdk file it is happy.

/home/qyang/Desktop/dev/db/include/concurrentqueue/concurrentqueue.h: In static member function ‘static U* moodycamel::ConcurrentQueue<T, Traits>::create_array(moodycamel::ConcurrentQueue<T, Traits>::size_t)’:
/home/qyang/Desktop/dev/db/include/concurrentqueue/concurrentqueue.h:3607:19: error: expected type-specifier before ‘;’ token
    new (p + i) U();
                   ^
/home/qyang/Desktop/dev/db/include/concurrentqueue/concurrentqueue.h: In static member function ‘static void moodycamel::ConcurrentQueue<T, Traits>::destroy_array(U*, moodycamel::ConcurrentQueue<T, Traits>::size_t)’:
/home/qyang/Desktop/dev/db/include/concurrentqueue/concurrentqueue.h:3617:20: error: expected identifier before ‘;’ token
     (p + --i)->~U();
                    ^
In file included from /opt/version/cpprest/include/cpprest/asyncrt_utils.h:16,
                 from /opt/version/cpprest/include/cpprest/json.h:18,
                 from /home/qyang/Desktop/dev/db/src/test.cpp:8:
/home/qyang/Desktop/dev/db/include/concurrentqueue/concurrentqueue.h: In static member function ‘static U* moodycamel::ConcurrentQueue<T, Traits>::create(A1&&)’:
/home/qyang/Desktop/dev/db/include/concurrentqueue/concurrentqueue.h:3633:35: error: expected type-specifier
   return p != nullptr ? new (p) U(std::forward<A1>(a1)) : nullptr;
                                   ^~~
/opt/version/cpprest/include/cpprest/details/basic_types.h:70:22: note: in definition of macro ‘_XPLATSTR’
 #define _XPLATSTR(x) x
                      ^
/home/qyang/Desktop/dev/db/include/concurrentqueue/concurrentqueue.h:3633:33: note: in expansion of macro ‘U’
   return p != nullptr ? new (p) U(std::forward<A1>(a1)) : nullptr;
                                 ^
In file included from /home/qyang/Desktop/dev/db/src/test.cpp:9:
/home/qyang/Desktop/dev/db/include/concurrentqueue/concurrentqueue.h:3633:32: error: expected ‘:’
return p != nullptr ? new (p) U(std::forward<A1>(a1)) : nullptr;
                                ^
                                :
/home/qyang/Desktop/dev/db/include/concurrentqueue/concurrentqueue.h:3633:57: error: expected ‘;’ before ‘:’ token
   return p != nullptr ? new (p) U(std::forward<A1>(a1)) : nullptr;
                                                         ^
/home/qyang/Desktop/dev/db/include/concurrentqueue/concurrentqueue.h:3633:57: error: expected primary-expression before ‘:’ token
/home/qyang/Desktop/dev/db/include/concurrentqueue/concurrentqueue.h: In static member function ‘static void moodycamel::ConcurrentQueue<T, Traits>::destroy(U*)’:
/home/qyang/Desktop/dev/db/include/concurrentqueue/concurrentqueue.h:3640:11: error: expected identifier before ‘;’ token
    p->~U();
           ^
gmake[2]: *** [CMakeFiles/test.dir/build.make:82: CMakeFiles/test.dir/src/test.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:124: CMakeFiles/test.dir/all] Error 2
gmake: *** [Makefile:103: all] Error 2

**Comment by yangqun** [comment]
#include "cpprest/json.h"
#include "concurrentqueue/concurrentqueue.h"
using namespace std;
using namespace web;
int main(){
  return 0;
}

**Comment by yangqun** [comment]
centos 8.2 cmake 3.18 gcc 8.4.1

**Comment by cameron314** [comment]
Looks like something is defining a macro named `U`. Not related to this queue if that's the case.

**Comment by yangqun** [comment]
thanks for your quick reply. I just changed typename U to UU and errors disappeared.

**Comment by cameron314** [comment]
Good, that confirms it. You'll need to find the header that's defining `U`.

**Comment by LiarMaiq** [comment]
> thanks for your quick reply. I just changed typename U to UU and errors disappeared.

No neet to rename, just to add  compile definition _TURN_OFF_PLATFORM_STRING

**Comment by yangqun** [comment]
> 

OK， I will try your suggestion. Thank you so much.
