### ISSUE TITLE
memory leak detect in my program, when using the concurrentqueue.try_dequeue() methord

### ISSUE THREAD

**Issue by lianpei** [cameron314/concurrentqueue#26]
My questions are as follows：

Defines an ConcurrentQueue<Tree> type for storing multiple Tree.

ConcurrentQueue<Tree> _leakedTrees new = ConcurrentQueue<Tree> static ();

Write a method, according to the input of the configuration, the structure of the size of the Tree, and the Tree into the ConcurrentQueue<Tree>.

After the execution of the TryDequeue cycle, the Queue will be cleared. In theory, we think that after ConcurrentQueue<Tree>, TryDequeue has lost the reference to the various Tree object instance, and each Tree object has not been referenced in the program, it can be considered in the implementation of GC.Collect (), will be the Tree object from the heap.

But the leak was so naked.

Thank you for your assistance！

**Comment by cameron314** [comment]
Hi! I'm not entirely sure I understand the whole issue.

How do you know there's a memory leak? (How was this detected?)

If you put a breakpoint in the destructor for your Tree object, is it being called at the right times?

There's no standard garbage collector in C++, so I don't know how exactly the garbage collector you're using tracks object liveness, nor how this would contribute to a leak.

Could you explain further? (A code example would be great!)
