### ISSUE TITLE
[SPMC] externally synchronized `try_dequeue` fails with items in queue

### ISSUE THREAD

**Issue by Selmar** [cameron314/concurrentqueue#265]
Hi,

I couldn't find any related issue, forgive me if I missed one!

I've been running into an issue with the queue when enqueuing on a single thread and using a task scheduler to start a job that dequeues an item. Every now and then, the dequeue fails. When inspecting the queue upon assertion failure, it seems that there is actually an item in the queue, which hints to some kind of race condition.

What's done is effectively something like below; it is easy to write a test and reproduce it. All producers and consumers are implicit. On Windows, x64. It only happens if there are multiple threads dequeuing.

Main thread:
```C++
for(auto& task : tasks)
{
  queue.enqueue(item);
  scheduler.start_job(some_task_func);
}
```
Task thread:
```C++
void some_task_func(...)
{
  Item item;
  bool success = queue.try_dequeue(item);
  assert(success); // fails every now and then
}
```

Is this expected behavior, or does it sound like a bug?

Thanks,
Selmar

**Comment by cameron314** [comment]
Thanks for the example, I can now reproduce instantly (changed `Sleep` to `std::this_thread::yield()`).

I forgot about this, sorry, but dequeuing from the `ConcurrentQueue` is unfortunately only *eventually-consistent*. However, in this specific example, there's explicit synchronization between the threads, so it should never happen that one of them sees the queue as empty. Will look into this more later.

**Comment by Selmar** [comment]
By eventually-consistent, do you mean that a simple atomic read or write (on x86, == acquire/release) outside of the queue is not sufficient, and a fence may be necessary to make the queue state visible immediately? Or do you mean that if the only atomic operations we do are through accessing the queue, the state may not be visible on all threads immediately?

**Comment by cameron314** [comment]
A dequeue could always spuriously fail if there's another consumer. Assuming the memory effects of at least one producer are synchronized with the single consumer (as you do here with jobs) that consumer should never spuriously fail.

> By the way, I thought you may like to know: your queue is 2-8 times faster than our implementation. It performs much better under contention especially.

Excellent :-) If you're using it as a single-producer multi-consumer queue, you're basically hitting the best case.

**Comment by Selmar** [comment]
I think I recall seeing one dequeue failure outside of the above test case, but that is already very rare in comparison to our own queue, so we can hardly call that a problem.

Since you've answered everything, and more, I think we can close this issue. :)

Thank you for your quick and detailed replies!
