### ISSUE TITLE
<concurrentqueue.h> not found

### ISSUE THREAD

**Issue by mscofield0** [cameron314/concurrentqueue#266]
I import the project via [CPM.cmake](https://github.com/cpm-cmake/CPM.cmake) and I use it like:

```cmake
CPMAddPackage(
  NAME concurrentqueue
  GIT_TAG 07534961616f00728a99cbe864c5833c445cfd9b
  GITHUB_REPOSITORY cameron314/concurrentqueue
)
...
target_link_libraries(${PROJECT_NAME} PRIVATE concurrentqueue)
```

but, when I try to actually use the header, it doesn't find it.

I include the header like:
```cpp
#include <concurrentqueue.h>
// also tried: #include <concurrent_queue.h>
// also tried: #include <moodycamel/concurrentqueue.h>
```

What do I do?

**Comment by mscofield0** [comment]
CMake was bugged or something, wasn't the problem with the lib.

**Comment by mscofield0** [comment]
It seems to work in the target itself, but as soon as I import my library to a different target (i.e. the [ModernCppStarter](https://github.com/TheLartians/ModernCppStarter) template way), it fails to open the include file.

**Comment by cameron314** [comment]
Can you provide an example?
