### ISSUE TITLE
Failable try_dequeue_bulk

### ISSUE THREAD

**Issue by uncttao** [cameron314/concurrentqueue#270]
Hi, first of all thanks for this wonderful library that makes my life so much easier!

At the same time, I wonder if there could be an efficient "failable" `try_dequeue_bulk` function such that if it cannot entirely fulfill my request of `n` elements, it does not dequeue any element at all? Currently, this function seems to best-effort dequeue a few elements often `<n`, which doesn't suit my use case well.

**Comment by cameron314** [comment]
Unfortunately such an all-or-nothing (atomic) bulk dequeue operation is not possible with the current design of the queue, since it's based around a collection of sub-queues that are each individually pumped for elements one after another.

**Comment by uncttao** [comment]
That makes sense. Thank you for the clarification!
