### ISSUE TITLE
A question of thread-safe

### ISSUE THREAD

**Issue by LiarMaiq** [cameron314/concurrentqueue#274]
Is that thread-safe if using one producer in multi thread?

**Comment by cameron314** [comment]
I'm not sure I understand the question. The queue is thread-safe with one (or more) threads enqueueing elements while other threads dequeue elements.

**Comment by LiarMaiq** [comment]
I call this method `inline bool enqueue(producer_token_t const& token, T const& item)` in multi thread, but the parameter `token` is the same one, is that safe?

**Comment by cameron314** [comment]
Ah I see. No, this is not safe unless the token is used by only one thread (or one thread at a time, e.g. with a mutex).

Of course, different threads can enqueue using different tokens with no problem.

**Comment by LiarMaiq** [comment]
Thanks for your reply.
