### ISSUE TITLE
BLOCK_SIZE defined by linux/fs.h

### ISSUE THREAD

**Issue by dvd0101** [cameron314/concurrentqueue#280]
Hi,

`concurrentqueue` does not compile if included after `<linux/fs.h>` because the latter defines `BLOCK_SIZE` :(

example:
```
$ echo '
#include <linux/fs.h>
#include "concurrentqueue.h"
int main() {}' | g++ -x c++ -

In file included from <stdin>:2:
concurrentqueue.h:342:29: error: expected unqualified-id before numeric constant
  342 |         static const size_t BLOCK_SIZE = 32;
      |                             ^~~~~~~~~~
concurrentqueue.h:342:29: error: expected ‘)’ before numeric constant
  342 |         static const size_t BLOCK_SIZE = 32;
      |                             ^~~~~~~~~~
concurrentqueue.h:762:29: error: expected unqualified-id before numeric constant
  762 |         static const size_t BLOCK_SIZE = static_cast<size_t>(Traits::BLOCK_SIZE);
      |                             ^~~~~~~~~~
concurrentqueue.h:762:29: error: expected ‘)’ before numeric constant
  762 |         static const size_t BLOCK_SIZE = static_cast<size_t>(Traits::BLOCK_SIZE);
      |                             ^~~~~~~~~~
```

**Comment by randolf** [comment]
I'm having the same problem.

This variable should be renamed to something else, such as CONCURRENTQUEUE_BLOCK_SIZE to prevent the conflict.

**Comment by cameron314** [comment]
This is really a bug with `fs.h` exporting non-namespaced macros, not with my queue (where it's an ordinary identifier, not a macro).

You can `#undef BLOCK_SIZE` before including `concurrentqueue.h` to work around this.

**Comment by cameron314** [comment]
Not going to make this change as it would break the existing public API, sorry.

**Comment by randolf** [comment]
> Not going to make this change as it would break the existing public API, sorry.

This seems reasonable.  How does one go about getting linux/fs.h to fix the naming conflict they're creating?  (For now, I'm having to modify the source in blockingconcurrentqueue.h and concurrentqueue.h, manually changing all instances of BLOCK_SIZE to CONCURRENTQUEUE_BLOCK_SIZE, to get things to compile and avoid creating problems in fs.h.  If you like, I'd be happy to contribute a small script to automate this for those who need it on Linux systems with problematic linux/fs.h files.)

**Comment by cameron314** [comment]
Linux can't change this for the same reason (backwards compatibility). You can either `#undef BLOCK_SIZE` before including concurrentqueue headers, or separate the code using `fs.h` and `concurrentqueue.h` into different .cpp compile units. I personally don't like automated code manipulation that has to be run on a continuous basis, but if you feel others might benefit from an automated renaming script feel free to link to a gist in these comments.
