### ISSUE TITLE
is it safe to use the same token to produce and consume in several threads

### ISSUE THREAD

**Issue by vinllen** [cameron314/concurrentqueue#283]
I have several threads for producing and consuming, I wonder whether it is safe and efficient to use the same token in several threads, e.g., 

* thread1 and thread2 use tokenA to produce, thread3 and thread4 use tokenA to consume.
* thread5 and thread6 use tokenB to produce, thread7 and thread8 use tokenB to consume.

**Comment by cameron314** [comment]
No, producer tokens must not be used concurrently by more than one producer, and consumer tokens must not be used concurrently by more than one consumer.

**Comment by vinllen** [comment]
In my experiment, I'm using your concurrentqueue as a thread pool queue, e.g., there are 4 queues and 4 thread, each thread fetches a task from the corresponding concurrentqueue, besides, there may have some stealing things that happened if some threads find there's no task in the corresponding queue, so each queue have several consumers.
As I went through the documentation: `Using the implicit enqueue methods causes an automatically-allocated thread-local producer sub-queue to be allocated. `. If I choose implicit methods, the subqueue is bonded to thread-local, so it's not work in my experiment, right?

**Comment by cameron314** [comment]
I'm not sure I understand. If you use the implicit methods, then each thread enqueueing jobs to the threadpool will get its own sub-queue. `try_dequeue` will search all sub-queues for an element in the worst case.

`try_enqueue` only fails if it would have needed to allocate memory in order to accept another element. This is somewhat orthogonal to implicit/explicit operations.

**Comment by vinllen** [comment]
Thanks for your answer.

**Comment by cameron314** [comment]
That's one approach, yes.

**Comment by MrGuin** [comment]
Thanks!
