### ISSUE TITLE
try_enqueue() returns true but approx_size() is always 0 and try_dequeue() fails

### ISSUE THREAD

**Issue by teoring** [cameron314/concurrentqueue#285]
I feel like I don't understand some key concept but can't figure it out. 
My environment is U20, gcc 9.3.0, concurrentqueue master branch, one of the latest (38d01f450602513722ccf71a209cdce76bb2758b) commits. 

I have two consumer threads and two producer threads. I construct blocking queue like this ( fixed size ~1024 elements per queue ).

![image](https://user-images.githubusercontent.com/12891023/154945974-a7022694-b785-49f0-95ef-d7185807ea36.png)

Producer threads enqueue elements with try_enqueue that consecutively return true ( 30+ iterations ) but after every insert approx_size() is always 0.

```
        return mQueue.try_enqueue( std::move( aFrame ) ) )
```

Then, I have consumers polling for elements in two ways,
Non blocking if during the last poll queue wasn't empty:
```
        // In case at least one packet was dequeued we return true.
        return mQueue.try_dequeue( aFrame ) )
```

Blocking wait if in last poll queue was empty, wait timeout 100ms:

```
        return mQueue.wait_dequeue_timed( aFrame, aTimeoutMsecs );
```

Both wait_dequeue_timed and try_dequeue always return false. I did some debugging and I think they exit in LightweightSemaphore::tryWait with oldCount == 0.

Notes: 

Consumer threads start before producer threads.
I took concurrentqueue.h, lightweightsemaphore.h, blockingconcurrentqueue.h from the repository and placed them in my project.

**Comment by teoring** [comment]
Ok. I think I need to introduce a proper memory barrier ( release in producer + acquire in consumer? ) so that consumer see the elements in the queue, is that right?

**Comment by teoring** [comment]
Confirmed, sorry for this spam :)

**Comment by cameron314** [comment]
No worries, feel free to reopen if there's anything else you run into. The eventually-consistent nature of the queue can be tricky.
