### ISSUE TITLE
try_dequeue blocks for up to 10ms (mingw)

### ISSUE THREAD

**Issue by SnapperTT** [cameron314/concurrentqueue#299]
Firstly, thanks for the great library!

I'm having an issue with gcc-cross compiled x86_64 mingw code:

```
class Foo {
public:
	moodycamel::BlockingConcurrentQueue<PacketDisassemblyThread_Job_t> leInQueue;
	moodycamel::ConcurrentQueue<PacketDisassemblyThread_Job_t> leOutQueue;
	...
	
	void poll(NetworkInterfaceI* NI) {
		Profiler_t P;
		P.push("PacketDisassemblyThread.start"); 
		isPolling = true;
		while (true) {
			PacketDisassemblyThread_Job_t pe;
			leOutQueue.try_dequeue(pe);
		        P.push("PacketDisassemblyThread.try_dequeue");
		        ...
		        // do stuff with pe
		        }
           }
}
```
`try_dequeue` usually is instant, but sometimes takes up to 10ms to clear. `PacketAssemblyThread_Job_t` is a small class. Linux gcc performance is fine. Cross compiled mingw code is run on a native windows machine. I have 1 producer and 1 consumer thread.

Compiler:
```
$ x86_64-w64-mingw32-g++ --version
x86_64-w64-mingw32-g++ (GCC) 11.2.0
```

Any suggestions? Cheers

**Comment by cameron314** [comment]
You're not checking the return value of `try_dequeue`.

**Comment by cameron314** [comment]
How do you know it's taking 10 ms?

**Comment by SnapperTT** [comment]
It turns out that the constructor for `PacketDisassemblyThread_Job_t` was taking 10ms. Inside it there was an allocation whose size was uninitialized. 

Cheers for your prompt response and sorry to be a trouble mate, my brain has been melted by fixing mingw issues.

**Comment by cameron314** [comment]
Ah that explains it! :-)
