### ISSUE TITLE
Program crashed when it calls try_dequeue_bulk, how to handle this ?

### ISSUE THREAD

**Issue by driftli** [cameron314/concurrentqueue#311]
<img width="1127" alt="image" src="https://user-images.githubusercontent.com/44229257/184588973-7f0e20cd-fed8-4ba1-b29a-a77758c85c35.png">

Here is my structure definition:
<img width="727" alt="image" src="https://user-images.githubusercontent.com/44229257/184589393-081b0082-d635-43b2-8c99-3b78f1537e3b.png">

And some codes:
<img width="659" alt="image" src="https://user-images.githubusercontent.com/44229257/184589758-0e965920-eeb8-4dfd-b369-9645490bae84.png">

**Comment by cameron314** [comment]
Don't see anything wrong with the code posted. Can you reduce it to a self-contained example?

**Comment by gentooise** [comment]
Hi @cameron314, I didn't know where to ask exactly so I'm using this issue. Related to bulk operations, can they be used with STL containers (such as an `std::vector` or an `std::list`) or just plain old arrays? I see they accept a sort of iterator, but I'm not sure what to pass.
Thank you

**Comment by cameron314** [comment]
Yes, any output iterator will do for `dequeue_bulk`, and any input iterator for `enqueue_bulk`.
