### ISSUE TITLE
iOS

### ISSUE THREAD

**Issue by martinfinke** [cameron314/concurrentqueue#32]
I would like to use the concurrent queue in an iOS project. However, when I try to compile I get the following error:

> concurrentqueue.h:103:49: Thread-local storage is not supported for the current target

The problem is in this line:
```cpp
static inline thread_id_t thread_id() { static MOODYCAMEL_THREADLOCAL int x; return reinterpret_cast<thread_id_t>(&x); }
```

For now I've found a quick solution by creating a file `concurrentqueue.mm` with the following contents:

```cpp
#include "concurrentqueue.h"
#import <Foundation/Foundation.h>

moodycamel::details::thread_id_t moodycamel::details::thread_id() { return reinterpret_cast<thread_id_t>([NSThread currentThread]); }
```

...adding a conditional include to the top of `concurrentqueue.h`:

```cpp
#if defined(__APPLE__)
#include "TargetConditionals.h"
#endif
```

...and replacing the problematic line by this code:

```cpp
#if defined(__APPLE__) && (defined(TARGET_IPHONE_SIMULATOR) || defined(TARGET_OS_IPHONE))
    thread_id_t thread_id();
#else
    static inline thread_id_t thread_id() { static MOODYCAMEL_THREADLOCAL int x; return reinterpret_cast<thread_id_t>(&x); }
#endif
```

This seems to work, but it's not as nice as just having one header file. I can't think of a better solution right now, but maybe we can discuss it here.

**Comment by cameron314** [comment]
This relates to pull request #29.

**Comment by cameron314** [comment]
Aha, I think I know what to do with this.

It's unfortunate that iOS doesn't support TLS (which I assumed would exist on all C++11ish compilers), but no matter, I only really use it for obtaining a unique ID per thread. As @jupp0r discovered, this can also be done via `std::this_thread::get_id()`. The only trouble is I needed two distinct invalid values that can't also be thread IDs; `std::thread::id` provides for only one.

However, I only use the second invalid ID to implement a feature that requires TLS to work anyway, so that feature macro would be disabled in that case anyway, leaving me able to use `std::thread::id` (yay!).

The only trouble is that technically, `std::thread::id` may not be a simple integer -- it's trivially copyable, but two different byte representations could compare equal with custom comparators. I also have no idea what the overhead is for obtaining the thread ID on iOS.

So, since you have access to the platform, I'll ask if you would be kind enough to do the following:
1) Find out if `std::thread::id` is a simple integer or not on iOS (is the non-member `operator==` special?)
2) Run my benchmarks that show how long it takes to call `std::this_thread::get_id()` (do a `git clone --recursive` of https://github.com/cameron314/atomic_bench).

**Comment by jupp0r** [comment]
```std::hash``` is implemented for std::thread_id, so you could use that to obtain a ```std::size_t```.

**Comment by cameron314** [comment]
Ah, but `std::hash` does not necessarily give unique hashes :-)

**Comment by cameron314** [comment]
Also just FYI, `std::this_thread::get_id()` is 300x slower than `GetCurrentThreadId()` on MSVC. No idea how it performs on Linux, iOS, etc.

**Comment by martinfinke** [comment]
Right now I only have access to the iOS simulator, but I'll probably test on a real device in the near future.

> 1) Find out if `std::thread::id` is a simple integer or not on iOS (is the non-member `operator==` special?)

When I `#include <thread>` in an iOS project and use Xcode to jump to the file, it opens the file */Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/thread*. I think this is the one being used, because the iOS SDK (9.1) contains its own `<atomic>` and `<functional>`, but not `<thread>`.

In this file, `std::thread::id` is typedef'd to `__thread_id`, which is a `class` with only one attribute `pthread_t __id_;`. The member (!) `operator==` just compares this `__id_`.
`pthread_t` is typedef'd to `__darwin_pthread_t`, which is typedef'd to `struct _opaque_pthread_t *`. These definitions are the same for the simulator SDK and the device SDK.

**Summary / TLDR:** `std::thread::id` is a `class`, but the member `operator==` is implemented as a comparison of two pointers. `std::this_thread::get_id()` is implemented as `return pthread_self();`.

I hope this is (some of) the information you're looking for.

> 2) Run my benchmarks that show how long it takes to call `std::this_thread::get_id()`

Sure :) But I tried to run them in the simulator, and there's an error in microbench.h:75, about the `assert(q < 4 && q > 0)`: *Reference to non-static member function must be called* (referring to the first `q`).

**Comment by cameron314** [comment]
Oh, oops. That assert is totally wrong, it should be checking the parameter. Fixing, please hold!

**Comment by cameron314** [comment]
Alright, I've fixed the assertion. But you should be running the benchmark with `-DNDEBUG` and `-O3`.

**Comment by cameron314** [comment]
Thanks for the detailed investigation of `std::this_thread::get_id()`! Much appreciated. It's exactly what I was looking for.

**Comment by martinfinke** [comment]
Thanks for fixing. Some **simulator** results are below. Compiled with iOS 9.1 SDK and run in the simulator on a MacBook Air mid-2011.

### iPhone 5
```
32-bit CAS takes 49.2084ns on average
64-bit CAS takes 62.2087ns on average
32-bit FAA takes 35.5487ns on average
64-bit FAA takes 63.0698ns on average
std::this_thread::get_id() takes 21.6200ns on average
pthread_mach_thread_np(pthread_self()) takes 22.7176ns on average
```
### iPhone 6
```
32-bit CAS takes 32.7848ns on average
64-bit CAS takes 22.1598ns on average
32-bit FAA takes 30.1754ns on average
64-bit FAA takes 30.8622ns on average
std::this_thread::get_id() takes 14.6488ns on average
pthread_mach_thread_np(pthread_self()) takes 18.4856ns on average
```
### iPhone 6s Plus
```
32-bit CAS takes 32.2473ns on average
64-bit CAS takes 32.3501ns on average
32-bit FAA takes 23.7544ns on average
64-bit FAA takes 30.2334ns on average
std::this_thread::get_id() takes 14.6107ns on average
pthread_mach_thread_np(pthread_self()) takes 17.0769ns on average
```
### iPad 2
```
32-bit CAS takes 27.2899ns on average
64-bit CAS takes 56.9956ns on average
32-bit FAA takes 26.3636ns on average
64-bit FAA takes 52.2845ns on average
std::this_thread::get_id() takes 21.6360ns on average
pthread_mach_thread_np(pthread_self()) takes 23.1409ns on average
```
### iPad Air
```
32-bit CAS takes 31.0635ns on average
64-bit CAS takes 36.1364ns on average
32-bit FAA takes 28.3323ns on average
64-bit FAA takes 26.1996ns on average
std::this_thread::get_id() takes 14.6087ns on average
pthread_mach_thread_np(pthread_self()) takes 18.6738ns on average
```

**Comment by cameron314** [comment]
Great, thanks! Looks like `std::this_thread::get_id()` is perfectly usable on iOS from a performance perspective (but not on, say, Win32).

So, I can safely add (yet another) platform-specific `#ifdef` for iOS thread IDs, which will both fix this issue and obsolete pull request #29 (I can't switch across the board because `std::thread_id` may not be a numeric/pointer type on all platforms, and on those it is there's no performance guarantees).

**Comment by martinfinke** [comment]
Great! I will add results from an actual device later, but I'd be surprised if they were completely different.

**Comment by ZizhengTai** [comment]
Thanks for all the work! Just want to add that sometimes simulators and real devices do actually disagree a lot on things (from performance perspective). Most of the disagreements involve GPU but it's always a good idea to test on real devices before making changes.

**Comment by martinfinke** [comment]
I actually hadn't set `-DNDEBUG` and `-O3` when benchmarking in the simulator. I set those flags and benchmarked on my iPhone 4:

### iPhone 4
iOS 9.1 SDK, device running iOS 6.1.
```
32-bit CAS takes 100.8185ns on average
64-bit CAS takes 108.3355ns on average
32-bit FAA takes 94.3694ns on average
64-bit FAA takes 96.7093ns on average
std::this_thread::get_id() takes 25.1667ns on average
pthread_mach_thread_np(pthread_self()) takes 52.7148ns on average
```

**Comment by cameron314** [comment]
Cool. Thanks! Seems speedy.
Whatever the equivalent of "Release" is in Xcode uses `-Os` by default, I believe.

**Comment by ZizhengTai** [comment]
Any update?

**Comment by cameron314** [comment]
Not yet, sorry. ETA early 2016.

**Comment by cameron314** [comment]
I pushed a commit which should fix this, but I don't have the platform to test it. For all I know it doesn't even compile ;-)

If someone could verify that it compiles and runs on iOS, and ideally run the unit tests too, that'd be great!

**Comment by cameron314** [comment]
Haven't heard back about any problems, so I'm closing for now.
