### ISSUE TITLE
multi-thread problem

### ISSUE THREAD

**Issue by alanchb** [cameron314/concurrentqueue#33]
Hi,when using the ConcurrentQueue in multi-thread,I found a problem.Below is my code:

moodycamel::ConcurrentQueue<int> q;
void threadproc()
{
	for (int i = 0; i < 10; i++)
        {
		q.enqueue(i);
	}
}

int main()
{
	thread td1(threadproc);
	td1.join();
	thread td2(threadproc);
	td2.join();

	int d;
	while (q.try_dequeue(d))
        {
		cout << d << " ";
	}
	cin.get();
        return 0;
}

The expected output is:
0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 

Not as expected, the output result is:
0 0 1 1 2 2 3 3 4 4 5 5 6 6 7 7 8 8 9 9 

Is it a bug of ConcurrentQueue about multi-thread or the usage of ConcurrentQueue in my code is wrong?

**Comment by cameron314** [comment]
Hi!

This is actually normal. As soon as you enqueue from multiple threads, there's absolutely no guarantee what order they'll come out in -- just that the elements that went in on one thread will come out in the same order relative to each other.

**Comment by alanchb** [comment]
But in fact, there has td1.join() to wait until first thread ended then start second thread to enquene data.I think this case is different from what you relied above.

**Comment by cameron314** [comment]
Ah. Sorry, I missed that.

Yes, though it's confusing, that's still normal. There's still no guarantees when things are enqueued from different threads (even if there's external synchronization between the threads, such as in this case the entire thread lifetimes being serialized).

Internally, each thread is enqueueing to a different sub-queue (the implicit producer methods use the thread ID to map to a sub-queue, and so these threads, serialized though they may be, will generally still have different thread IDs and thus different sub-queues). When dequeueing, a handful of the sub-queues are polled, with the one having the largest number of elements being chosen to dequeue from next. In this example, the largest sub-queue will alternate after every dequeue operation. This is why the output is interleaved the way it is.

You can read the section about non-linearizability in the README to find out more.

Sorry for the confusion!

**Comment by cameron314** [comment]
And just to clarify: If you used the explicit producer interface, you'd see the output you expect because the sub-queues for explicit producers are reused by the next producer after the previous one is destroyed (so there'd be only one sub-queue, leading to a deterministic output for this example).

**Comment by alanchb** [comment]
Thanks for the explainations.
The ConcurrentQueue is a great job!
