### ISSUE TITLE
Issue Verify query with relational opeartors

### ISSUE THREAD

**Issue by janraak** [cameron314/concurrentqueue#331]
Verify queries like 
rxquery year_founded > 2000
rxquery year_founded > 1600 & year_founded < 1900

**Comment by cameron314** [comment]
Are you sure this is the right repo?

**Comment by janraak** [comment]
No, I made a mistake, don’t see how to remove the issue.

Excuses.

Kind regards/Met vriendelijke groet

Jan Raak

(Sent from my iPad)

On 18 Jan 2023, at 12:51, Cameron ***@***.***> wrote:

﻿

Are you sure this is the right repo?

**Comment by cameron314** [comment]
No problem

**Comment by janraak** [comment]
tx

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

________________________________
