### ISSUE TITLE
bus error occurs when program runs to line at "index &= hash->capacity - 1u;" in file concurrentqueue.h

### ISSUE THREAD

**Issue by JiangDonglai98** [cameron314/concurrentqueue#337]
I am using the ConcurrentQueue in a condition for multi-producers and one consumer in different threads. Those producers' threads has their own locks, and consumer no lock. Can I use this ConcurrentQueue in this acondition? After I finish build and running the code, it first get an segmentation fault. I go through the printout and locate the problem to that line of code "index &= hash->capacity - 1u;" in file concurrentqueue.h.

**Comment by JiangDonglai98** [comment]
I try the demo example of multi-producers and one consumer in different threads with or without locks. It works fine. So I am not sure what cause this error.

**Comment by cameron314** [comment]
Would need to see the code, but nothing sounds inherently wrong with such a setup. Please continue to try to reproduce in a self-contained example.

**Comment by JiangDonglai98** [comment]
I use this queue in a singleton and open a thread to receive data structure in the singleton.  Other producer threads are opened by somwhere else. I use the concurrentqueue's enqueue methos in their thread to send data structure. 

![image](https://user-images.githubusercontent.com/51168630/228413875-0355d37b-aa12-4fde-974c-91fab5b08e44.png)
![image](https://user-images.githubusercontent.com/51168630/228414406-53687bd9-3812-4cb4-8568-f1f50f170ddc.png)
![image](https://user-images.githubusercontent.com/51168630/228414774-1147fc5e-bc88-4bc5-9925-02038f66e449.png)

**Comment by JiangDonglai98** [comment]
The error ocurs when a digitwise operation happend, I found.
![image](https://user-images.githubusercontent.com/51168630/228416102-59684f2b-ec87-45fe-98d4-287e2bbad6e7.png)
![image](https://user-images.githubusercontent.com/51168630/228416220-2e329c34-519c-4318-9508-afdd7392a7a6.png)
