### ISSUE TITLE
Need exit mechanism for sample: Threadpool task queue

### ISSUE THREAD

**Issue by poor1017** [cameron314/concurrentqueue#339]
Hi @cameron314 

I read all the samples in `concurrentqueue/samples.md`, they are great, except:

For sample: Threadpool task queue
I think we should replace `wait_dequeue()` with `wait_dequeue_timed()`.
Because there is a `while (true)`, so we need a break to exit this `while`, but `wait_dequeue()` may cause the break never be achieved.

Thank you!

**Comment by cameron314** [comment]
Ah, the assumption was that one of the tasks would cause the processing code to break out of the loop. I could probably make that more clear (at the expense of a lomger example).

**Comment by poor1017** [comment]
If using `wait_dequeue()` and the queue may be empty all the time, the loop may hang all the time, at this time, how to break out of the loop?

And now, if some one destroy the queue, an undefined error occurs?

**Comment by poor1017** [comment]
Got it, thank you!
