### ISSUE TITLE
About ConsumerToken

### ISSUE THREAD

**Issue by alanchb** [cameron314/concurrentqueue#34]
Hi，there's another question.

I create a single ConsumerToken which used in multi-thread without synchronization.It appears that the dequeue method in every thread act correctlly.In your readme I found:

***************** from readme
The queue can take advantage of extra per-producer and per-consumer storage if
it's available to speed up its operations. This takes the form of "tokens":
You can create a consumer token and/or a producer token for each thread or task
(tokens themselves are not thread-safe), and use the methods that accept a token
as their first parameter
*****************

So my confution is whether the ConsumerToken is thread-safe or not exactlly? And in which situations should I use ConsumerToken?

Thanks a lot.

**Comment by cameron314** [comment]
Tokens are definitely *not* thread-safe (your example probably works by coincidence, but could conceivably break under contention). Sorry :-)

If the consumer token were thread-safe, I wouldn't have needed to add it to the design, as the functionality could have been simply baked into the queue itself.

The point of the consumer token is that, if you, as a consumer of elements of the queue, are going to consume more than once in a while, you should create a consumer token and use it when dequeueing (the consumer token allows much faster dequeueing, while the producer token allows slightly faster enqueueing but also has other side benefits).

It might help if you think of threads as people, and tokens as bus passes. If one person has a bus pass (token), they can use it to move around easier (dequeue faster). Each person can have no bus pass, or one, or even many, and passes can be passed around between people, but a bus pass can't be used by two people at once. Make sense?

**Comment by alanchb** [comment]
Thanks.
As you said, the consumer token allows much faster dequeueing.I wrote a test case to check dequeueing with consumer token and without it in a single thread while loop.But I found the time they cost are almost the same.(100,000 times dequeueing).

**Comment by cameron314** [comment]
It depends on a few things -- if there's only one producer, then the consumer token is not going to accelerate it much. If the queue is empty, same thing. But if there is (or was) multiple producers, the speedup should be quite noticeable. Also, make sure to run your benchmark in Release/`-O3 -DNDEBUG`, that's another common source of timing inaccuracy.

**Comment by cameron314** [comment]
Oh, and you might like to run my existing benchmarks to see the results on your specific system.

**Comment by alanchb** [comment]
I see, thank you very much!

**Comment by cameron314** [comment]
No problem :-)
