### ISSUE TITLE
Clarification Needed on try_dequeue Function Logic

### ISSUE THREAD

**Issue by AlanHN** [cameron314/concurrentqueue#344]
Hi there! I have a question regarding the logic in the try_dequeue function in your codebase. 
https://github.com/cameron314/concurrentqueue/blob/810f6213a2ee3bbd0c2ff647c28996cfff84df06/concurrentqueue.h#L1127-L1141
Specifically, I am unsure about the following:

1. Is there a risk of the later queues never being dequeued from if the first few non-empty queues keep growing?
2. If there are multiple consumers, do they share the same producerListTail? And if so, could this lead to an imbalance in the number of elements in the queues?

I would greatly appreciate any clarification on these points. Thank you!

**Comment by cameron314** [comment]
1. Yes, starvation can occur. Use consumer tokens to protect against this.
2. There's only one `producerListTail` per ConcurrentQueue instance. It's a linked list of all internal sub-queues, one per producer, and is not directly related to the number of elements in each.

**Comment by AlanHN** [comment]
Thank you for your clarification. I consider this issue resolved.
