### ISSUE TITLE
blockingcurrentqueue::try_dequeue(item) stuck in an endless loop

### ISSUE THREAD

**Issue by oviano** [cameron314/concurrentqueue#347]
Very occasionally I have found things gets stuck looping here:

```
	// Attempts to dequeue from the queue.
	// Returns false if all producer streams appeared empty at the time they
	// were checked (so, the queue is likely but not guaranteed to be empty).
	// Never allocates. Thread-safe.
	template<typename U>
	inline bool try_dequeue(U& item)
	{
		if (sema->tryWait()) {
			while (!inner.try_dequeue(item)) {
				continue;
			}
			return true;
		}
		return false;
	}
```

I wonder if there is a legitimate circumstance where the sema->tryWait() can return true, but somehow there are no items left to dequeue, in which case instead of the while loop maybe it should just return false?

**Comment by cameron314** [comment]
That should never happen. Can you reproduce in a self-contained example?

**Comment by oviano** [comment]
I'll try and do that!

**Comment by oviano** [comment]
Before I embark on that, I wanted to check whether there is something I am fully understanding.

I am using a producer token, and there are two threads enqueueing items to the queue with the same producer token.

Is that thread-safe? It's just that I wasn't sure what this comment meant, highlighted bit in bold.

_but rather one that happens to be spread across multiple threads. In this case, you can still establish a total ordering with my queue by creating a single producer token, and using that from both threads to enqueue (**taking care to synchronize access to the token**, of course, but there was already extra synchronization involved anyway)._

**Comment by cameron314** [comment]
That's not safe, no. The point of the tokens is that each one is used exclusively by a single producer (or my multiple threads pretending to be a single producer, e.g. by enqueueing under a mutex).

**Comment by oviano** [comment]
> That's not safe, no. The point of the tokens is that each one is used exclusively by a single producer (or my multiple threads pretending to be a single producer, e.g. by enqueueing under a mutex).

Ok that's probably my issue then, since I've only seen this in this part of the code, the only place I'm using a producer token.

Thanks.
