### ISSUE TITLE
Build errors in VS2015 update 1

### ISSUE THREAD

**Issue by tinaungwin** [cameron314/concurrentqueue#35]
Error	C3066	there are multiple ways that an object of this type can be called with these arguments	fuzztests	c:\devl\c++14\concurrentqueue-master\concurrentqueue-master\tests\fuzztests\fuzztests.cpp	676	1	

Error	C2280	'std::atomic<boost::lockfree::detail::tagged_ptr<T>>::atomic(void) noexcept': attempting to reference a deleted function	benchmarks	c:\devl\c++14\concurrentqueue-master\concurrentqueue-master\benchmarks\boost\lockfree\queue.hpp	109	1	

Error (active)		the declared exception specification is incompatible with the generated one	benchmarks	c:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\atomic	662	2	

Error (active)		the declared exception specification is incompatible with the generated one	benchmarks	c:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\atomic	508	2

**Comment by cameron314** [comment]
This should be fixed now! Feel free to re-open if it's not.
