### ISSUE TITLE
Is there that kind of API here: call once to clear all data?Even if the caller does not know the number of data in the queue

### ISSUE THREAD

**Issue by yyf117** [cameron314/concurrentqueue#353]

**Comment by cameron314** [comment]
No. You must repeatedly dequeue, or, if the queue is not being used from any other thread, you can assign an empty temporary:

    q = ConcurrentQueue<int>();

**Comment by yyf117** [comment]
thanks.I try to do it like that:
//
qq0=new moodycamel::ConcurrentQueue<cv::UMat>;
//

//Under certain conditions，try to clear all data elements in queue qq0;
UMat r[64];//To clear data at once，i need to set this number  larger,such as 64,or 128, ... ,etc.
qq0->try_dequeue_bulk(r,64);

**Comment by yyf117** [comment]
> No. You must repeatedly dequeue, or, if the queue is not being used from any other thread, you can assign an empty temporary:
> 
> ```
> q = ConcurrentQueue<int>();
> ```

thanks.I try to do it like that:
//
qq0=new moodycamel::ConcurrentQueuecv::UMat;
//

//Under certain conditions，try to clear all data elements in queue qq0;
UMat r[64];//To clear data at once，i need to set this number larger,such as 64,or 128, ... ,etc.
qq0->try_dequeue_bulk(r,64);
It doesn't look very convenient to use this way
will you  update the version and add an API for clearing data at once oneday？

**Comment by cameron314** [comment]
No, sorry, see https://github.com/cameron314/concurrentqueue/issues/150#issuecomment-467457890

**Comment by yyf117** [comment]
> No, sorry, see [#150 (comment)](https://github.com/cameron314/concurrentqueue/issues/150#issuecomment-467457890)

Anyway，thanks again.
