### ISSUE TITLE
error C2129: static function 'bool moodycamel::details::likely(bool)' declared but not defined

### ISSUE THREAD

**Issue by fmvin** [cameron314/concurrentqueue#354]
I'm getting this error from master on Windows Server 2019 x64 and msvc CL Version 19.37.32822 (Visual Studio 2022 v. 17.7.0)

If manually to remove `static` from the `likely` function then the code successefully has been built.

**Comment by cameron314** [comment]
What header(s) did you include?

**Comment by cameron314** [comment]
The only declaration of `likely` is also a definition, so this error should be impossible...

**Comment by fmvin** [comment]
> What header(s) did you include?

I do `#include "blockingconcurrentqueue.h"` in  MyModule.ixx

**Comment by cameron314** [comment]
Sounds like you're using C++ modules? Can you share an example?

**Comment by fmvin** [comment]
I'm created a one more simple test project from scratch with `blockingconcurrentqueue` to present here and suddenly for me the issue is not reproduced. 
I'm strongly apologize for disturbance and propose to close this issue.
Somehow my issue is related to dependency of [imgui_bundle](https://github.com/pthom/imgui_bundle) in my real project which I should investigate independently from`concurrentqueue`.

**Comment by cameron314** [comment]
That's good news, thanks for following up. No need to apologize! Reopen as needed.
