### ISSUE TITLE
Release queue memory without calling destructors

### ISSUE THREAD

**Issue by bear24rw** [cameron314/concurrentqueue#360]
I have a concurrentqueue of shared_ptr's pointing to buffers. When my program terminates the concurrentqueue destructor calls the shared_ptr destructors which free all the buffers. It takes significant time to free all the buffers. Since the program is terminating I'd rather just release the memory without calling the destructors and let the OS reclaim it.

**Comment by cameron314** [comment]
Don't destruct the ConcurrentQueue then :-)

**Comment by bear24rw** [comment]
Wildly obvious solution 😅 Simply constructing my queue with `new` instead of as a smart pointer works great :)
