### ISSUE TITLE
Is basic release-consume semantic guaranteed?

### ISSUE THREAD

**Issue by glglwty** [cameron314/concurrentqueue#37]
I have a question about a statement in the document. The document says
> Note that it is up to the user to ensure that the queue object is completely constructed before being used by any other threads (this includes making the memory effects of construction visible, possibly via a memory barrier

Suppose I have a `int* a`, I assigned `*a = 10` and  push `a` into the queue in thread 1, then thread 2 gets the pointer from the queue. Is that thread guaranteed to see `*a == 10`? If not, how can I workaround it by applying a memory barrier? Since `int*` isn't an atomic variable, trivially adding std::atomic_thread_fence does not seem to make any difference. I might be misunderstanding memory order stuffs or the document, though.

Thanks!

**Comment by cameron314** [comment]
Yes, the queue guarantees release-consume semantics for elements that are enqueued/dequeued. `*a == 10` will never be violated in your example.

That paragraph in the README refers to the queue object itself -- in other words, don't start using the queue if not all threads know about it yet. In practice, this is rarely an issue (indeed, often the queue is created before any of the threads are).
