### ISSUE TITLE
Naming conflict

### ISSUE THREAD

**Issue by JPewterschmidt** [cameron314/concurrentqueue#373]
It's quiet easy to cause a error which the compiler would complain that
> error: expected unqualified-id before numeric constant
> 343 |         static const size_t BLOCK_SIZE = 32;

Would you please rename those numeric constant into whatever not like macros? Although I can write `#undef BLOCK_SIZE` before include the header of `ConcurrentQueue` to solve the problem.

**Comment by JPewterschmidt** [comment]
I can submit a PR if you'd like

**Comment by cameron314** [comment]
Yes, this is unfortunate. However, [as I've explained previously](https://github.com/cameron314/concurrentqueue/issues/280#issuecomment-1427083441), I cannot change this name without breaking the API.
