### ISSUE TITLE
Weird dequeue behavior 

### ISSUE THREAD

**Issue by ankan1097** [cameron314/concurrentqueue#375]
Hi,
I am using concurrentqueue for a long time and it performed very well till now. I am using it in several places in a network packet capture application. But nowadays the throughput of network data has gone up by manifold and I have started witnessing a weird dequeue behavior. This is my enqueue code
```cpp
        struct sc_packet *next; 
	struct sc_packet *pkt;  
	for (next = pl->head; (pkt = next) && ((next = next->next), 1);)  
	{
		long ts = pkt->ts_sec * 1e9 + pkt->ts_nsec;
		st->enqueue_count++;
		L_(linfo) << "sc_packet timestamp: " << ts;
		L_(linfo) << "Current enqueue count: " << st->enqueue_count;
		st->dest->enqueue(pkt);
	}
```
Here `sc_packet` is an internal network packet structure, `st` is object of another struct which has a `moodycamel::ConcurrentQueue<sc_packet*> *dest` and  `long enqueue_count` as member. `pl` is a linked_list type data structure of sc_packets. Here the sc_packet timestamp is a unique key across all sc_packets and always increasing from packet to packet.
Now my dequeue code is
```cpp
        sc_packet *pkt;
	vector<sc_packet*> dequeued_items;
	long dequeue_count = 0;
	int count = 0;
	dequeued_items.reserve(DEQUEUE_LIST_SIZE);
	while (terminate == false)
	{
		if ((count = incoming_packet_queue.try_dequeue_bulk(ctok, dequeued_items.begin(), DEQUEUE_LIST_SIZE)) > 0)
		{
			dequeue_count += count;
			for (int i = 0; i < count; i++)
			{
				pkt = dequeued_items[i];
				long ts = pkt->ts_sec * 1e9 + pkt->ts_nsec;
				L_(linfo) << "dequeued_packet timestamp: " << ts;
				L_(linfo) << "Current dequeue count: " << dequeue_count;
                         }
                }
        } 
```
So basically after dequeuing I am again printing the timestamp and dequeue count. Here my observation is, though the counts for enqueuing and dequeuing match always, there are few mismatches in the timestamp printing before enqueue and after dequeue. After looking closely I found out, though all timestamps were printed correctly before enqueue(i.e. printed timestamps are strictly increasing), after dequeuing there are some timestamps printed twice, on the other hand few timestamps haven't printed at all. So basically some sc_packet objects are dequeued twice and some others haven't at all. Which means some sc_packet objects are being overwritten by others inside the queue. Here is only one producer thread and one consumer thread at work. I have tried with readerwriterqueue and observed the same behavior. Please suggest me why is this happening and what can I do to prevent it.

**Comment by cameron314** [comment]
First, fix the undefined behaviour in the dequeue loop -- the vector is always of size 0 yet being written to and indexed past the end of it.

**Comment by cameron314** [comment]
Is it possible that the sc_packet is freed or reused before the dequeuer is done with it?

**Comment by ankan1097** [comment]
No, I am calline reserve function to allocate memory for the vector
```cpp
dequeued_items.reserve(DEQUEUE_LIST_SIZE);
```
Here DEQUEUE_LIST_SIZE is a constant which has value of 100.

**Comment by cameron314** [comment]
Aside: if you have a single-producer single-consumer use case, consider using ReaderWriterQueue instead, as it will be faster.

**Comment by cameron314** [comment]
> No, I am calline reserve function to allocate memory for the vector
> 
> ```c++
> dequeued_items.reserve(DEQUEUE_LIST_SIZE);
> ```
> 
> Here DEQUEUE_LIST_SIZE is a constant which has value of 100.

Reserving and resizing are not the same thing.

**Comment by cameron314** [comment]
You have a queue of pointers. When enqueueing, the pointer is copied into the queue. When dequeueing, the pointer is copied out. At no point is the structure being pointed to copied in this sample code.

**Comment by ankan1097** [comment]
> You have a queue of pointers. When enqueueing, the pointer is copied into the queue. When dequeueing, the pointer is copied out. At no point is the structure being pointed to copied in this sample code.

Hi Cameron, this insight really solved our issue. Turns out the pointers are getting deallocated by another thread before we are dequeuing them and processing. Now we have made the deallocation same threaded as processing so this issue is gone completely. Thank you so much. Closing this.
