### ISSUE TITLE
The website is invalid and cannot be opened

### ISSUE THREAD

**Issue by cy2333ytu** [cameron314/concurrentqueue#387]
I want to have a overview of the internal design, but the following website provided cannot be opened 
[overview of the internal design](http://moodycamel.com/blog/2014/a-fast-general-purpose-lock-free-queue-for-c++)

**Comment by cameron314** [comment]
Works for me. Is it back for you?

**Comment by cy2333ytu** [comment]
> Works for me. Is it back for you?

It's fine, I find there is something wrong with my Internet
