### ISSUE TITLE
in-order dequeue when used as MPSC

### ISSUE THREAD

**Issue by frankist** [cameron314/concurrentqueue#400]
Hi Cameron!

Thanks for your work on this. I have a question, about dequeue ordering. I understand that when one uses only one producer (SPMC), the dequeue is in order (strict FIFO). However, with your implementation, such guarantee does not exist for MPSC, correct?

However, I was thinking - if I have multiple producers and one single consumer (MPSC), I could use an extra atomic counter that gets incremented on the producers' side, and a reordering window on the consumer side. This could ensure some strict FIFO order. Do you see any major issues with this approach?
﻿
﻿To give a bit of context, my problem is that I have a producer that is sequential in the way it pushes tasks, but it is constantly hopping between threads (it's a boost strand). So, the objects will be dequeued out of order.

**Comment by cameron314** [comment]
I'm not familiar with Boost strands, but it sounds like the producing is serialized even though it's from multiple threads. If that's the case, use a single producer token, and you'll have ordering.

**Comment by frankist** [comment]
Thanks! That makes a lot of sense!

**Comment by frankist** [comment]
@cameron314, just one last question - how many producers is too many producers? Is there a scalability issue I should take into consideration when instantiating multiple producer/consumer objects?

**Comment by cameron314** [comment]
Well, each producer ends up associated with sn internal sub-queue, so if you have 1000 producers, then in the worst case a consumer needs to check 1000 sub-queues to establish the queue is empty.

Note that sub-queues are reused, so if you create 1000 producer tokens but only one is alive at once, there will only be one sub-queue.
