### ISSUE TITLE
Passing iterator references to enqueue_bulk and variants

### ISSUE THREAD

**Issue by koraa** [cameron314/concurrentqueue#46]
Hi,

I am working on a channel abstraction over concurrentqueue; one of the features allows me to limit the number of elements in the queue dynamically.

It's similar to your blocking queue, but it allows me to change the capacity of the queue on the fly and it allows me to enqueue_bulk with a count much greater than the capacity.

I do this by waiting until there is some free space, filling that up with elements from the iterator and then repeating that until the iterator is empty.

To achieve this, I am passing a reference to the iterator my wrapper got rather than it's value, so outside of enqueue_bulk I my iterator will be incremented and in the next step I can just pass the same to enqueue_bulk again.

Unfortunately, eneuque_bulk decays my references to values. I was able to change this, but I am not quite sure this was by design.

Here is the code, hopefully with fewer bugs than the last one :)

https://github.com/SoftwearDevelopment/concurrentqueue/commit/95a00a3d1b40fb0c80df9af96d494cc57cffe058

**Comment by cameron314** [comment]
Hmm. This is interesting. The iterator wasn't intended to be accepted by reference. Passing an l-value iterator object should not cause it to be modified.

But I don't see why explicitly passing an iterator reference shouldn't be allowed. (Note that MSVC's `std::vector` doesn't allow this, though.) What I don't understand is why the perfect forwarding doesn't already handle this.

I'm looking into it.

**Comment by cameron314** [comment]
You must be specifying the `It` type explicitly in your code?

**Comment by koraa** [comment]
Yes, I am calling `enqueue_bulk<It&>(...)`.

**Comment by cameron314** [comment]
I'm inclined to leave it the way it is. It seems like all other containers accept iterators by value. And this way, you can't accidentally pass a reference to an iterator without meaning to.

To achieve what you want, I can think of two simple options:
1) Use a normal pass-by-value iterator, then increment the reference to match after the enqueue
2) Use a wrapper object, something like `std::reference_wrapper` but for input iterators:

    template<typename It>
    struct input_iterator_reference_wrapper {
        input_iterator_reference_wrapper(It& ref) : ref(ref) { }
        auto operator*() const -> decltype(*ref) { return *ref; }
        input_iterator_reference_wrapper& operator++() { ++ref; return *this; }
    private:
        It& ref;
    };

**Comment by koraa** [comment]
Hmm. OK.
(1) wouldn't work for single pass iterators thats why I avoided that, but (2) will probably so I'll go with that. I hoped I could save some code by passing references to templates ^^

I am not *that* deep into rvalue semantics, but I think you might consider actively decaying the Iterator instead of forwarding it, since I am not sure that the behavior we are seeing here is actually defined.

Thanks for the info and suggestions!

**Comment by cameron314** [comment]
Neither am I :-) I'll add the explicit decay, it's a good suggestion, thanks.
