### ISSUE TITLE
Strict aliasing warning with Android GCC 4.9

### ISSUE THREAD

**Issue by AstralStorm** [cameron314/concurrentqueue#48]
Compiler version:
arm-linux-androideabi-c++ (GCC) 4.9 20140827 (prerelease)

Built in C++-1y mode (almost C++14).

The warning is as follows:
```
include/moodycamel/concurrentqueue.h:1575:97: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
    inline T* operator[](index_t idx) MOODYCAMEL_NOEXCEPT { return reinterpret_cast<T*>(elements) + static_cast<size_t>(idx & static_cast<index_t>(BLOCK_SIZE - 1)); }
```
(line may be slightly off due to additional comments inserted)

Warning seems correct in that char object is accessed through T*, which is not allowed in C++11 and newer.

**Comment by cameron314** [comment]
Hmm, that's unfortunate. In that case, is it even possible (in a standard-compliant way) to declare an object with enough bytes for N `T` objects without initializing said memory?

**Comment by cameron314** [comment]
Ooh. Apparently C++11 allows non-POD types in unions now, for exactly this kind of scenario. The constructors/destructor are not called automatically, which is exactly what I was trying to avoid with my `char[]` workaround. I'll try that if MSVC supports it.

**Comment by cameron314** [comment]
Aw, no, unions can't hold any type with a non-trivial copy constructor.
It looks like there's no built-in way to do this sort of manual memory management. However, I can use intermediate casts to hopefully trick the compiler into doing the right thing. See http://stackoverflow.com/questions/13466556/aligned-storage-and-strict-aliasing

**Comment by cameron314** [comment]
Let me know if this fixes the warning. Thanks!

**Comment by AstralStorm** [comment]
Seems fine.

**Comment by cameron314** [comment]
Great, thank you!
