### ISSUE TITLE
Two-step Initialization

### ISSUE THREAD

**Issue by computerquip** [cameron314/concurrentqueue#54]
Some of us who haven't figured out how to handle errors in constructors tend to use two-step constructors. It should be pretty basic to implement for the queue here... although ugly (as is every two-step initialization).

**Comment by cameron314** [comment]
To clarify, are you asking for a separate `init` method on the queue object? Why?

**Comment by computerquip** [comment]
If a concurrent_queue is part of an object that requires two-step initialization, I have no way of setting max capacity for the concurrent queue since I'm not given enough information in the initializer in this case. I don't seem to have any way of controlling memory after initialization.

**Comment by cameron314** [comment]
I see. Maybe use a unique_ptr?

**Comment by computerquip** [comment]
I'd rather not but I worked around it regardless. I'll close the issue for now and maybe propose something later.

**Comment by cameron314** [comment]
Sure. Another option would be to move-assign it a temporary once you know what parameters you want to pass to the constructor.
