### ISSUE TITLE
Redundant #IfElse For Define

### ISSUE THREAD

**Issue by BlamKiwi** [cameron314/concurrentqueue#57]
concurrentqueue.h : line 240-244
`#ifdef __GNUC__
    typedef std::max_align_t max_align_t;      // GCC forgot to add it to std:: for a while
#else
    typedef std::max_align_t max_align_t;   // Others (e.g. MSVC) insist it can *only* be accessed via std::
#endif`

This appears to be redundant. ;)

**Comment by cameron314** [comment]
Ah, but that's not what's in the source file ;-)
The comments should make it clear why I needed the `#ifdef` :-)
