### ISSUE TITLE
Please, add libcds in benchmarks

### ISSUE THREAD

**Issue by masterspline** [cameron314/concurrentqueue#61]
libcds https://github.com/khizmax/libcds is C++ library of Concurrent Data Structures

Please, add it in your benchmarks

**Comment by schoetbi** [comment]
I started an implementation here: https://github.com/schoetbi/concurrentqueue/tree/IntegrateLibcds 
But I only integrated the vyukov queue and only the vs2017 project files compile at the moment.

What cds queue types do you want to include in this benchmark?

**Comment by cameron314** [comment]
Unfortunately, I don't have time to add new benchmarks at this point. Feel free to submit pull requests, however.
