### ISSUE TITLE
can it compatible to gcc4.4.4

### ISSUE THREAD

**Issue by lilothar** [cameron314/concurrentqueue#63]
for c++0x

**Comment by cameron314** [comment]
Unfortunately not; older versions of GCC have bugs in their implementation of atomics, which I rely on heavily. 

GCC 4.4 doesn't implement [certain key parts][1] of c++11 at all, like the memory model.

Nothing I can do, sorry! 

[1]: https://gcc.gnu.org/gcc-4.4/cxx0x_status.html
