### ISSUE TITLE
Making concurrentqueue even better :)

### ISSUE THREAD

**Issue by caustik** [cameron314/concurrentqueue#65]
Thanks for creating this project and for making the source code available as a simple drop-in and cross-platform implementation. I'm impressed by the lengths you went to with developing the idea, implementing it, building the tests and metrics to prove its worth. Much appreciation also for making it commercial-friendly because as I'll attempt to demonstrate it encourages external contributions and evolution ;)

For NUMA support, we ended up implementing the SALSA algorithm (which I've seen you mention, so I know you're at least a little familiar ) -- but we ran into some issues. In particular, the requirement of "CPU binding" is not generally cross-platform, and the paper's talk of using mfence as an alternative didn't seem to work at all. So instead we did a little bit of a rework which uses an atomic OR 32-bit operation for stealing and an atomic increment for fast-path consumers, using CAS only in the event of a "steal" operation.

Anyway, wanted to drop this note to encourage you to check out SALSA in depth if you haven't already, and to warn you about the CPU bind issue. But the good news is that the workaround of a single interlocked increment on the consumer fast-path, with an interlocked OR and CAS on the "steal" path is tenable and has better performance than concurrentqueue in all permutations of 1x1, 1xN, Nx1, NxN consumer x producer. The CPU bind path is even faster, but it won't work on OSX since they don't provide a way to bind to a specific CPU core (take it up with their kernel team, whom I am forever disappointed with). 

Not sure if you are aware, but there's an implementation of SALSA (not ours) available here: https://subversion.assembla.com/svn/scpools/SCPools which is not totally complete but is plenty enough to guide you toward a proper implementation, particularly when armed with the CPU bind warning which I'm not sure if they're aware of (haven't tried contacting the authors). There also seem to be various versions of their paper floating around, and this seemed to be the most up-to-date and complete (though I may be wrong) http://webee.technion.ac.il/~idish/ftp/SALSA-full.pdf.

**Comment by cameron314** [comment]
Thanks!

This queue is never going to be really efficient in a NUMA environment, but if I ever design another one, I'm going to keep this in mind. Much appreciated!
