### ISSUE TITLE
Android ARMv7a libstdc++: blockingconcurrentqueue build fails with memory model failure

### ISSUE THREAD

**Issue by AstralStorm** [cameron314/concurrentqueue#68]
Unfortunately, the log doesn't say which line in blockingconcurrentqueue.h waitWithPartialSpinning.

Android NDK r10e, android-19 platform, gnustl_static.

Log snippet:
  ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/atomic_base.h: In member function 'bool moodycamel::details::mpmc_sema::LightweightSemaphore::waitWithPartialSpinning(int64_t)':
  ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/atomic_base.h:584:70: error: failure memory model cannot be stronger than success memory model for '__atomic_compare_exchange'
    return __atomic_compare_exchange_n(&_M_i, &__i1, __i2, 0, __m1, __m2);

**Comment by AstralStorm** [comment]
It seems that 3 argument form of compare_exchange_strong form is broken on this platform - converting to 4 argument form avoids the build failure.

**Comment by cameron314** [comment]
Hmm, that's unfortunate. Easy fix though, thanks for finding this!
