### ISSUE TITLE
Is there any api that I could  insert element at front of the queue, not at the end?

### ISSUE THREAD

**Issue by xeoshow** [cameron314/concurrentqueue#69]
Hi,

I am using concurrentqueue (blocking version) in my product, and now I have a need that insert some special element at the front of current queue, not at the end of the queue.

Is it possible? If yes how to do? Thanks!

Best regards, Jason

**Comment by cameron314** [comment]
Sorry, I'm afraid this isn't possible.

**Comment by cameron314** [comment]
Perhaps you could simulate this with two queues -- one high priority that is usually empty and one low priority with the normal elements. You'd lose the blocking feature but could do your own with only a little more overhead using a `std::condition_variable` and a bit of state.
