### ISSUE TITLE
read access violation -> get_or_add_implicit_producer -> on calling enqueue()

### ISSUE THREAD

**Issue by jensweller** [cameron314/concurrentqueue#71]
I try to use the blockingconcurrentqueue in a simple project.

I add a object from a userdefined class with enqueue() and get an exception in the method get_or_add_implicit_producer.

it seems mainhash is not valid:

Unhandled exception thrown: read access violation.
hash was 0xCCCCCCCC.

I using Visual Studio 2015 with Update 3.

Do I have to make any settings?

**Comment by cameron314** [comment]
No special settings, no. Can you rustle up a reproducible example for me?

**Comment by jensweller** [comment]
Sorry. My Mistake. Resolved. You can close this issue.

**Comment by cameron314** [comment]
No worries! :-)

**Comment by SephVelut** [comment]
I would like to know what you did to resolve it
