### ISSUE TITLE
How to stop wait_dequeue in blockingconcurrentqueue

### ISSUE THREAD

**Issue by jensweller** [cameron314/concurrentqueue#72]
Hi.

I have a loop and wan't to exit this loop

```
while (run_)
{
	T object;
	queue_->wait_dequeue(object);
	func_(object);
}
```

How is it possible to stop waiting.

```
void Stop()
{
    run_ = false;
    queue_-> ??
}
```

**Comment by cameron314** [comment]
There's no special support for this scenario right now.
You'll need to either enqueue a special sentinel element to unblock the consumer, or use the `wait_dequeue_timed` methods that accept a timeout parameter.

**Comment by jensweller** [comment]
Hm. 
1. If I use with timeout its like a non blocking que and I have to check the result of wait_dequeue_timed().
2. My class ist template based. So in my Stop method i can not enqueue any object. 
I have to enqueue an object of T(). But then I have no special sentinel element which I do not have to process after dequeue.

Also its not possible to clear the queue. Is this correct?

**Comment by cameron314** [comment]
1. Yes, but you can block for fixed slices of time (e.g. 100ms).
2. Right, but you could wrap your elements in a custom type with a boolean sentinel flag
3. Right, there's no way to clear the queue (though you can bulk-dequeueing everything)

**Comment by jensweller** [comment]
2. Yes thats correct but:

```
template <typename T>
class Wrapper
{

   Wrapper(bool isStop) : isStop_(isStop) 

  // how to initialize reference of T ?
  // use a copy instead of a reference is not so pretty

   bool isStop_;
   T& item_;
}

void Stop()
{ 
   auto wrapper = Wrapper<T>(true);
    queue_->enqueue(wrapper);
}
```

**Comment by cameron314** [comment]
Yes, there will be an extra copy; for small POD types this should not be a problem, since the overhead is negligible; for other types this is still not a problem since they can be moved in (and the queue will move your wrapper in turn, assuming you provide a move constructor/assignment operator).

**Comment by SungJJinKang** [comment]
i found solution.!!
Pass dummy object to queue.
