### ISSUE TITLE
get_block_index_index_for_index() accesing null localBlockIndex

### ISSUE THREAD

**Issue by Manu343726** [cameron314/concurrentqueue#75]
At line 2853 of concurrentqueue.h I reach a situation where the queue internals access a null pointer returned by an atomic load:

``` cpp
localBlockIndex = blockIndex.load(std::memory_order_acquire); // Returns null
auto tail = localBlockIndex->tail.load(std::memory_order_acquire); // Segfault here, localBlockIndex is null
```

This happens while extracting a queue element with `try_dequeue()` (Which invokes `likely(best->dequeue())`, which invokes `(ImplicitProducer*)this->dequeue()`, which invokes `get_block_index_entry_for_index()`, which finally invokes `get_block_index_index_for_index()`).

I would like to know if this is not the expected behavior (i.e. a bug) or if I may be invoking some weird state due to a misuse of the queue.  What I'm basically doing is to have a job-stealing job system of 4 threads, one queue per thread, where each thread queue could be being accessed from any of the other threads.

Thanks.

**Comment by cameron314** [comment]
This is definitely not supposed to happen, so it's either a bug in the queue or your usage of it.

Looking at the source, `blockIndex` being null can only happen if `malloc` fails during implicit producer creation. There's indeed a bug in that I should check for this during enqueue -- but without the check, enqueue should crash in this case, never getting as far as dequeue.

So, this looks like memory corruption, though I'm not sure how/why. Can you rustle up a small example?
