### ISSUE TITLE
Pointer in class

### ISSUE THREAD

**Issue by Victsz** [cameron314/concurrentqueue#79]
As mentioned in How to dequeue types without calling the constructor, a solution without internal pointer has provided. But what if I do need a pointer inside the class like 
class DataWrapper
{
public: 
    long long Number;
    DataType dataType;
    unsigned char* buffer;
}
The bufferis filled by std::copy from another class indicated by dataType filed;
The consumer thread will parse the content and try to convert back to the original class, but the buffer seems to be deleted.
 1. OrgClass tmp;
     memcpy(&tmp, content, sizeof(tmp)); //std::terminate()
2.
           auto tmp = *(OrgClass *)content;//Stuck

**Comment by cameron314** [comment]
I'll need a bit more code to figure out what's going on here. `DataWrapper` doesn't have any internal pointers -- `buffer` seems to point to memory outside of the object itself.
