### ISSUE TITLE
wait_dequeue_timed asserts on received signal

### ISSUE THREAD

**Issue by kontza** [cameron314/concurrentqueue#80]
Hi,

I'm building a new-style Linux daemon with two threads (a producer and a consumer). A new-style daemon should react to SIGHUP, and SIGTERM. In my main thread's processing loop I'm calling `wait_dequeue_timed`. During my trial runs, I noticed that when I sent SIGHUP (via `kill -HUP [pid]`), the wait finished due to assertion failing:
`Assertion failed: (success), function wait_dequeue_timed, file readerwriterqueue.h, line 748.`

**Comment by cameron314** [comment]
Looks like a bug, thanks for reporting it! I'll try to fix this soon.

**Comment by cameron314** [comment]
Might be related to #105, but on Linux.

**Comment by cameron314** [comment]
Note that this is the `concurrentqueue` repo, not the `readerwriterqueue` repo.

Regardless, they use the same semaphore implementation. I suspect this is related to #173, which should now be fixed.

Please reopen if the bug still manifests.
