### ISSUE TITLE
Compilation error C4703: potentially uninitialized local pointer variable 'idxEntry' used

### ISSUE THREAD

**Issue by narrill** [cameron314/concurrentqueue#81]
concurrentqueue.h won't compile as-is for me in Visual Studio Enterprise 2015. I had to change `BlockIndexEntry* idxEntry;` to `BlockIndexEntry* idxEntry = nullptr;` at line 2575.

**Comment by cameron314** [comment]
Thanks! I didn't notice this before.

**Comment by cameron314** [comment]
Wait, scratch that. Looking more closely at the code, it appears to be correct in all paths. I understand why the compiler has a hard time proving this, though, since the initialization is done conditionally and only in another function. I'll add an `= nullptr` to appease the compiler.
