### ISSUE TITLE
Does ConcurrentQueue support non-copyable objects?

### ISSUE THREAD

**Issue by narrill** [cameron314/concurrentqueue#83]
Pretty self-explanatory, does this work with move-only objects? I'm using the following, and I'm still getting "attempting to reference a deleted function" errors from the copy constructor.
```
// items is a std::array<T, N> &&, where T is movable but not copyable
m_queue.enqueue_bulk(std::make_move_iterator(std::begin(items)), items.size());
```

**Comment by cameron314** [comment]
Yes, it does! Is your move constructor declared `noexcept`?

**Comment by narrill** [comment]
That was it! Thanks a bunch.

**Comment by cameron314** [comment]
No problem :-) Good timing, I happen to be online for a few minutes at the moment.

**Comment by narrill** [comment]
No kidding. Definitely wasn't expecting a response that quickly.
