### ISSUE TITLE
Possible memory leak with tokens

### ISSUE THREAD

**Issue by narrill** [cameron314/concurrentqueue#85]
I've got a system set up with two queues and with each thread (eight on my machine) having both a consumer and a producer token for both queues. Every thread is both producing and consuming at more or less the same rate.

When I don't use the tokens the memory usage stays around 1mb for the entire test (which is around 30 seconds long), but when I do use them it increases throughout the test (to about 4mb by the end with optimizations off and to ~25mb with `-O3` in clang and `-Ox` in MSVC).

The only change is whether the tokens are used:
```C++
m_queue.enqueue(/*qd.pt,*/ std::forward<queue_item_t>(item)); // From this
m_queue.enqueue(qd.pt, std::forward<queue_item_t>(item)); // To this
```

I took some heap snapshots, and basically all of the allocations happen in `requisition_block`, so this smells a whole lot like a memory leak, unless I'm using the tokens incorrectly. The queue should only ever be holding ~4kb of actual data at any one time.

**Comment by cameron314** [comment]
Hmm, I'll have to look into this. I don't have time at the moment, give me week or so.

**Comment by narrill** [comment]
Okay. I'll see if I can put together a minimal program that reproduces the issue.

**Comment by cameron314** [comment]
Thanks!

**Comment by narrill** [comment]
This might not be as big a deal as I thought. I was having trouble creating a test that would reproduce this behavior, so I decided to just run my original longer and see if the memory usage stabilized eventually. And it turns out it does; it jumps up really quickly over the first thirty seconds or so, then it levels out and only increases very periodically. After six minutes the memory barely changes.

I'm still a little bit confused though, because like I said the queue should only ever be holding ~4kb of actual data; I have eight threads running, each of which enqueues eight objects in bulk then begins dequeueing individually, and once a thread's eight items are all dequeued it queues eight more. The objects themselves are only 64 bytes a piece.

Is it the heuristic data in the tokens that's taking up that space?

**Comment by cameron314** [comment]
Tokens are small and of fixed size, we can rule those out. But, using a producer token changes the type of internal queue being used to the "explicit queue".

Explicit queues don't try as hard to recycle memory -- once they acquire a block they never release it back to the general pool. However, they reuse blocks internally once completely drained, so there shouldn't be more than two or three per explicit queue.

Each block has room for 32 elements by default, so that adds up to 8*3*32*64 bytes or on the order of 50KB plus the indexes, etc. So it does look like a very weird leak, or most likely something accidentally inefficient. Worth investigating either way :-)

**Comment by cameron314** [comment]
To address your update -- yes, a block is only reused once completely drained, so it's possible to have an extra block hanging around or sometimes more depending on how fast the dequeues are propagated to the producer thread.

If you could keep going with the test case isolation I'd really appreciate it!

**Comment by narrill** [comment]
Yeah, we're looking at something like 3000 blocks here, I agree it's worth looking into even if it isn't a leak per se. And the good news is that I'm still able to get ~30 million objects per second both into and out of the queue in my tests (up from ~12 million without the tokens), so the extra allocations aren't slowing things down significantly.

I'll let you know once I've got a test case worth looking at 👍

**Comment by cameron314** [comment]
Thanks :-)
As a temporary measure you can try using just consumer tokens. Most of the performance gain with tokens is on the consuming end.
