### ISSUE TITLE
Sorting queue

### ISSUE THREAD

**Issue by filippobistaffa** [cameron314/concurrentqueue#86]
I plan to use your queue in a scenario in which a bunch of threads push to the queue, and then, after all the "production" is done, I have one thread that reads the content of the queue.
Might be a stupid question, but is it possible to sort the queue (e.g., by using std::sort) after all the producers are done pushing things to the queue? Or should I just copy everything to a normal vector and sort that?

**Comment by cameron314** [comment]
You'll have to extract all elements and then sort them afterwards.

The queue doesn't expose any iterators, since this wouldn't be safe under contention. On top of that, the elements are not contiguous internally, making random access iterators inefficient to implement in any case.

**Comment by filippobistaffa** [comment]
Ok, thanks for the answer!

**Comment by cameron314** [comment]
Closing for now, a sorting function and/or iterators aren't in my future plans.
