### ISSUE TITLE
Build fail on arm v8 platform

### ISSUE THREAD

**Issue by falconray0704** [cameron314/concurrentqueue#96]
nvidia@tegra-ubuntu:/md/ray/github/concurrentqueue/build$ make
test -d bin || mkdir bin
g++ -std=c++11 -Wall -pedantic-errors -Wpedantic -Wconversion -pthread  -g -O0    -fno-elide-constructors ../tests/common/simplethread.cpp ../tests/common/systemtime.cpp ../tests/unittests/unittests.cpp -o bin/unittests -lrt
../tests/unittests/unittests.cpp: In instantiation of ‘bool moodycamel::ConcurrentQueueTests::full_api() [with Traits = moodycamel::ConcurrentQueueDefaultTraits]’:
../tests/unittests/unittests.cpp:285:3:   required from here
../tests/unittests/unittests.cpp:3517:9: warning: unused variable ‘lockFree’ [-Wunused-variable]
    bool lockFree = ConcurrentQueue<Foo, Traits>::is_lock_free();
         ^
../tests/unittests/unittests.cpp: In instantiation of ‘bool moodycamel::ConcurrentQueueTests::full_api() [with Traits = moodycamel::SmallIndexTraits]’:
../tests/unittests/unittests.cpp:286:3:   required from here
../tests/unittests/unittests.cpp:3517:9: warning: unused variable ‘lockFree’ [-Wunused-variable]
test -d bin || mkdir bin
g++ -std=c++11 -Wall -pedantic-errors -Wpedantic -pthread  -O3 -g -DNDEBUG ../tests/common/simplethread.cpp ../tests/common/systemtime.cpp ../tests/fuzztests/fuzztests.cpp -o bin/fuzztests -lrt
test -d bin || mkdir bin
g++ -std=c++11 -O3 -DNDEBUG -D__TBB_BUILD=1  -I../benchmarks -c ../benchmarks/tbb/cache_aligned_allocator.cpp ../benchmarks/tbb/concurrent_monitor.cpp ../benchmarks/tbb/concurrent_queue.cpp ../benchmarks/tbb/dynamic_link.cpp ../benchmarks/tbb/tbb_misc.cpp
ar -rc bin/libtbb.a cache_aligned_allocator.o concurrent_monitor.o concurrent_queue.o dynamic_link.o tbb_misc.o
rm -f cache_aligned_allocator.o concurrent_monitor.o concurrent_queue.o dynamic_link.o tbb_misc.o
test -d bin || mkdir bin
g++ -std=c++11 -Wall -pedantic-errors -Wpedantic -pthread  -O3 -g -DNDEBUG -I../benchmarks ../benchmarks/cpuid.cpp ../tests/common/simplethread.cpp ../tests/common/systemtime.cpp ../benchmarks/benchmarks.cpp -o bin/benchmarks -Lbin -ltbb -lrt
In file included from ../benchmarks/tbb/internal/../tbb_machine.h:249:0,
                 from ../benchmarks/tbb/internal/_concurrent_queue_impl.h:29,
                 from ../benchmarks/tbb/concurrent_queue.h:24,
                 from ../benchmarks/tbbqueue.h:5,
                 from ../benchmarks/benchmarks.cpp:29:
../benchmarks/tbb/internal/../machine/gcc_generic.h:80:62: error: extra ‘;’ [-Wpedantic]
     inline int clz(unsigned int x){ return __builtin_clz(x);};
                                                              ^
../benchmarks/tbb/internal/../machine/gcc_generic.h:81:68: error: extra ‘;’ [-Wpedantic]
     inline int clz(unsigned long int x){ return __builtin_clzl(x);};
                                                                    ^
../benchmarks/tbb/internal/../machine/gcc_generic.h:82:74: error: extra ‘;’ [-Wpedantic]
     inline int clz(unsigned long long int x){ return __builtin_clzll(x);};
                                                                          ^
makefile:41: recipe for target 'bin/benchmarks' failed
make: *** [bin/benchmarks] Error 1
nvidia@tegra-ubuntu:/md/ray/github/concurrentqueue/build$ 
nvidia@tegra-ubuntu:/md/ray/github/concurrentqueue/build$ 
nvidia@tegra-ubuntu:/md/ray/github/concurrentqueue/build$ 
nvidia@tegra-ubuntu:/md/ray/github/concurrentqueue/build$ 
nvidia@tegra-ubuntu:/md/ray/github/concurrentqueue/build$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/aarch64-linux-gnu/5/lto-wrapper
Target: aarch64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu/Linaro 5.4.0-6ubuntu1~16.04.5' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-libquadmath --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-arm64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-arm64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-arm64 --with-arch-directory=aarch64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-multiarch --enable-fix-cortex-a53-843419 --disable-werror --enable-checking=release --build=aarch64-linux-gnu --host=aarch64-linux-gnu --target=aarch64-linux-gnu
Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu/Linaro 5.4.0-6ubuntu1~16.04.5) 
nvidia@tegra-ubuntu:/md/ray/github/concurrentqueue/build$ 
nvidia@tegra-ubuntu:/md/ray/github/concurrentqueue/build$ g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/aarch64-linux-gnu/5/lto-wrapper
Target: aarch64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu/Linaro 5.4.0-6ubuntu1~16.04.5' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-libquadmath --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-arm64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-arm64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-arm64 --with-arch-directory=aarch64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-multiarch --enable-fix-cortex-a53-843419 --disable-werror --enable-checking=release --build=aarch64-linux-gnu --host=aarch64-linux-gnu --target=aarch64-linux-gnu
Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu/Linaro 5.4.0-6ubuntu1~16.04.5) 
nvidia@tegra-ubuntu:/md/ray/github/concurrentqueue/build$ 
nvidia@tegra-ubuntu:/md/ray/github/concurrentqueue/build$ 
nvidia@tegra-ubuntu:/md/ray/github/concurrentqueue/build$ cat /proc/cpuinfo 
processor       : 0
model name      : ARMv8 Processor rev 3 (v8l)
BogoMIPS        : 62.50
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x1
CPU part        : 0xd07
CPU revision    : 3

processor       : 3
model name      : ARMv8 Processor rev 3 (v8l)
BogoMIPS        : 62.50
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x1
CPU part        : 0xd07
CPU revision    : 3

processor       : 4
model name      : ARMv8 Processor rev 3 (v8l)
BogoMIPS        : 62.50
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x1
CPU part        : 0xd07
CPU revision    : 3

processor       : 5
model name      : ARMv8 Processor rev 3 (v8l)
BogoMIPS        : 62.50
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x1
CPU part        : 0xd07
CPU revision    : 3

nvidia@tegra-ubuntu:/md/ray/github/concurrentqueue/build$

**Comment by cameron314** [comment]
Sorry it took me so long to get around to this, but it should be fixed now.
