### ISSUE TITLE
blocking queue wait reports 100% cpu time under Android 7

### ISSUE THREAD

**Issue by fdoyon** [cameron314/concurrentqueue#98]
I am using the ``BlockingConcurrentQueue`` in an android NDK project and I am having issues with the profiler reporting my NDK thread using 100% cpu when this thread is just idling in the ``sem_wait`` here: https://github.com/cameron314/concurrentqueue/blob/master/blockingconcurrentqueue.h#L196

Is this a debugger / profiler issue or am I actually draining my users' battery?
This queue is central to my system (realtime audio app, mixing 40 samples in realtime, I use the blocking queue to send commands to the IO thread)

Thanks for the great library!

**Comment by cameron314** [comment]
The short answer is I don't know :-)
Is it actually spinning in the loop, or is it repeatedly calling `wait()`?

**Comment by cameron314** [comment]
A couple counters (one incremented in the loop and one incremented in the function prologue) would disambiguate.

**Comment by palad1** [comment]
It’s just calling wait and blocking. I will try to create a repro with a call to sem_wait without the queue.

**Comment by cameron314** [comment]
So `sem_wait` is failing over and over with `EINTR`, then.

This could actually make sense if your profiler is repeatedly interrupting the process to sample where it's at; do you have access to an instrumenting profiler instead to test this theory?

**Comment by palad1** [comment]
Thanks!
I will try to use systrace - but failing that I might then try to procure a trial of VTune
